// content_est.js - ES&T version, condensed from content_v19.js (AMT length).
//
// ES&T Research Article constraints applied here:
//   * 7000-word limit -> main text held near 5500 body words (v19 was 13174)
//   * abstract 150-200 words (v19 was 461)
//   * four display items in the main text; everything else in the SI
//   * Introduction / Materials and Methods / Results and Discussion, with NO
//     separate Conclusions section ("any concluding statements are to be
//     incorporated under Results and Discussion")
//   * numbered citations in order of appearance -> written here as {{key}}
//     markers and numbered by build_est.js, so the order is never hand-kept
//
// Every statistic is carried over unchanged from content_v19.js; check_est.js
// verifies that, so condensation cannot silently alter a number.
module.exports = {
  title: "Hourly Satellite Formaldehyde Columns and Routine Surface Air Toxics Monitoring: Day-to-Day Agreement at 123 United States Sites",

  authors: ["[[Author list, affiliations and corresponding author to be completed.]]"],

  tocNote: "[[TOC/abstract graphic not yet built. Run Rscript R/16_toc_graphic.R, which writes output/figures/toc_graphic.tiff (300 dpi, 3.25 x 1.75 in, for submission) and toc_graphic.png (embedded here on the next build).]]",

  keywords: ["formaldehyde", "TEMPO", "satellite validation", "air toxics monitoring", "hazardous air pollutants", "geostationary remote sensing"],

  abstract: [
    "Formaldehyde (HCHO) is a carcinogenic hazardous air pollutant and a leading contributor to estimated cancer risk from U.S. outdoor air toxics. The geostationary Tropospheric Emissions: Monitoring of Pollution (TEMPO) instrument retrieves HCHO columns hourly over North America, but published evaluations compare it only with other column measurements. We compared TEMPO Level 3 version 4 HCHO columns with every valid integrated formaldehyde sample reported to the U.S. Air Quality System in 2024-2025: 16 383 samples at 123 sites in 37 states, over 24, 8 and 3 h. A screened observation was available for 70 % of 24 h samples; the pooled correlation with surface HCHO was 0.42, or 0.40 after removing site and month means. The distribution behind that average is the central result: at individual monitors the day-to-day correlation ranged from -0.24 to 0.89 (median 0.48). Days with a usable observation were also unrepresentative, carrying 0.52 µg m^{-3} (25 %) more surface HCHO than fully screened-out days. Among samples of equal duration the hour of collection mattered, but not uniformly: at one Colorado site only the window three hours after sampling carried day-to-day information, while at a second and at two California sites the sampling window itself worked."
  ],

  sections: [
    { h1: "Introduction", p: [
      "Formaldehyde (HCHO) is a carcinogenic hazardous air pollutant and one of the largest contributors to estimated cancer risk from outdoor air toxics in the United States{{zhu2017}}. Unlike most air toxics, ambient HCHO is predominantly secondary: it is produced during the oxidation of biogenic and anthropogenic volatile organic compounds, with smaller primary contributions from combustion and industrial sources. Downwind of Houston-area petrochemical facilities, secondary production accounted for 92 ± 4 % of HCHO against 4 ± 2 % from primary emissions{{parrish2012}}. Surface HCHO trends across the United States track temperature-dependent biogenic precursor emissions and are influenced by wildfires{{liu2026}}, and HCHO is produced within ageing wildfire plumes{{liao2021}}.",

      "Because HCHO is formed regionally and has a short lifetime, its column abundance can be observed from space and has been used to map surface concentrations and associated cancer risks{{zhu2017}}. TEMPO, launched in 2023 into geostationary orbit, measures HCHO hourly during daylight over North America at a spatial resolution of a few kilometres{{zoogman2017}}. Hourly observations resolve diurnal changes in ozone-NO_{x}-VOC chemistry{{jin2025}} and, in principle, allow satellite observations to be matched to the sampling periods of surface monitors.",

      "Validation of satellite HCHO has relied on aircraft profiles and ground-based column instruments. Aircraft comparisons found the Ozone Monitoring Instrument (OMI) HCHO product biased low by 22-45 % under polluted conditions and high at low columns{{zhu2020}}. For TEMPO, comparisons with the Pandonia Global Network characterised the retrieval's spatiotemporal performance{{rawat2026}}, and comparisons with Fourier transform infrared (FTIR) and Pandora spectrometers found a low bias of about 30 % while diurnal and seasonal variability were captured{{ortega2026}}. Surface measurements have been used differently and far less. Wang et al. compared seasonal means of surface HCHO at 45 Air Quality System (AQS) sites with OMI columns for 2006-2015, finding regional correlations of 0.56-0.87 in summer, weak or negative correlations in winter, and a seasonal amplitude 20-100 % larger in the column than at the surface{{wang2022}}. That comparison had to be seasonal: 24 h samples collected every sixth day and a single early-afternoon overpass yield few coincidences. For nitrogen dioxide, where the surface network is hourly and dense, TEMPO and TROPOMI columns have been compared with regulatory monitors directly{{acker2025}}{{nawaz2025}}. No equivalent comparison exists for formaldehyde, whose surface network is neither hourly nor dense. Evaluations of TEMPO HCHO published to date compare it with other measurements of the column — TROPOMI, Pandonia{{rawat2026}}, NDACC FTIR and Pandora{{ortega2026}}, and vertically integrated aircraft profiles — and these are the comparisons listed in the mission's own validation report{{nasaval2026}}. To our knowledge TEMPO HCHO has not been evaluated against surface concentration measurements from routine monitoring networks at daily or sub-daily resolution.",

      "An hourly geostationary instrument changes the arithmetic, because every sample day yields a dozen observations and the satellite can be matched to the hours a sample actually covers. Routine networks collect integrated samples designed for long-term risk assessment rather than satellite validation, so the practical questions are how often a usable observation is available, how well TEMPO tracks day-to-day variation at individual monitors, how much that varies from monitor to monitor, whether the days that survive cloud screening resemble the days that do not, and what limits the agreement that remains. Here we compare TEMPO Level 3 version 4 HCHO columns with surface HCHO measured in 2024-2025 at every United States monitor reporting formaldehyde to AQS: 123 sites in 37 states, including National Air Toxics Trends Stations, NCore multipollutant sites and Photochemical Assessment Monitoring Stations, with sample durations of 24, 8 and 3 h. Colorado, whose network reports through both AQS and the state's own data packets, is treated as a case study that supplies two diagnostics the national data cannot: an estimate of retrieval noise from successive scans, and a sub-daily record whose sampling window is fixed."
    ]},

    { h1: "Materials and Methods", p: [
      "Surface measurements. Formaldehyde is measured across the United States by state, local and tribal agencies and reported to AQS as parameter 43502{{epaaqs2026}}. Almost all use EPA Compendium Method TO-11A{{epato11a1999}}: air is drawn through a 2,4-dinitrophenylhydrazine-coated cartridge and the derivative quantified by high-performance liquid chromatography. Of the samples analysed here, 76 % were collected with a potassium-iodide ozone scrubber, 16 % on a bare silica cartridge and 8 % behind a heated ozone denuder. We retrieved every formaldehyde sample reported for 1 January 2024 to 31 December 2025 and retained all valid records: 16 383 samples at 123 sites in 37 states. AQS records the local standard time at which each sample began, the corresponding GMT time and the duration, so every sampling window is known without a time zone assumption. Records carrying an AQS null data qualifier were removed, and where more than one method at a site reported the same window their values were averaged. AQS reports these measurements in parts per billion carbon, which for formaldehyde equals parts per billion by volume; we converted to mass concentration at 25 °C and 1 atm.",

      "The network divides into three sampling regimes. One hundred and two sites collect 24 h samples (8730 samples, 30 states), almost all beginning at midnight local standard time, typically every third or sixth day. Forty sites collect 8 h samples (6972 samples, 29 states), every one in the same three fixed blocks beginning at 04:00, 12:00 and 20:00 local standard time. Four sites collect 3 h samples (681 samples): two Colorado ozone-precursor sites sampling only 06:00-09:00 MST, and two sites in California's San Joaquin Valley sampling five windows a day beginning at 05:00, 08:00, 12:00, 16:00 and 23:00 LST. The Colorado case study adds seven 24 h air toxics sites and the two 3 h sites through the state's annual data packets, which carry quality-control flags AQS does not hold; the same samples also reach us through AQS, allowing the two pathways to be cross-checked. One of the 3 h sites, Platteville, also reported formaldehyde to AQS through 2023, so its record is extended back to August 2023, the first month with TEMPO granules; the packets and the national comparison begin in 2024, and the second 3 h site reported no 2023 formaldehyde. Site descriptions, quality-control handling and a map are given in the Supporting Information (Figure S1, Tables S1 and S2).",

      "TEMPO columns and matching. We used the Level 3 version 4 HCHO product{{tempol3v4}}, currently provisional, which grids Level 2 retrievals from each scan to a 0.02° × 0.02° grid (about 2.2 km × 1.7 km at 39.5° N). Granules were identified with NASA's Common Metadata Repository, and a 5 × 5 block of grid cells centred on each site was requested through NASA's OPeNDAP service without screening, so that screening choices could be varied afterwards. A grid cell was used when the main data quality flag was 0, the effective cloud fraction was ≤ 0.2, the solar zenith angle was ≤ 70° and the snow and ice fraction was zero; the user guide advises that negative columns should not be excluded{{nasaguide2025}}, and they were retained. For each scan we averaged the screened cells in a 3 × 3 block (about 6.7 km × 5.1 km) and treated the scan as valid when at least half the block's cells passed. A sampling window is expressed as the set of hours it spans in UTC, and a scan is assigned to it when the hour containing the granule midpoint belongs to that set; the midpoint can differ from the time TEMPO viewed an individual site by tens of minutes. Lagged windows are the same set shifted by -3, 0, +3 or +6 h, applied only to sub-daily samples. Sensitivity to cloud thresholds of 0.1, 0.2 and 0.3, to 1 × 1, 3 × 3 and 5 × 5 blocks, and to all-day against midday scans was tested throughout (Figures S2 and S3).",

      "Statistics. We report Pearson (r) and Spearman (ρ) correlations by site, by season and pooled. Because surface HCHO and the column share a strong seasonal cycle, we also computed within-month anomalies by subtracting the site- and calendar-month mean from both variables, retaining site-months with at least three matched samples; correlations of these anomalies measure day-to-day covariation and are the quantity we rely on. Their p-values do not account for the degrees of freedom spent on the monthly means and are therefore optimistic, which no multiplicity correction repairs; counts of significant sites are given in the Supporting Information (Table S3) and nothing here rests on them. The pooled regression of surface concentration on the column uses ordinary least squares with fixed effects for site and calendar month. Reduced major axis slopes, mixed-effects models, Williams' test for dependent correlations{{steiger1980}} and the retrieval-noise estimator are described in the Supporting Information.",

      "Effective mixing height. To relate column to surface we converted the surface mass concentration to a number density n_{s} and defined an effective mixing height H_{eff} = Ω/n_{s}, where Ω is the TEMPO column: the depth of a uniform layer at the surface concentration that would contain the observed column. H_{eff} combines the vertical distribution of HCHO, biases in the retrieval and in the surface measurement, and the mismatch between sampling period and daytime satellite sampling, so we use it as a diagnostic and not as a physical boundary layer depth. Because AQS and the CDPHE packets report at standard conditions (25 °C, 1 atm), we converted to a mixing ratio, χ = C × 24.45/M with M = 30.026 g mol^{-1}, and then to a number density at the conditions of the air, n_{s} = 10^{-15} χ p/(k_{B}T), with p in Pa and T in K; the factor 10^{-15} combines the definition of a part per billion (10^{-9}) with the conversion from molecules m^{-3} to molecules cm^{-3} (10^{-6}). Nationally a fixed air temperature of 15 °C was used with the retrieved surface pressure; a 10 K error changes H_{eff} by 3 %.",

      "Observability of sample days. A sample day is observable when at least one scan passes screening; it is screened out when TEMPO returned granules covering the site but no scan passed; and it has no granule when TEMPO returned none. No-granule days are excluded from the observability comparisons, so that gaps in TEMPO's own sampling are not counted as screening. To establish what drives the rejections we re-evaluated every screened-out sample day with one screening criterion relaxed at a time. These relaxation counts are not mutually exclusive: a sampling period usually contains several scans, and different scans within it can fail different criteria. Two estimates of the difference in surface HCHO between observable and screened-out days are reported, both signed observable minus screened out. The first is the coefficient β in HCHO_{it} = α_{i} + γ_{m} + β·observable_{it} + ε_{it}, with fixed effects for monitor i and calendar month m and standard errors cluster-robust by monitor. The second takes deviations from each site-month mean, averages them within site-months to a single paired difference, and averages across site-months, with a confidence interval from a bootstrap resampling monitors (2000 replicates); no interval is reported for a stratum with fewer than five monitors, where such a bootstrap is degenerate rather than merely wide.",

      "All processing was done in R{{rcore2024}}; a single script downloads every input and produces all tables and figures (see Supporting Information and Code Availability)."
    ]},

    { h1: "Results and Discussion", p: [] },

    { h2: "Availability and Pooled Agreement", p: [
      "A screened TEMPO observation was available for 70 % of the 8730 national 24 h samples, with a median of 11 usable scans per sample day, against 75 % in the Colorado case study. Coverage varied widely between sites, from around 90 % in Arizona, southern California and on the Texas Gulf coast to below 50 % in western Oregon, Vermont and upstate New York, with the lowest values at Tualatin, Oregon (37 %) and Proctor Maple Research Center, Vermont (40 %). That availability primarily reflects the repeated sampling a geostationary orbit allows rather than any property of the retrieval: at a Pandonia site in New Jersey, hourly sampling yields a usable observation on about 50 % more days than an early-afternoon overpass alone would{{rawat2026}}, and modelled cloud fields imply that 68-93 % of days contain a clear-sky opportunity at some daylight hour against 33-69 % at a fixed early-afternoon overpass{{goldberg2025}}.",

      "Pooled across the 24 h sites, the daily mean column and the 24 h surface concentration correlated at r = 0.42 (ρ = 0.48, n = 6106), and after removing site and calendar-month means the day-to-day correlation was 0.40 (n = 5218 in 1262 site-months). The regression of surface concentration on the column, with fixed effects for site and calendar month, gave 0.163 ± 0.006 µg m^{-3} per 10^{15} molecules cm^{-2}. Table 1 summarises the comparison by sample duration. Median H_{eff} across the 24 h sites was 1.09 km against a median TEMPO planetary boundary layer height of 1.04 km; the agreement of the two medians is not by itself evidence of a well-mixed profile, since H_{eff} also absorbs retrieval bias, the free-tropospheric column and the mismatch between a 24 h sample and daytime satellite sampling."
    ]},

    { table: {
      caption: "Table 1. The national comparison by sample duration. Sites and samples are those reported to AQS for 2024-2025; matched counts and correlations use the primary screening (effective cloud fraction ≤ 0.2, 3 × 3 cell block) with scans inside the sampling window. Day-to-day correlations use deviations from site and calendar-month means. Median day-to-day r by site is computed over sites with at least 10 matched samples. Start hours are those covering most samples: 94 % of 24 h samples begin at 00 and the remainder at 23; 90 % of 8 h samples begin at 04, 12 or 20, the rest spread over nine other hours, chiefly at Rocky Flats, which changed schedule in mid-2025.",
      header: ["", "24 h", "8 h", "3 h"],
      widths: [3400, 1875, 1875, 1876],
      rows: [
        ["Sites (states)", "102 (30)", "40 (29)", "4 (2)"],
        ["Samples", "8730", "6972", "681"],
        ["Principal window start hours (LST)", "00", "04, 12, 20", "05, 08, 12, 16, 23 (CA); 06 (CO)"],
        ["Samples with a usable scan", "6106 (70 %)", "3509 (50 %)", "402 (59 %)"],
        ["Median usable scans per sample", "11", "6", "2"],
        ["Pearson r", "0.42", "0.33", "0.46"],
        ["Spearman ρ", "0.48", "0.38", "0.42"],
        ["Day-to-day r (n)", "0.40 (5218)", "0.38 (3509)", "0.39 (383)"],
        ["Column coefficient (µg m^{-3} per 10^{15} molecules cm^{-2})", "0.163 ± 0.006", "0.193 ± 0.008", "0.229 ± 0.028"],
        ["Median surface HCHO (µg m^{-3})", "2.46", "4.18", "3.93"],
        ["Median column (10^{15} molecules cm^{-2})", "5.50", "10.31", "8.78"],
        ["Median H_{eff} / median TEMPO PBL height (km)", "1.09 / 1.04", "1.27 / 1.12", "1.05 / 1.05"],
        ["Median day-to-day r by site (IQR)", "0.48 (0.27-0.59)", "0.47 (0.26-0.57)", "0.31 (0.05-0.42)"]
      ]
    }},

    { h2: "Day-to-Day Skill Is Highly Site Dependent", p: [
      "Agreement is positive at most individual monitors but far from uniform (Figure 1), and it is the distribution rather than any count of significant sites that carries the result. At the 97 sites with enough 24 h samples the median correlation was 0.64 (interquartile range 0.45-0.72) and the median day-to-day correlation 0.48 (0.27-0.59), ranging from 0.89 at Medford, Oregon, 0.85 at Fresno and 0.79 at Stockton, California, to values indistinguishable from zero at a dozen sites and -0.24 at St. Charles Mesa, Colorado. The 40 sites sampling 8 h blocks behaved similarly (median day-to-day correlation 0.47).",

      "Two comparisons make the pooled numbers interpretable. First, the pooled correlation of 0.42 is well below the median correlation computed within individual sites (0.64), so pooling across the country dilutes rather than inflates: TEMPO tracks variation at a given monitor considerably better than it tracks the differences between monitors, whose column-to-surface ratios differ with climate, mixing depth and free-tropospheric background. Second, pooling adds almost nothing over the day-to-day correlation nationally (0.42 against 0.40), whereas in the Colorado case study it adds a great deal (0.56 against 0.30), because seven monitors in one state share a single regional seasonal cycle that a pooled statistic rewards. The day-to-day correlation is therefore the quantity to compare between networks, and by that measure Colorado sits below the national norm: its six 24 h AQS sites have a median day-to-day correlation of 0.35 against the national 0.48, below Iowa (0.59), Michigan (0.59), Pennsylvania (0.54) and California (0.40) and above New York (0.33). A single-region evaluation could not have known which of these it was seeing, and the same caution applies to any satellite evaluation carried out in one area.",

      "This heterogeneity is the central practical result. TEMPO carries usable day-to-day information at most routine air toxics monitors and none at some, and there is no network-wide satellite-to-surface relationship that can safely be assumed at a monitor that has not been checked. A programme considering satellite data as a supplement can estimate what to expect at its own sites from Figure 1 rather than from a network average."
    ]},

    { fig: { file: "fig13_national_site_map.png",
      caption: "Figure 1. Day-to-day agreement (within-month anomaly correlation) between TEMPO HCHO columns and surface HCHO at each site, by sample duration, for scans inside the sampling window. Colour shows the correlation and symbol size the number of matched samples. Sites with fewer than 10 matched samples are not shown." }},

    { h2: "What Limits Agreement: Retrieval Noise and Spatial Averaging", p: [
      "Agreement improves consistently with spatial averaging. Pooled over the national 24 h sites the correlation rises from 0.39 for single cells to 0.42 for 3 × 3 blocks and 0.43 for 5 × 5 blocks, and a stricter cloud threshold of 0.1 helps slightly (0.44 at 3 × 3) at the cost of 9 % of the samples. On its own that gradient is equally consistent with averaging down noise and with larger blocks being more representative of what a monitor sees.",

      "The Colorado case study separates the two, because repeated scans within a day allow the retrieval noise itself to be estimated. Successive valid scans of the same site and day differ by an amount equivalent to a single-scan noise of about 4 × 10^{15} molecules cm^{-2} for one grid cell, falling to 1.2 × 10^{15} molecules cm^{-2} for a daily mean of a 3 × 3 block. That is 48 % of the variance of the within-month column anomalies, so noise alone would cap the day-to-day correlation at about 0.72, well above the observed 0.30. Because the column genuinely changes between successive scans, this is an upper bound on random scan-to-scan noise and correspondingly a lower bound on the ceiling; it is also blind to errors that persist through a day. Dividing the observed correlation by the cap gives noise-corrected values of 0.40, 0.41 and 0.47 at 1 × 1, 3 × 3 and 5 × 5 blocks. The block-size gradient is therefore greatly attenuated once the estimated noise is accounted for, which indicates that much of the improvement with averaging reflects reduced retrieval noise rather than improved spatial representativeness, although the residual rise at 5 × 5 leaves room for a smaller representativeness gain. The national distribution corroborates this across a much wider range of conditions: grouping the 24 h sites into thirds by median surface concentration, the median day-to-day correlation is 0.34 in the lowest third (0.6-2.0 µg m^{-3}), 0.58 in the middle third and 0.46 in the highest, which is what a fixed retrieval noise predicts, since it consumes the largest share of the variance where the signal is small.",

      "Noise does not explain the differences between monitors. In Colorado, La Salle and Cañon City lie close to their noise ceilings (noise-corrected correlations 0.85 and 0.91), Commerce City is intermediate (0.67) and Grand Junction is far below (0.28). Terrain inside the averaging block does not account for it: the spread of TEMPO surface pressure across the 3 × 3 block is smallest at Commerce City and largest at Cañon City, the opposite of what the site correlations would require. Where agreement stays far below the noise ceiling, spatial representativeness, vertical structure, retrieval biases that persist through a day, or error in the surface measurement are all candidates, and this diagnostic cannot separate them. Taken at face value the per-cell uncertainties reported in the product are larger still and would leave no room for the correlations we observe, so they appear to overstate the random error of the scans they flag as most uncertain.",

      "For comparisons with 24 h integrated samples, averaging over roughly 10 km and over all daylight scans is a reasonable default; Rawat et al. reach a compatible conclusion from the opposite direction, finding that a 10 km collocation radius reproduces results earlier evaluations obtained with 20-40 km{{rawat2026}}. Near strong local sources, larger blocks dilute local enhancements, so the appropriate scale depends on whether the application targets regional or near-source concentrations."
    ]},

    { h2: "Days TEMPO Can Use Are Not Representative", p: [
      "Whether agreement survives a stricter cloud threshold is a different question from whether the days that survive screening resemble the days that do not. Nationally the 8730 24 h samples divide into 6106 observable (69.9 %), 2253 screened out (25.8 %) and 371 with no granule (4.2 %); in Colorado, 338 of 453 were observable (74.6 %), 100 screened out (22.1 %) and 15 had no granule (3.3 %).",

      "Screening is not a cloud filter alone. Re-evaluating each screened-out sample day with one criterion relaxed at a time, the effective cloud fraction threshold on its own would have made at least one scan usable for 1551 of the 2253 nationally (69 %) and 64 of the 100 in Colorado (64 %). Snow or ice cover would have rescued 394 and 18, the solar zenith angle limit 189 and 4, and the main data quality flag 8 and none; 311 and 18 would not have been rescued by relaxing any single criterion. These counts are not mutually exclusive, because different scans within one sampling period can fail different criteria. About a third of the rejections therefore survive removal of the cloud threshold alone, so the contrast is between sampling days with a usable observation and sampling days for which TEMPO returned granules but no scan passed — an observability contrast, not a comparison of clear with cloudy days.",

      "Observable days carry more surface HCHO (Figure 2). With fixed effects for monitor and calendar month, a day with a usable observation has 0.52 µg m^{-3} more surface HCHO than a screened-out day at the same monitor in the same month (95 % confidence interval 0.43 to 0.61, standard errors clustered by monitor; n = 8359 at 102 monitors), which is 25 % of the national median of the days compared. Taking deviations within each site-month instead, and bootstrapping over monitors, gives 0.51 µg m^{-3} (0.42 to 0.60; 955 site-months at 100 monitors). The Colorado case study gives the same sign and a smaller magnitude, 0.39 µg m^{-3} by regression and 0.36 µg m^{-3} (0.14 to 0.49) by the site-month estimate; with only seven monitor clusters the reference distribution of the cluster-robust statistic is poorly approximated, so we place no weight on its nominal significance there. The difference grows through the warm season: nationally the paired difference is 0.16 µg m^{-3} in winter (10 % of the seasonal median; 0.01 to 0.31), 0.47 in spring (26 %; 0.33 to 0.60), 1.00 in summer (34 %; 0.83 to 1.19) and 0.63 in autumn (30 %; 0.46 to 0.80).",

      "The direction is the opposite of the corresponding result for nitrogen dioxide. Goldberg et al. found surface NO_{2} higher on cloudy than on clear days at most AQS monitors and interpreted this partly in terms of slower photochemical loss{{goldberg2025}}. For HCHO, higher concentrations on observable days are consistent with greater net production under sunnier and generally warmer conditions, particularly in summer. Cloudiness also covaries with temperature, biogenic emissions, transport and boundary layer structure, however, and screening removes days for reasons unrelated to cloud at all, so this comparison identifies an observability-related selection effect rather than the process responsible for it. The practical consequence is direct: a surface-HCHO mean calculated only for TEMPO-observable days would exceed the corresponding mean over days for which TEMPO returned granules, so combining satellite observations with the monitor's own record on days with no usable retrieval, whether screened out or never observed, is necessary if the target is a long-term mean rather than one conditioned on observability."
    ]},

    { fig: { file: "fig14_observability_bias.png",
      caption: "Figure 2. Surface HCHO on days with a usable TEMPO observation and on days for which TEMPO returned granules but no scan passed the full screening criteria, as deviations from the site and calendar-month mean, for site-months containing at least one day of each kind. Days for which TEMPO returned no granule are excluded. Diamonds are means; the adjusted paired difference and its site-cluster bootstrap interval are given above each panel; axes are truncated near the 1st and 99th percentiles." }},

    { h2: "The Hour of Sampling Matters, but No Single Lag Is Best", p: [
      "Sub-daily samples allow the satellite to be matched to the hours a sample actually covers. Two cautions apply. Pooling a lag curve across sites that sample different windows mixes shifts that mean quite different things — a -3 h shift is the middle of the night for a 05:00 sample and mid-morning for a 12:00 sample — so pooled curves are reported in the Supporting Information (Figure S4) rather than here. And an 8 h window shifted by 3 h still overlaps the original by five hours, so lag curves for the 8 h sites are expected to be flat, and they are (0.31, 0.38, 0.35 and 0.32 at lags of -3, 0, +3 and +6 h). The informative cut is the hour at which sampling begins (Figure 3).",

      "Grouped that way, the pattern is not the one the Colorado case study alone would suggest. At the two California sites sampling 3 h blocks, the window beginning at 05:00 LST tracks the surface as well as any: the day-to-day correlation is 0.44 (n = 99) for scans inside the sampling window, essentially the same as the 0.41 of the midday window beginning at 12:00 (n = 100), while the late-afternoon window beginning at 16:00 shows no significant agreement (0.17, n = 91, p = 0.11). The Colorado window beginning at 06:00 MST is the outlier: 0.11 (n = 79, p = 0.35). The case study, which assembles its samples independently of the national extraction and extends Platteville back to August 2023, resolves that outlier into two sites that behave differently. At Chatfield State Park the sampling window carries no day-to-day information at all (r = 0.01, n = 46) while the window three hours later carries a good deal (0.48, n = 63); at Platteville neither window carries significant day-to-day information (0.25 and 0.16). Restricted to the samples usable in both windows, the gain from waiting three hours is 0.55 at Chatfield (Williams' test p = 0.011) and 0.07 at Platteville (p = 0.73); pooled over the two sites it is 0.27, which is not significant (p = 0.057). The pooled figure averages two monitors 60 km apart that do not agree with each other, which is the point rather than a limitation. Across the 40 sites sampling 8 h blocks the same ordering appears more coarsely: the block beginning at 12:00 LST gives a day-to-day correlation of 0.42 (n = 1754) and the block beginning at 04:00, which straddles the morning transition, 0.34 (n = 1698). Because every 8 h site samples the same three blocks, that comparison holds the schedule fixed and varies only the time of day.",

      "Morning sampling is therefore not intrinsically hard to match to a satellite column. An obvious alternative explanation is that early-morning retrievals are less informative about the surface: Nawaz et al. found the weakest TEMPO NO_{2} agreement in the early morning, with R^{2} of 0.23 at 06:00 and 0.35 at 07:00 local time, attributing it to reduced sensitivity to near-surface pollution when the light path is long{{nawaz2025}}. The same mechanism would apply to HCHO. Three observations argue that it is not the whole explanation here. The California sites begin sampling an hour earlier still, at solar zenith angles no more favourable, and their morning window works. At the Colorado 24 h sites, where the sample covers every window, early scans carry as much day-to-day information as later ones (within-month anomaly correlations 0.40 for 06:00-09:00 and 0.35 for 09:00-12:00 on the 184 site-days with valid scans in both, p = 0.58). And the two regions are at broadly comparable latitudes. Retrieval sensitivity that varies regionally — with cloud, aerosol, surface albedo and profile shape as well as geometry — may still contribute; the two explanations are not exclusive.",

      "A boundary layer explanation is consistent with these observations, and we offer it as a hypothesis rather than a demonstrated mechanism. As the morning mixed layer deepens, a surface concentration becomes representative of a larger fraction of the column, so the two measurements should agree more closely once mixing has developed. In the Colorado 3 h record the median TEMPO boundary layer height rises from 0.47 km during sampling to 1.50 km three hours later, while the inferred H_{eff} barely changes (0.99 and 0.95 km) — a pattern consistent with a change in vertical distribution without a corresponding change in the total column. The contrasts within our data are ordered as that reading would predict: Chatfield State Park, at the foot of the Front Range where nocturnal drainage and a strongly stable morning layer are expected, has an essentially zero sampling-window correlation and a strong +3 h window, whereas Platteville on the open plains of the Denver-Julesburg basin, where morning decoupling should be weaker, gains nothing from the later window. Four sites is a thin basis for a mechanism, and the two Californian ones are 80 km apart in a single air basin. Co-located boundary layer measurements, or a lag analysis stratified by a stability index, would be needed to test it properly.",

      "The practical implication is neither \"match the satellite to the sampling window\" nor \"add three hours\", but that the best match has to be determined rather than assumed. For 24 h samples the all-day mean is a reasonable compromise. For programmes designing sub-daily carbonyl sampling, a window centred on the middle of the day is the more robust default, although the optimal window remains site dependent. Whatever the choice, the metadata matter: without the sample start times recorded in AQS we would have had the Colorado sampling window backwards, and would have reported the best-fitting window as the sampling window."
    ]},

    { fig: { file: "fig12_national_by_start_hour.png",
      caption: "Figure 3. Correlation between sub-daily surface HCHO and the mean TEMPO column, grouped by the local standard hour at which the sampling window begins, using only scans inside the sampling window. \"Whole\" uses the concentrations as measured; \"anomalies\" uses deviations from site and calendar-month means. In the 3 h panel, the windows beginning at 05:00, 12:00 and 16:00 are the two California sites and the window beginning at 06:00 is the two Colorado sites; in the 8 h panel each point pools all 40 sites. Labels give the number of matched samples." }},

    { h2: "The Colorado Case Study", p: [
      "Colorado designated formaldehyde one of five priority toxic air contaminants in January 2025{{cdphetac2026}}, and its network spans an urban-industrial corridor north of Denver, oil-and-gas-producing and agricultural areas on the northern Front Range, southern Front Range cities and a valley city on the Western Slope. Beyond the two diagnostics above, three case-study results are worth recording. First, the two data pathways agree: at the three sites with two-year records, day-to-day correlations computed from the state's data packets and from the same samples retrieved through AQS differ by at most 0.02, which validates both the packet parsing and the AQS unit conversion. Second, the seasonal amplitude of the column exceeds that of the surface concentration, 3.0-fold against 1.7-fold from winter to summer, and the median H_{eff} of 0.83 km is about half the median TEMPO boundary layer height of 1.55 km, whereas nationally the two are close. Illustrative corrections for the known low bias of TEMPO HCHO against ground-based columns{{ortega2026}}{{rawat2026}} give a Colorado median H_{eff} of about 0.85 km under the network-wide low-column estimate and 1.3-1.5 km under Boulder-specific estimates. These are sensitivity scenarios rather than uncertainty bounds — the estimates come from different comparisons, a single factor cannot strictly be applied to a median pooling sites and seasons, and neither assessment characterises version 4 — but they show that plausible corrections could span much of the difference from the modelled boundary layer depth, which is why H_{eff} is treated as a diagnostic here. Third, wildfire smoke identified by the NOAA Hazard Mapping System{{rolph2009}}{{brey2018}} raised both surface HCHO and the column within season, and removing smoke days weakened day-to-day agreement from 0.30 to 0.23; in the 3 h arm smoke-affected windows correlated more strongly than smoke-free ones (0.55 against 0.37) in the post-sampling window, consistent with HCHO emitted by fires and produced within ageing plumes{{liao2021}}. Fire-related enhancements can also remain aloft and appear in the column without a proportionate surface signal{{goldberg2025}}, so this is episode classification rather than vertical or source attribution. Full case-study results are in the Supporting Information (Figures S5-S14 and Tables S4 and S5)."
    ]},

    { h2: "Implications and Limitations", p: [
      "TEMPO provides useful seasonal and episodic context for air toxics monitoring across the United States, and it updates the only previous surface-satellite HCHO comparison over the country: Wang et al. matched seasonal means at 45 AQS sites to OMI columns and found agreement in summer but not winter{{wang2022}}, and our seasonal findings reproduce theirs — but the comparison no longer has to be seasonal, because 70 % of individual 24 h samples now carry a usable observation. The value of the column for tracking day-to-day variation is greatest when observations are averaged spatially, when the monitor's concentrations are not close to the retrieval noise floor, and when the satellite is matched to the periods of the day in which surface-column correspondence is strongest. Which of those conditions hold, and which matching window is best, are now questions that can be answered monitor by monitor rather than assumed from a network average. Pairing satellite observations with time-resolved surface samples, recording sampling start and end times, and preferring midday sampling windows where the science allows would all make better use of hourly retrievals.",

      "Several limitations apply. The record spans two years. The sub-daily arm rests on 40 sites with one 8 h sampling pattern and four sites with 3 h samples, two of them the Colorado pair, so the evidence that morning sampling can work rests on two Californian sites in one air basin. Sample duration and time of day are confounded across the network, because each duration is associated with a different set of sites and programmes; we therefore compare windows only among samples of the same duration. Twenty-three sites report both 24 h and 8 h formaldehyde, so a within-site comparison of duration is possible in principle and would be the natural way to separate the two. Integrated DNPH samples are subject to artefacts and calibration uncertainty; the negative interference from ozone{{arnts1989}} would lower surface concentrations and raise H_{eff}, so it does not explain low values, and calibration differences among HCHO techniques can be substantial{{jeong2026}}. The lags examinable were limited by the solar zenith angle screen, and the 20:00 LST block of the 8 h sites is dark. National effective mixing heights assume a fixed air temperature of 15 °C. TEMPO V04 HCHO is provisional; scans were assigned to sampling periods by granule midpoint; and the boundary layer height is a model product. Wildfire smoke is classified only in the Colorado case study, and Hazard Mapping System classification is qualitative and column based{{brey2018}}. Finally, anomaly p-values are optimistic because they do not account for the degrees of freedom spent on the site-month means, so the distribution of the correlations should carry more weight than any count of significant sites."
    ]},

    { h1: "Associated Content", p: [
      "Supporting Information. The Supporting Information is available free of charge at [URL]. Colorado case-study site descriptions, quality-control handling and detailed methods; retrieval-noise estimator; smoke classification; Figures S1-S14 and Tables S1-S5 (PDF)."
    ]},

    { h1: "Code and Data Availability", p: [
      "The R code used for data retrieval, processing, statistics and figures is available at https://github.com/pdez90/coatts_hcho [[archive a release on Zenodo and cite its DOI]]. CDPHE formaldehyde data packets are available from the CDPHE Air Toxics and Ozone Precursor Data Repository. National formaldehyde samples, sample times and monitor metadata come from EPA's Air Quality System. TEMPO Level 3 V04 HCHO data are available from the NASA Langley Atmospheric Science Data Center (https://doi.org/10.5067/IS-40e/TEMPO/HCHO_L3.004). NOAA Hazard Mapping System smoke polygons are available from NOAA OSPO. [[Decide whether to deposit the matched datasets with a DOI.]]"
    ]},

    { h1: "Author Information", p: [
      "[[Corresponding author, ORCID identifiers, author contributions and competing financial interest statement to be completed.]]"
    ]},

    { h1: "Acknowledgments", p: [
      "We thank the CDPHE Air Pollution Control Division Air Toxics and Ozone Precursors programme for collecting and publishing the monitoring data and for answering our questions about it [[names, with permission]], the TEMPO science team and NASA Atmospheric Science Data Center for the TEMPO products, and NOAA Hazard Mapping System analysts for the smoke analyses. [[Funding to be completed.]]"
    ]}
  ],

  notes: [
    "This is the ES&T version, condensed from the AMT-length draft (v19). Main text held to the ES&T Research Article limits: 7000 words, a 150-200 word abstract, four display items, Introduction / Materials and Methods / Results and Discussion with no separate Conclusions section. Everything else is in the Supporting Information.",
    "Citations are numbered by order of appearance by build_est.js from {{key}} markers; the reference list is emitted in that order. Do not renumber by hand.",
    "Still to settle before submission: author list, affiliations, ORCIDs, corresponding author, author contributions, competing financial interest statement and funding; the TOC/abstract graphic; a Zenodo release and DOI for the code; whether to deposit the matched datasets; and the reference details still highlighted below.",
    "Outstanding with CDPHE: what COOPs stands for, and how to cite their answers to our questions (Supporting text S1).",
    "Time-sensitive: re-run the literature search behind the novelty claim in the Introduction in the week of submission. The watch item is an August 2025 TEMPO science team presentation by Rawat on using remotely sensed HCHO columns to assess surface air quality.",
    "Yellow-highlighted text marks statements to verify or decisions to make."
  ],

  // ---------------------------------------------------------------- references
  // key -> full citation. build_est.js numbers them by first appearance in the
  // main text, then continues through the Supporting Information.
  refs: {
    zhu2017: "Zhu, L.; Jacob, D. J.; Keutsch, F. N.; Mickley, L. J.; Scheffe, R.; Strum, M.; González Abad, G.; Chance, K.; Yang, K.; Rappenglück, B.; Millet, D. B.; Baasandorj, M.; Jaeglé, L.; Shah, V. Formaldehyde (HCHO) as a hazardous air pollutant: mapping surface air concentrations from satellite and inferring cancer risks in the United States. Environ. Sci. Technol. 2017, 51, 5650-5657. https://doi.org/10.1021/acs.est.7b01356",
    parrish2012: "Parrish, D. D.; Ryerson, T. B.; Mellqvist, J.; Johansson, J.; Fried, A.; Richter, D.; Walega, J. G.; Washenfelder, R. A.; de Gouw, J. A.; Peischl, J.; Aikin, K. C.; McKeen, S. A.; Frost, G. J.; Fehsenfeld, F. C.; Herndon, S. C. Primary and secondary sources of formaldehyde in urban atmospheres: Houston Texas region. Atmos. Chem. Phys. 2012, 12, 3273-3288. https://doi.org/10.5194/acp-12-3273-2012",
    liu2026: "Liu, S.; Jaffe, D. A. Surface atmospheric formaldehyde trends in the U.S. driven by temperature-dependent biogenic precursor emissions and influenced by wildfires. ACS ES&T Air 2026, 3, 1167-1175. https://doi.org/10.1021/acsestair.6c00010",
    liao2021: "Liao, J.; Wolfe, G. M.; Hannun, R. A.; St. Clair, J. M.; Hanisco, T. F.; Gilman, J. B.; Lamplugh, A.; Selimovic, V.; Diskin, G. S.; Nowak, J. B.; Halliday, H. S.; DiGangi, J. P.; Hall, S. R.; Ullmann, K.; Holmes, C. D.; Fite, C. H.; Agastra, A.; Ryerson, T. B.; Peischl, J.; et al. Formaldehyde evolution in US wildfire plumes during the Fire Influence on Regional to Global Environments and Air Quality experiment (FIREX-AQ). Atmos. Chem. Phys. 2021, 21, 18319-18331. https://doi.org/10.5194/acp-21-18319-2021",
    zoogman2017: "Zoogman, P.; Liu, X.; Suleiman, R. M.; et al. Tropospheric emissions: Monitoring of pollution (TEMPO). J. Quant. Spectrosc. Radiat. Transfer 2017, 186, 17-39. https://doi.org/10.1016/j.jqsrt.2016.05.008 [[complete author list]]",
    jin2025: "Jin, X.; Yang, Y.; González Abad, G.; Nowlan, C.; Liu, X. Observing the diurnal variations of ozone-NO_{x}-VOC chemistry over the U.S. from the geostationary TEMPO instrument. Geophys. Res. Lett. 2025, 52, e2025GL116394. https://doi.org/10.1029/2025GL116394",
    zhu2020: "Zhu, L.; González Abad, G.; Nowlan, C. R.; Chan Miller, C.; Chance, K.; Apel, E. C.; DiGangi, J. P.; Fried, A.; Hanisco, T. F.; Hornbrook, R. S.; Hu, L.; Kaiser, J.; Keutsch, F. N.; Permar, W.; St. Clair, J. M.; Wolfe, G. M. Validation of satellite formaldehyde (HCHO) retrievals using observations from 12 aircraft campaigns. Atmos. Chem. Phys. 2020, 20, 12329-12345. https://doi.org/10.5194/acp-20-12329-2020",
    rawat2026: "Rawat, P.; Travis, K. R.; Henderson, B.; Crawford, J. H.; Judd, L. M.; Demetillo, M. A. G.; Lee, T. C.; Flittner, D. E.; Szykman, J. J.; Valin, L. C.; Whitehill, A.; Baumann, E.; Hanisco, T. F.; Pandey, A.; González Abad, G.; Nowlan, C. R.; Liu, X.; Chance, K. Spatiotemporal assessment of the TEMPO formaldehyde column retrieval using the Pandonia Global Network. J. Geophys. Res. Atmos. 2026, 131, e2025JD044788. https://doi.org/10.1029/2025JD044788",
    ortega2026: "Ortega, I.; Hannigan, J. W.; Edwards, D.; Stremme, W.; Grutter, M.; Cadena-Caicedo, A.; Strong, K.; Flood, V.; Zhao, X.; González Abad, G.; Nowlan, C. R. Evaluating TEMPO formaldehyde retrievals with co-located ground-based FTIR and Pandora observations. J. Geophys. Res. Atmos. 2026, 131, e2026JD046497. https://doi.org/10.1029/2026JD046497",
    wang2022: "Wang, P.; Holloway, T.; Bindl, M.; Harkey, M.; De Smedt, I. Ambient formaldehyde over the United States from ground-based (AQS) and satellite (OMI) observations. Remote Sens. 2022, 14, 2191. https://doi.org/10.3390/rs14092191",
    acker2025: "Acker, S.; Holloway, T.; Harkey, M. Satellite detection of NO_{2} distributions using TROPOMI and TEMPO and comparison with ground-based concentration measurements. Atmos. Chem. Phys. 2025, 25, 8271-8288. https://doi.org/10.5194/acp-25-8271-2025",
    nawaz2025: "Nawaz, M. O.; Huber, D. E.; Kerr, G. H.; Judd, L. M.; Acker, S. J.; Goldberg, D. L. A comparative analysis of TEMPO NO_{2} remote sensing with surface-level monitoring through diurnal and seasonal trends, meteorology, and monitor characteristics. J. Geophys. Res. Atmos. 2025, 130, e2025JD043923. https://doi.org/10.1029/2025JD043923",
    nasaval2026: "NASA Atmospheric Science Data Center. Validation and quality assessment of the TEMPO Level-2 trace gas products; NASA Langley Atmospheric Science Data Center, 2026. https://asdc.larc.nasa.gov/documents/tempo/TEMPO_validation_report_baseline_draft.pdf [[confirm the current version and its formal citation before submission]]",
    epaaqs2026: "U.S. Environmental Protection Agency. Air Quality System (AQS) API and pre-generated data files; U.S. EPA, 2026. https://aqs.epa.gov/aqsweb/documents/data_api.html",
    epato11a1999: "U.S. Environmental Protection Agency. Compendium Method TO-11A: Determination of formaldehyde in ambient air using adsorbent cartridge followed by high performance liquid chromatography (HPLC). In Compendium of Methods for the Determination of Toxic Organic Compounds in Ambient Air, 2nd ed.; EPA/625/R-96/010b; U.S. EPA: Cincinnati, OH, 1999.",
    tempol3v4: "NASA/LARC/SD/ASDC. TEMPO gridded formaldehyde total column V04 (PROVISIONAL); NASA Langley Atmospheric Science Data Center DAAC, 2025. https://doi.org/10.5067/IS-40e/TEMPO/HCHO_L3.004 [[check citation on DOI landing page]]",
    nasaguide2025: "NASA Atmospheric Science Data Center. TEMPO Level 2/3 trace gas and cloud products user guide, version 2.1; NASA Langley Atmospheric Science Data Center, 2025. https://asdc.larc.nasa.gov/documents/tempo/guide/TEMPO_Level-2-3_trace_gas_clouds_user_guide_V2.1.pdf [[check authors and year]]",
    steiger1980: "Steiger, J. H. Tests for comparing elements of a correlation matrix. Psychol. Bull. 1980, 87, 245-251. https://doi.org/10.1037/0033-2909.87.2.245",
    rcore2024: "R Core Team. R: A language and environment for statistical computing; R Foundation for Statistical Computing: Vienna, Austria, 2024. https://www.R-project.org/",
    goldberg2025: "Goldberg, D. L.; Nawaz, M. O.; Lyu, C.; He, J.; Carlton, A. G.; Kondragunta, S.; Anenberg, S. C. NO_{2} concentration differences under clear versus cloudy skies and implications for applications of satellite measurements. EGUsphere, preprint, 2025. https://doi.org/10.5194/egusphere-2025-1350 [[check whether the peer-reviewed version has appeared before submission]]",
    cdphetac2026: "Colorado Department of Public Health and Environment. Priority toxic air contaminants; CDPHE, 2026. https://cdphe.colorado.gov/air-toxics/priority-toxic-air-contaminants",
    rolph2009: "Rolph, G. D.; Draxler, R. R.; Stein, A. F.; Taylor, A.; Ruminski, M. G.; Kondragunta, S.; Zeng, J.; Huang, H.-C.; Manikin, G.; McQueen, J. T.; Davidson, P. M. Description and verification of the NOAA Smoke Forecasting System: the 2007 fire season. Weather Forecast. 2009, 24, 361-378. https://doi.org/10.1175/2008WAF2222165.1",
    brey2018: "Brey, S. J.; Ruminski, M.; Atwood, S. A.; Fischer, E. V. Connecting smoke plumes to sources using Hazard Mapping System (HMS) smoke and fire location data over North America. Atmos. Chem. Phys. 2018, 18, 1745-1761. https://doi.org/10.5194/acp-18-1745-2018",
    arnts1989: "Arnts, R. R.; Tejada, S. B. 2,4-Dinitrophenylhydrazine-coated silica gel cartridge method for determination of formaldehyde in air: identification of an ozone interference. Environ. Sci. Technol. 1989, 23, 1428-1430. https://doi.org/10.1021/es00069a018",
    jeong2026: "Jeong, D.; Hornbrook, R. S.; Hills, A. J.; Diskin, G.; Halliday, H. S.; DiGangi, J. P.; Fried, A.; Richter, D.; Walega, J.; Weibring, P.; Hanisco, T. F.; Wolfe, G. M.; St. Clair, J.; Peischl, J.; Wisthaler, A.; et al. Trace Organic Gas Analyzer Time-of-Flight mass spectrometer (TOGA-TOF) system for airborne observations of formaldehyde. Atmos. Meas. Tech. 2026, 19, 2985-3000. https://doi.org/10.5194/amt-19-2985-2026",
    cdpherepo2026: "Colorado Department of Public Health and Environment. Air Toxics and Ozone Precursor Data Repository; CDPHE, 2026. https://www.colorado.gov/airquality/air_toxics_repo.aspx",
    bates2015: "Bates, D.; Mächler, M.; Bolker, B.; Walker, S. Fitting linear mixed-effects models using lme4. J. Stat. Softw. 2015, 67, 1-48. https://doi.org/10.18637/jss.v067.i01",
    pebesma2018: "Pebesma, E. Simple features for R: standardized support for spatial vector data. R J. 2018, 10, 439-446. https://doi.org/10.32614/RJ-2018-009",
    hollister2025: "Hollister, J. W. elevatr: access elevation data from various APIs, R package version 0.99.0, 2025. https://CRAN.R-project.org/package=elevatr [[confirm the version used and whether a Zenodo DOI should be cited instead]]",
    census2023: "U.S. Census Bureau. Cartographic boundary files; U.S. Census Bureau, 2023. https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.html",
    aws: "Amazon Web Services. Terrain Tiles, Registry of Open Data on AWS. https://registry.opendata.aws/terrain-tiles/",
    noaahms2026: "NOAA Office of Satellite and Product Operations. Hazard Mapping System smoke polygons; NOAA OSPO, 2026. https://satepsanone.nesdis.noaa.gov/pub/FIRE/web/HMS/Smoke_Polygons/Shapefile/",
    epanatts2025: "U.S. Environmental Protection Agency. National Air Toxics Trends Stations (NATTS) and the ambient air monitoring networks; U.S. EPA, 2025. https://www.epa.gov/amtic/national-air-toxics-trends-stations-natts [[check title and citation form]]"
  }
};
