// content_est.js - ES&T version, condensed from content_v19.js (AMT length).
//
// ES&T Research Article constraints applied here:
//   * 7000-word limit -> main text held near 5500 body words (v19 was 13174)
//   * abstract 150-200 words (v19 was 461)
//   * four display items in the main text; everything else in the SI
//   * Introduction / Materials and Methods / Results and Discussion, with NO
//     separate Conclusions section ("any concluding statements are to be
//     incorporated under Results and Discussion")
//   * numbered citations in order of appearance -> written here as {{key}}
//     markers and numbered by build_est.js, so the order is never hand-kept
//
// Every statistic is carried over unchanged from content_v19.js; check_est.js
// verifies that, so condensation cannot silently alter a number.
//
// Regenerated 2026-09-22 from the edited Word manuscript, so that this file and
// the document agree again. Prose, headings and captions come from the document;
// refs, figure files, table data and the drafting notes are carried over.
module.exports = {
  "title": "Hourly Satellite Formaldehyde Columns and Routine Surface Air Toxics Monitoring: Day-to-Day Agreement at 123 United States Sites",
  "authors": [
    "[[Author list, affiliations and corresponding author to be completed.]]"
  ],
  "tocNote": "[[TOC/abstract graphic not yet built. Run Rscript R/16_toc_graphic.R, which writes output/figures/toc_graphic.tiff (300 dpi, 3.25 x 1.75 in, for submission) and toc_graphic.png (embedded here on the next build).]]",
  "keywords": [
    "formaldehyde",
    "TEMPO",
    "satellite validation",
    "air toxics monitoring",
    "hazardous air pollutants",
    "geostationary remote sensing"
  ],
  "abstract": [
    "Formaldehyde (HCHO) is a carcinogenic hazardous air pollutant and a leading contributor to estimated cancer risk from U.S. outdoor air toxics. The geostationary Tropospheric Emissions: Monitoring of Pollution (TEMPO) instrument retrieves HCHO columns hourly over North America, but published TEMPO HCHO evaluations have compared them only with other column measurements. We compared TEMPO Level 3 version 4 HCHO columns with 16,383 valid integrated formaldehyde samples reported to the Air Quality System by 123 monitors in 36 states and Washington, DC, over 24, 8, and 3 h. A sample was observable when at least one TEMPO scan during its sampling window passed screening; 70 % of 24 h samples were observable. The pooled correlation with surface HCHO was 0.42 and 0.40 for within-month anomalies. This pooled result obscured substantial site-to-site variation: day-to-day correlations at individual 24 h monitors ranged from −0.24 to {{n:site_dd_max_24}} (median {{n:site_dd_median_24}}), with only {{n:pct_between_states}} % of the variance among monitors attributable to differences between states. Observable days were also unrepresentative, with surface HCHO 0.52 µg/m³ (25 %) higher than on days when all available scans were screened out. For 3 h samples, the temporal match differed across sites. At one site, the correlation increased from −0.01 during the 06:00–09:00 sampling period to 0.48 in the following three hours; another showed little agreement in either window, while the two California sites showed agreement during their morning sampling window."
  ],
  "sections": [
    {
      "h1": "1 Introduction",
      "p": [
        "Formaldehyde (HCHO) is one of the largest contributors to estimated cancer risk from outdoor air toxics in the United States.{{zhu2017}} Unlike most air toxics, ambient HCHO is predominantly secondary, produced by the oxidation of biogenic and anthropogenic volatile organic compounds (VOCs), with smaller primary contributions from combustion and industrial sources. For example, research has shown that downwind of Houston-area petrochemical facilities, secondary production accounted for 92 ± 4 % of HCHO compared with 4 ± 2 % from primary emissions.{{parrish2012}} Surface HCHO trends across the United States track temperature-dependent biogenic precursor emissions and are influenced by wildfires.{{liu2026}} Studies have shown HCHO is produced within aging wildfire plumes{{liao2021}}.",
        "HCHO has characteristic absorption features in the ultraviolet. By measuring the attenuation of backscattered sunlight at these wavelengths, satellite spectrometers can retrieve the vertically integrated abundance of HCHO in the atmosphere. Because HCHO has a short atmospheric lifetime of only a few hours, the observed column is typically dominated by recent, nearby production within the boundary layer and therefore contains information about surface concentrations. Satellite-derived HCHO has consequently been used to map surface concentrations and infer cancer risks across the United States,{{zhu2017}} although converting a column measurement to a surface concentration necessarily requires assumptions about the vertical distribution of HCHO.",
        "TEMPO, launched into geostationary orbit in 2023, measures HCHO hourly during daylight over North America at a spatial resolution of a few kilometres.{{zoogman2017}} Because HCHO is produced largely through VOC oxidation, its abundance responds to the same processes that shape ozone-NOx-VOC photochemistry over the course of the day, including changes in sunlight-driven production and loss, precursor emissions, and boundary-layer mixing. Hourly TEMPO observations can thus track the diurnal evolution of HCHO and its underlying photochemical environment.{{jin2025}}",
        "Evaluation of satellite HCHO has relied on aircraft profiles and ground-based column instruments. Aircraft comparisons found the Ozone Monitoring Instrument (OMI) HCHO product biased low by 22-45 % under polluted conditions and high at low columns{{zhu2020}}. For TEMPO, comparisons with the Pandonia Global Network characterised the retrieval's spatiotemporal performance{{rawat2026}}, and comparisons with Fourier transform infrared (FTIR) and Pandora spectrometers found a low bias of about 30%, while diurnal and seasonal variability were captured.{{ortega2026}} The TEMPO validation team’s baseline assessment collects these and other comparisons for the version 3 trace gas products.{{nasaval2026}}",
        "Comparisons with routine surface HCHO measurements remain rare, in part because the monitoring network is sparse and relies largely on intermittently collected integrated samples. Wang et al. compared OMI columns from 2006-2015 with seasonal mean surface HCHO at 45 sites reporting to the Air Quality System (AQS), EPA’s repository for ambient monitoring data. They found regional correlations of 0.56-0.87 in summer, weak or negative correlations in winter, and seasonal variability that was 20-100% larger in the satellite column than at the surface.{{wang2022}} The analysis used seasonal rather than monthly averages to preserve geographic coverage: only 37 sites had at least one measurement in every month, whereas requiring six surface samples per season retained 45 sites. In contrast, regulatory NO₂ networks are dense and report concentrations hourly, allowing TROPOMI and TEMPO columns to be matched directly with routine surface measurements at daily and sub-daily resolution.{{acker2025}}{{nawaz2025}}",
        "TEMPO’s hourly geostationary sampling provides multiple HCHO observations within a single surface-sampling day, allowing satellite columns to be matched to the actual hours covered by 24, 8, and 3 h integrated samples rather than to a single overpass. This makes it possible to evaluate satellite-surface agreement at the level of individual sampling periods and to test whether that agreement depends on time of day.",
        "Here we compare TEMPO Level 3 version 4 HCHO columns with surface HCHO measured in 2024-2025 at 123 U.S. monitors reporting to AQS across 36 states and the District of Columbia, including National Air Toxics Trends Stations, NCore multipollutant sites, and Photochemical Assessment Monitoring Stations. Because these routine networks were designed for long-term air toxics monitoring rather than satellite validation, we ask how often a usable TEMPO observation is available for a surface sample, how well TEMPO tracks day-to-day variation in surface HCHO at individual monitors, how that agreement varies among sites, and whether days with usable retrievals are representative of days that are screened out.",
        "TEMPO’s repeated observations also allow us to examine what contributes to variation in satellite–surface agreement. First, we estimate retrieval noise from differences between consecutive scans, reasoning that the atmospheric HCHO column changes relatively little over approximately one hour. We then use this estimate to determine how strongly retrieval noise constrains the maximum correlation TEMPO could achieve with surface HCHO. Second, we test whether agreement depends on the hours used for the satellite comparison. Two Colorado monitors provide the cleanest test of temporal matching because they are the only 3 h sites that consistently sample a single fixed early-morning window, from 06:00 to 09:00. This allows us to hold the surface measurement period constant while comparing TEMPO columns observed during sampling with those observed in the non-overlapping three hours that follow. The other sub-daily monitors sample at several times of day and are used to examine how satellite–surface agreement varies with sampling time more broadly."
      ]
    },
    {
      "h1": "2 Data and Methods",
      "p": []
    },
    {
      "h2": "2.1 Surface measurements.",
      "p": [
        "HCHO is measured across the United States by state, local, and tribal agencies and reported to EPA’s Air Quality System (AQS) under parameter code 43502.{{epaaqs2026}} Nearly all measurements in this study use EPA Compendium Method TO-11A,{{epato11a1999}} in which air is collected on a 2,4-dinitrophenylhydrazine-coated cartridge and the resulting derivative is quantified by high-performance liquid chromatography. Of the samples analyzed here, 76% were collected with a potassium-iodide ozone scrubber, 16% with a bare silica cartridge, and 8% downstream of a heated ozone denuder.",
        "For the national analysis we used EPA's AQS annual summary files to identify sites in the contiguous United States whose monitors together reported at least 20 formaldehyde samples at a single sample duration over calendar years 2024 and 2025. We then retrieved every sample-level record for those sites, keeping all durations reported at a qualifying site; this retains one 10-sample 24 h record at a site that qualified on its {{n:pct_method_denuder}} h record. Six sites fell short of 20 samples at every duration and were excluded, removing 48 samples. Records carrying an AQS null data qualifier were then removed, and where more than one record (instrument or method) at a site covered the same sampling window their values were averaged; because the threshold was applied to the annual-summary counts, it was not re-applied after this screening. The final dataset contains {{n:pct_method_bare}},383 valid samples from 123 sites in 36 states and the District of Columbia, spanning 1 January 2024 to 31 December 2025. AQS reports HCHO in parts per billion carbon, which for this one-carbon molecule is numerically equivalent to parts per billion by volume; we converted concentrations to mass units at 25 °C and 1 atm.",
        "Samples were collected over 24, 8, or 3 h, and 23 sites reported both a 24 h and an 8 h record, so the site counts by duration overlap. The 24 h record comprised 8,730 samples at 102 sites; 97 % began at midnight local standard time and the remaining 273 at 23:00 LST, all of them during daylight saving time- that is, at local midnight by the clock- at four Philadelphia monitors and once in Florida. Most were collected on a one-in-six or one-in-twelve day schedule. The 8 h record comprised 6,972 samples at 40 sites; 99 % began at 04:00, 12:00, or 20:00 LST, the remaining 55 falling on alternative eight-hour grids used briefly at five sites. The 3 h record comprised 681 samples at four sites: two Colorado ozone-precursor monitors sampled exclusively from 06:00 to 09:00 MST, whereas two sites in California's San Joaquin Valley sampled several times a day, principally beginning at 05:00, 12:00, 16:00 and 23:00 LST, with 14 samples beginning at 08:00.",
        "We use the Colorado monitors for two additional analyses because they provide information not available consistently across the national network. Seven Colorado air-toxics monitors provide 24 h samples, and the two ozone-precursor monitors provide 3 h samples. Wheat Ridge, which has only 15 samples, falls below the inclusion threshold for the national comparison but is retained in the Colorado-specific analysis. For the 24 h sites, annual Colorado Department of Public Health and Environment data packets also report a sampling temperature and pressure that AQS does not publish, for 118 of the 326 matched days used to estimate effective mixing height (H_{eff}). We use them only as an independent check on the model meteorology described below, which is applied identically at every monitor in this study; they do not enter the calculation of H_{eff} itself. The two Colorado 3 h sites also provide a fixed 06:00-09:00 sampling window, enabling a direct comparison of TEMPO columns measured during sampling with those measured in subsequent hours. One of these sites, Platteville, reported HCHO to AQS beginning in August 2023, the first month with TEMPO observations, so its Colorado-specific record is extended back to that date; the national comparison begins in 2024, and the second Colorado 3 h site has no 2023 HCHO record. Site descriptions, quality-control procedures, and a map are provided in the Supporting Information (Figure S1, Table S1)."
      ]
    },
    {
      "h2": "TEMPO columns and matching",
      "p": [
        "We used the provisional TEMPO Level 3 version 4 HCHO product,{{tempol3v4}} which maps retrievals from each TEMPO scan onto a 0.02° × 0.02° grid, approximately 2.2 km × 1.7 km at 39.5° N. Each scan is distributed by NASA as a separate data file, or granule. We identified the files covering each monitoring site and sampling period through NASA’s Common Metadata Repository and downloaded a 5 × 5 block of grid cells surrounding each site through NASA’s OPeNDAP service. We initially downloaded these cells without quality screening so that screening criteria and spatial averaging windows could be varied after extraction.",
        "We retained a grid cell when the main data quality flag was 0, effective cloud fraction was ≤0.2, solar zenith angle was ≤70°, and snow and ice fraction was zero. Following the product user guide,{{nasaguide2025}} we retained negative HCHO columns. For the primary analysis, we averaged the screened cells within the central 3 × 3 block, approximately 6.7 km × 5.1 km, to obtain one HCHO column for each scan. A scan was considered valid when at least five of the nine cells passed the screening criteria.",
        "AQS records each sample’s start time in local standard time, the corresponding GMT, and its duration, allowing every sampling window to be defined directly in UTC without assumptions about time zone. We assigned a TEMPO scan to a sampling window when the hour containing the scan midpoint fell within that window. Because TEMPO observes locations sequentially during each scan, the midpoint timestamp can differ from the actual observation time at an individual site by tens of minutes.",
        "The surface sample and the TEMPO column may not represent the same vertical distribution of HCHO, particularly in the early morning when the boundary layer is shallow or decoupled. As mixing develops, the surface concentration may become more representative of a larger fraction of the atmospheric column. We therefore repeated the sub-daily comparisons after shifting the TEMPO window by −3 and +3 h. These shifts correspond to the additional three hours retrieved on either side of each sampling window in the national extraction. For the Colorado 3 h sites, the wider 03:00–19:00 MST extraction also allowed comparisons at +6 and +9 h. The −3 h window for these sites, 03:00–06:00 MST, occurs before usable daylight observations and therefore produced no scans passing the solar zenith angle screen. We did not apply lagged comparisons to 24 h samples because shifting a 24 h window by 3 h leaves 21 of its 24 hours unchanged, making the comparison largely uninformative.",
        "We tested sensitivity to effective cloud-fraction thresholds of 0.1, 0.2, and 0.3 and to spatial averages based on 1 × 1, 3 × 3, and 5 × 5 grid-cell blocks in all analyses (Figures S2-S3). At the Colorado 24 h sites, we additionally compared columns averaged over all usable daytime scans with those restricted to midday (section S8)."
      ]
    },
    {
      "h2": "Statistics",
      "p": [
        "We report Pearson (r) and Spearman (ρ) correlations by site, by season and pooled. Because surface HCHO and the column share a strong seasonal cycle, we also computed within-month anomalies by subtracting each site's mean for that month of that year from both variables, retaining site-months with at least three matched samples; correlations of these anomalies measure day-to-day covariation and are the quantity we rely on. For 8 h and 3 h samples a site-month pools the windows a site samples, so the anomaly also carries the systematic difference between windows; the comparison by start hour in the Results removes that difference by construction, and anomalies stratified by window as well are reported in the Supporting Information (S4). Because the site-month means are estimated from the same observations that then enter the correlation, the ordinary correlation test is anti-conservative, so anomaly correlations are tested by permuting one variable within site × month strata (2000 permutations; Supporting Information, Text S4), and site-level multiplicity is summarised with a Benjamini-Hochberg correction across the family (Table S2). Every anomaly p-value quoted here is a permutation value, except those of Williams' tests, which are parametric; the distribution of the correlations carries more weight than any count of significant sites. The pooled regression of surface concentration on the column uses ordinary least squares with fixed effects for site and calendar month. Reduced major axis slopes, mixed-effects models, Williams' test for dependent correlations{{steiger1980}} and the retrieval-noise estimator are described in the Supporting Information; the noise estimator and the time-of-day comparison are applied at every 24 h site.",
        "Effective mixing height. To relate column to surface we converted the surface mass concentration to a number density n_{s} and defined an effective mixing height H_{eff} = Ω/n_{s}, where Ω is the TEMPO column: the depth of a uniform layer at the surface concentration that would contain the observed column. H_{eff} combines the vertical distribution of HCHO, biases in the retrieval and in the surface measurement, and the mismatch between sampling period and daytime satellite sampling, so we use it as a diagnostic and not as a physical boundary layer depth. Because AQS reports at standard conditions (25 °C, 1 atm), we converted to a mixing ratio, χ = C × 24.45/M with M = 30.026 g mol^{-1}, and then to a number density at the conditions of the air, n_{s} = 10^{-15} χ p/(k_{B}T), with p in Pa and T in K; the factor 10^{-15} combines the definition of a part per billion (10^{-9}) with the conversion from molecules m^{-3} to molecules cm^{-3} (10^{-6}). Temperature and pressure come from the NOAA High-Resolution Rapid Refresh (HRRR) analysis, a 3 km hourly assimilating model{{dowell2022}}, averaged over the hours each sample spans; the same field is used at every monitor and in every arm. A single fixed temperature is not adequate here, because H_{eff} is proportional to T and HRRR spans {{n:hrrr_temp_min}} to +{{n:hrrr_temp_max}} °C over the site-hours sampled: a fixed 15 °C, used in earlier versions of this analysis, understates H_{eff} by about 7 % on a 35 °C day, overstates it by about 12 % at -15 °C, and compresses its seasonal contrast by roughly 19 percentage points. HRRR agrees closely with the surface pressure supplied with the TEMPO retrieval (median difference -0.6 hPa, r = 0.9995, n = 10,465). It does not agree with the pressure recorded in the CDPHE packets, which is 57 hPa lower on average (r = 0.56) while the packets' temperature tracks HRRR to +0.5 °C (r = 0.94); we therefore read the packet pressure as a measurement made within the sampling train rather than ambient barometric pressure, and do not use it (Figure S4, Table S3).",
        "Observability of sample days. A sample day is observable when at least one scan passes screening; it is screened out when TEMPO returned granules covering the site but no scan passed; and it has no granule when TEMPO returned none. No-granule days are excluded from the observability comparisons, so that gaps in TEMPO's own sampling are not counted as screening. To establish what drives the rejections we re-evaluated every screened-out sample day with one screening criterion relaxed at a time. These relaxation counts are not mutually exclusive: a sampling period usually contains several scans, and different scans within it can fail different criteria. Two estimates of the difference in surface HCHO between observable and screened-out days are reported, both signed observable minus screened out. The first is the coefficient β in HCHO_{it} = α_{i} + γ_{m} + β·observable_{it} + ε_{it}, with fixed effects for monitor i and calendar month m and standard errors cluster-robust by monitor. The second takes deviations from each site-month mean, averages them within site-months to a single paired difference, and averages across site-months, with a confidence interval from a bootstrap resampling monitors (2000 replicates); no interval is reported for a stratum with fewer than five monitors, where such a bootstrap is degenerate rather than merely wide.",
        "All processing was done in R{{rcore2024}}; a single script downloads every input and produces all tables and figures (see Supporting Information and Code Availability)."
      ]
    },
    {
      "h1": "Results and Discussion",
      "p": []
    },
    {
      "h2": "Availability and Pooled Agreement",
      "p": [
        "A screened TEMPO observation was available for 70 % of the 8730 national 24 h samples, with a median of {{n:scans_usable_median_24}} usable scans per sample. Coverage varied widely between sites, from around 90 % in Arizona, southern California and on the Texas Gulf coast to below 50 % in Oregon, Vermont, upstate New York and Seattle, with the lowest values at Tualatin (37 %) and Portland-Helensview (39 %), Oregon, and Proctor Maple Research Center, Vermont (40 %). That availability primarily reflects the repeated sampling a geostationary orbit allows rather than any property of the retrieval: at a Pandonia site in New Jersey, hourly sampling yields a usable observation on about 50 % more days than an early-afternoon overpass alone would{{rawat2026}}, and modelled cloud fields imply that 68-93 % of days contain a clear-sky opportunity at some daylight hour against 33-69 % at a fixed early-afternoon overpass{{goldberg2025}}.",
        "Pooled across the 24 h sites, the daily mean column and the 24 h surface concentration correlated at r = 0.42 (ρ = 0.48, n = 6106), and after removing site-month means the day-to-day correlation was 0.40 (n = 5218 in 1262 site-months). The regression of surface concentration on the column, with fixed effects for site and calendar month, gave 0.163 ± 0.006 µg m^{-3} per 10^{15} molecules cm^{-2}. Table 1 summarises the comparison by sample duration. Median H_{eff} over the matched 24 h samples with a positive column was 1.10 km against a median TEMPO planetary boundary layer height of 1.04 km; the agreement of the two medians is not by itself evidence of a well-mixed profile, since H_{eff} also absorbs retrieval bias, the free-tropospheric column and the mismatch between a 24 h sample and daytime satellite sampling."
      ]
    },
    {
      "table": {
        "caption": "Table 1. The national comparison by sample duration. Sites and samples are those reported to AQS for 2024-2025; matched counts and correlations use the primary screening (effective cloud fraction ≤ 0.2, 3 × 3 cell block) with scans inside the sampling window. Anomaly correlations use deviations from site-month means (each month of each year). Usable scans are those passing the screen, over samples with at least one. Median anomaly r by site is computed over sites with at least 10 matched samples. Start hours are those covering most samples: 97 % of 24 h samples begin at 00 and the remainder at 23; 99 % of 8 h samples begin at 04, 12 or 20, the rest spread over ten other start times, mostly at Rocky Flats, Colorado, which changed schedule in mid-2025, and Livermore, California. ^{a} Deviations from site-month means; for 8 h and 3 h samples these pool a site's sampling windows and so include the difference between windows (Supporting Information S4 gives the window-stratified values).",
        "header": [
          "",
          "24 h",
          "8 h",
          "3 h"
        ],
        "widths": [
          3400,
          1875,
          1875,
          1876
        ],
        "rows": [
          [
            "Sites (states)",
            "102 (29 + DC)",
            "40 (28 + DC)",
            "4 (2)"
          ],
          [
            "Samples",
            "8730",
            "6972",
            "681"
          ],
          [
            "Principal window start hours (LST)",
            "00",
            "04, 12, 20",
            "05, 12, 16, 23 (CA); 06 (CO)"
          ],
          [
            "Samples with a usable scan",
            "6106 (70 %)",
            "3509 (50 %)",
            "402 (59 %)"
          ],
          [
            "Median usable scans per sample",
            "{{n:scans_usable_median_24}}",
            "{{n:scans_usable_median_8}}",
            "{{n:scans_usable_median_3}}"
          ],
          [
            "Pearson r",
            "0.42",
            "0.33",
            "0.46"
          ],
          [
            "Spearman ρ",
            "0.48",
            "0.38",
            "0.42"
          ],
          [
            "Within-month anomaly r (n)^{a}",
            "0.40 (5218)",
            "0.38 (3509)",
            "0.39 (383)"
          ],
          [
            "Column coefficient (µg m^{-3} per 10^{15} molecules cm^{-2})",
            "0.163 ± 0.006",
            "0.193 ± 0.008",
            "0.229 ± 0.028"
          ],
          [
            "Median surface HCHO (µg m^{-3})",
            "2.46",
            "4.18",
            "3.93"
          ],
          [
            "Median column (10^{15} molecules cm^{-2})",
            "5.50",
            "10.31",
            "8.78"
          ],
          [
            "Median H_{eff} / median TEMPO PBL height (km)",
            "1.10 / 1.04",
            "1.32 / 1.12",
            "1.08 / 1.05"
          ],
          [
            "Median anomaly r by site (IQR)^{a}",
            "{{n:site_dd_median_24}} ({{n:site_dd_q25_24}}-{{n:site_dd_q75_24}})",
            "{{n:site_dd_median_8}} ({{n:site_dd_q25_8}}-{{n:site_dd_q75_8}})",
            "{{n:site_dd_median_3}} ({{n:site_dd_q25_3}}-{{n:site_dd_q75_3}})"
          ]
        ]
      }
    },
    {
      "h2": "Day-to-Day Skill Is Highly Site Dependent",
      "p": [
        "Agreement is positive at most individual monitors but far from uniform (Figure 1), and it is the distribution rather than any count of significant sites that carries the result. At the {{n:n_sites_24}} sites with enough 24 h samples the median correlation was {{n:site_r_median_24}} (interquartile range {{n:site_r_q25_24}}-{{n:site_r_q75_24}}) and the median day-to-day correlation {{n:site_dd_median_24}} ({{n:site_dd_q25_24}}-{{n:site_dd_q75_24}}), ranging from {{n:site_dd_max_24}} at Medford, Oregon (on only 8 anomaly pairs), 0.85 at Fresno and 0.79 at Stockton, California, to values within 0.1 of zero at seven sites and {{n:site_dd_min_24}} at St. Charles Mesa, Colorado (the Pueblo monitor of Table S1). The {{n:n_sites_8}} sites sampling 8 h blocks behaved similarly (median within-month anomaly correlation {{n:site_dd_median_8}}, pooling each site's blocks).",
        "The pooled correlation of 0.42 is well below the median correlation computed within individual sites (0.64), so pooling across the country dilutes rather than inflates: TEMPO tracks variation at a given monitor considerably better than it tracks the differences between monitors, whose column-to-surface ratios differ with climate, mixing depth and free-tropospheric background. How much pooling adds over the day-to-day correlation depends on how much regional structure it spans, and that is measurable rather than a matter of argument. Nationally it adds almost nothing (0.42 against 0.40). Across the {{n:n_multi_site_states}} states with at least four 24 h monitors the gain has a median of {{n:pooling_gain_median}} and ranges from {{n:pooling_gain_min}} to {{n:pooling_gain_max}}: in three states pooling lowers the correlation rather than raising it, and the largest gain anywhere is Colorado's (0.57 against 0.32). An evaluation carried out in one state could not have known where in that range it was sitting, and the same caution applies to any satellite evaluation carried out in one area.",
        "This heterogeneity is the central practical result, and it is local rather than regional. Across those {{n:n_multi_site_states}} states only {{n:pct_between_states}} % of the variance in site-level day-to-day agreement lies between states; the remaining {{n:pct_within_states}} % is between monitors within the same state (Figure 3). How much a state's monitors agree with one another is itself uneven: Iowa's five span 0.58 to 0.68, while Oregon's six, from -0.21 to 0.89, span almost the entire range observed nationally. TEMPO carries usable day-to-day information at most routine air toxics monitors and none at some, and there is no network-wide satellite-to-surface relationship that can safely be assumed at a monitor that has not been checked. A programme considering satellite data as a supplement can estimate what to expect at its own sites from Figures 1 and 3 rather than from a network average."
      ]
    },
    {
      "fig": {
        "file": "fig13_national_site_map.png",
        "caption": "Figure 1. Day-to-day agreement (within-month anomaly correlation) between TEMPO HCHO columns and surface HCHO at each site, by sample duration, for scans inside the sampling window. Colour shows the correlation and symbol size the number of matched samples. Sites with fewer than 10 matched samples are not shown."
      }
    },
    {
      "h2": "What Limits Agreement: Retrieval Noise and Spatial Averaging",
      "p": [
        "Agreement improves consistently with spatial averaging. Pooled over the national 24 h sites the Pearson correlation rises from 0.39 for single cells to 0.42 for 3 × 3 blocks and 0.43 for 5 × 5 blocks, and a stricter cloud threshold of 0.1 helps slightly (0.44 at 3 × 3) at the cost of 9 % of the samples. On its own that gradient is equally consistent with averaging down noise and with larger blocks being more representative of what a monitor sees.",
        "Repeated scans within a day separate the two, because they allow the retrieval noise itself to be estimated, and the estimate can be made at every 24 h site. Successive valid scans of the same site and day, no more than 1.6 h apart, differ by an amount equivalent to a single-scan noise of {{n:nat_noise_single_1x1_1e15}} × 10^{15} molecules cm^{-2} for one grid cell, falling to {{n:nat_noise_daily_3x3_1e15}} × 10^{15} molecules cm^{-2} for the within-month anomaly of the daily 3 × 3 mean. Pooled over the 24 h sites that is {{n:nat_noise_share_3x3_pct}} % of the variance of the within-month column anomalies, so noise alone would cap the day-to-day correlation at about {{n:nat_ceiling_3x3}}, against the observed {{n:nat_anom_obs_3x3}}. Because the column genuinely changes between successive scans, this is an upper bound on random scan-to-scan noise and correspondingly a lower bound on the ceiling; it is also blind to errors that persist through a day. The day-to-day correlation shows the same gradient as the whole-period one above, {{n:nat_anom_obs_1x1}}, {{n:nat_anom_obs_3x3}} and {{n:nat_anom_obs_5x5}} for 1 × 1, 3 × 3 and 5 × 5 blocks; dividing each by the ceiling at that block size gives noise-corrected values of {{n:nat_r_corr_1x1}}, {{n:nat_r_corr_3x3}} and {{n:nat_r_corr_5x5}}: the gradient disappears once the estimated noise is accounted for, so the improvement with averaging reflects reduced retrieval noise rather than improved spatial representativeness. The dependence on concentration points the same way: grouping the 24 h sites into thirds by median surface concentration, the median day-to-day correlation is {{n:tert_low_r}} in the lowest third ({{n:tert_low_lo}}-{{n:tert_low_hi}} µg m^{-3}), {{n:tert_mid_r}} in the middle third and {{n:tert_high_r}} in the highest. A fixed retrieval noise predicts the rise out of the lowest third, since it consumes the largest share of the variance where the signal is small; that the highest third falls back rather than rising further shows that other factors, near-source heterogeneity among the most polluted monitors being one candidate, also operate.",
        "Wildfire smoke, identified from NOAA Hazard Mapping System polygons overlapping each sampling window{{rolph2009}}{{brey2018}}, improves agreement rather than degrading it. Of the {{n:smoke_n_flagged}} matched samples carrying a smoke classification, {{n:smoke_n_affected}} were smoke-affected. At the 24 h sites the correlation with surface HCHO rose from {{n:smoke_r_24_none}} on smoke-free days to {{n:smoke_r_24_light}} under light smoke and {{n:smoke_r_24_heavy}} under medium or heavy smoke; at the 8 h sites it rose from {{n:smoke_r_8_none}} to {{n:smoke_r_8_light}} and {{n:smoke_r_8_heavy}} (Table S5, Figure S11). Excluding smoke days lowers the national day-to-day correlation from {{n:smoke_dd_24_all}} to {{n:smoke_dd_24_nosmoke}} at 24 h and from {{n:smoke_dd_8_all}} to {{n:smoke_dd_8_nosmoke}} at 8 h. Classification uses sampling windows widened by 3 h (Supporting Information S6), which flags 38 % of national windows against 30 % under strict overlap. The most economical reading is the mechanism above: smoke roughly doubles the median column, from {{n:smoke_col_24_none}} to {{n:smoke_col_24_light}} × 10^{15} molecules cm^{-2} at the 24 h sites, while surface HCHO rises proportionately less, so a fixed retrieval noise is a smaller share of the signal and the correlation moves toward its ceiling. On that reading smoke is a third expression of the concentration dependence rather than a separate effect; we have not tested it directly, and the seven Colorado monitors show the opposite whole-period sign on far fewer smoke days (Supporting Information S8). The 3 h record is too thin to test, with {{n:smoke_n_3_none}}, {{n:smoke_n_3_light}} and {{n:smoke_n_3_heavy}} samples in the three classes, and is not interpreted.",
        "Noise does not explain the differences between monitors. At the {{n:nat_sites_scored}} 24 h sites with enough successive-scan pairs and anomaly pairs for a ceiling to be defined (at {{n:nat_sites_ceiling_undefined}} more the noise bound exceeded the anomaly variance), the ceiling is high and fairly uniform, a median of {{n:nat_site_ceiling_median}} (interquartile range {{n:nat_site_ceiling_q25}} to {{n:nat_site_ceiling_q75}}), while the observed correlations spread from {{n:nat_site_obs_min}} to {{n:nat_site_obs_max}} (Figure S7). Dividing each site's correlation by its own ceiling gives a median noise-corrected value of {{n:nat_site_rcorr_median}} ({{n:nat_site_rcorr_q25}} to {{n:nat_site_rcorr_q75}}): {{n:nat_sites_near_ceiling}} sites sit within 20 % of their ceiling and {{n:nat_sites_far_below}} below half of it. Where agreement stays far below the ceiling, spatial representativeness, vertical structure, retrieval biases that persist through a day, or error in the surface measurement are all candidates, and this diagnostic cannot separate them; at the Colorado sites, where we indexed terrain within the block by the spread of TEMPO surface pressure, that spread does not order the sites (Supporting Information S8). Taken at face value the per-cell uncertainties reported in the product are larger still and, where we evaluated them (Supporting Information S5), would leave little or no room for the correlations we observe, so they appear to overstate the random error of the scans they flag as most uncertain.",
        "For comparisons with 24 h integrated samples, averaging over roughly 10 km and over all daylight scans is a reasonable default; Rawat et al. reach a compatible conclusion from the opposite direction, finding that a 10 km collocation radius reproduces results earlier evaluations obtained with 20-40 km{{rawat2026}}. Near strong local sources, larger blocks dilute local enhancements, so the appropriate scale depends on whether the application targets regional or near-source concentrations."
      ]
    },
    {
      "h2": "Days TEMPO Can Use Are Not Representative",
      "p": [
        "Whether agreement survives a stricter cloud threshold is a different question from whether the days that survive screening resemble the days that do not. Nationally the 8730 24 h samples divide into 6106 observable (69.9 %), 2253 screened out (25.8 %) and 371 with no granule (4.2 %).",
        "Screening is not a cloud filter alone. Re-evaluating each screened-out sample day with one criterion relaxed at a time, the effective cloud fraction threshold on its own would have made at least one scan usable for 1547 of the 2253 (69 %). Snow or ice cover would have rescued 394, the solar zenith angle limit 189 and the main data quality flag 8; 312 would not have been rescued by relaxing any single criterion. These counts are not mutually exclusive, because different scans within one sampling period can fail different criteria. About a third of the rejections therefore survive removal of the cloud threshold alone, so the contrast is between sampling days with a usable observation and sampling days for which TEMPO returned granules but no scan passed — an observability contrast, not a comparison of clear with cloudy days.",
        "Observable days carry more surface HCHO (Figure 2). With fixed effects for monitor and calendar month, a day with a usable observation has 0.52 µg m^{-3} more surface HCHO than a screened-out day at the same monitor in the same month (95 % confidence interval 0.43 to 0.61, standard errors clustered by monitor; n = 8359 at 102 monitors), which is 25 % of the national median of the days compared. Taking deviations within each site-month instead, and bootstrapping over monitors, gives 0.51 µg m^{-3} (0.42 to 0.60; 955 site-months at 100 monitors). The Colorado sites give the same sign and a smaller magnitude, 0.38 µg m^{-3} by regression and 0.36 µg m^{-3} (0.13 to 0.48) by the site-month estimate; with only seven monitor clusters the reference distribution of the cluster-robust statistic is poorly approximated, so we place no weight on its nominal significance there. The difference grows through the warm season: nationally the paired difference is 0.16 µg m^{-3} in winter (10 % of the seasonal median; 0.01 to 0.31), 0.47 in spring (25 %; 0.33 to 0.60), 1.00 in summer (34 %; 0.82 to 1.19) and 0.63 in autumn (30 %; 0.45 to 0.80).",
        "The direction is the opposite of the corresponding result for nitrogen dioxide. Goldberg et al. found surface NO_{2} higher on cloudy than on clear days at most AQS monitors and interpreted this partly in terms of slower photochemical loss{{goldberg2025}}. For HCHO, higher concentrations on observable days are consistent with greater net production under sunnier and generally warmer conditions, particularly in summer. Cloudiness also covaries with temperature, biogenic emissions, transport and boundary layer structure, however, and screening removes days for reasons unrelated to cloud at all, so this comparison identifies an observability-related selection effect rather than the process responsible for it. The practical consequence is direct: a surface-HCHO mean calculated only for TEMPO-observable days would exceed the corresponding mean over days for which TEMPO returned granules, so combining satellite observations with the monitor's own record on days with no usable retrieval, whether screened out or never observed, is necessary if the target is a long-term mean rather than one conditioned on observability."
      ]
    },
    {
      "fig": {
        "file": "fig14_observability_bias.png",
        "caption": "Figure 2. Surface HCHO on days with a usable TEMPO observation and on days for which TEMPO returned granules but no scan passed the full screening criteria, as deviations from the site-month mean, for site-months with at least three sample days containing at least one day of each kind. Days for which TEMPO returned no granule are excluded. Diamonds are means; the adjusted paired difference and its site-cluster bootstrap interval are given above each panel; axes are truncated near the 1st and 99th percentiles."
      }
    },
    {
      "h2": "The Hour of Sampling Matters, but No Single Lag Is Best",
      "p": [
        "Sub-daily samples allow the satellite to be matched to the hours a sample actually covers. Two cautions apply. Pooling a lag curve across sites that sample different windows mixes shifts that mean quite different things — a -3 h shift is the middle of the night for a 05:00 sample and mid-morning for a 12:00 sample — so pooled curves are reported in the Supporting Information (Figure S5) rather than here. And an 8 h window shifted by 3 h still overlaps the original by five hours, so lag curves for the 8 h sites are expected to be flat, and they are (0.31, 0.38 and 0.35 at lags of -3, 0 and +3 h). The informative cut is the hour at which sampling begins (Figure S12).",
        "Grouped that way, the pattern is not the one the Colorado sites alone would suggest. At the two California sites sampling 3 h blocks, the window beginning at 05:00 LST tracks the surface as well as any: the day-to-day correlation is 0.44 (n = 99) for scans inside the sampling window, essentially the same as the 0.41 of the midday window beginning at 12:00 (n = 100), while the late-afternoon window beginning at 16:00 shows no significant agreement (0.17, n = 91, p = 0.11). The Colorado window beginning at 06:00 MST is the outlier: 0.11 (n = 79, p = 0.38). The separate 3 h extraction, which assembles its samples independently of the national one and extends Platteville back to August 2023, resolves that outlier into two sites that behave differently. At Chatfield State Park the sampling window carries no day-to-day information at all (r = -0.01, n = 47) while the window three hours later carries a good deal (0.48, n = 64); at Platteville neither window carries significant day-to-day information (0.24 and 0.15). Restricted to the samples usable in both windows, the gain from waiting three hours is 0.57 at Chatfield (Williams' test p = 0.008) and 0.07 at Platteville (p = 0.71); pooled over the two sites it is 0.29 (p = 0.045). We report the pooled figure and rest nothing on it: it averages two monitors 78 km apart that do not agree with each other, which is the point rather than a limitation. Across the 40 sites sampling 8 h blocks the same ordering appears more coarsely: the block beginning at 12:00 LST gives a day-to-day correlation of 0.42 (n = 1754) and the block beginning at 04:00, which straddles the morning transition, 0.34 (n = 1698). Because every 8 h site samples the same three blocks, that comparison holds the schedule fixed and varies only the time of day.",
        "Morning sampling is therefore not intrinsically hard to match to a satellite column. An obvious alternative explanation is that early-morning retrievals are less informative about the surface: Nawaz et al. found the weakest TEMPO NO_{2} agreement in the early morning, with R{{parrish2012}} of 0.23 at 06:00 and 0.35 at 07:00 local time, attributing it to reduced sensitivity to near-surface pollution when the light path is long{{nawaz2025}}. The same mechanism would apply to HCHO. Three observations argue that it is not the whole explanation here, although the second shows it is part of it. The California sites begin sampling an hour earlier still, and their morning window tracks the surface. At the 24 h sites, where the sample covers every window, columns from 06:00-09:00 local standard time carry only slightly less day-to-day information than those from 09:00-12:00 (within-month anomaly correlations {{n:nat_tod_r_0609}} against {{n:nat_tod_r_0912}} on {{n:nat_tod_n}} site-days with valid scans in both windows, in site-months with at least three such days; Williams' test p = {{n:nat_tod_p}}); the later window is higher at {{n:nat_tod_sites_late_better}} of the {{n:nat_tod_sites}} sites with at least 20 such days, significantly so at {{n:nat_tod_sites_sig}}, and significantly lower at {{n:nat_tod_sites_sig_lower}}. A morning penalty of that size cannot produce the contrast at Chatfield, where the sampling window carries nothing and the three hours after it carry 0.48. And the two regions are at broadly comparable latitudes. Retrieval sensitivity that varies regionally — with cloud, aerosol, surface albedo and profile shape as well as geometry — may still contribute; the two explanations are not exclusive.",
        "A boundary layer explanation is consistent with these observations, and we offer it as a hypothesis rather than a demonstrated mechanism. As the morning mixed layer deepens, a surface concentration becomes representative of a larger fraction of the column, so the two measurements should agree more closely once mixing has developed. In the Colorado 3 h record the median TEMPO boundary layer height rises from 0.45 km during sampling to 1.50 km three hours later, while the inferred H_{eff} barely changes (0.98 and 0.93 km) — a pattern consistent with a change in vertical distribution without a corresponding change in the total column. The contrasts within our data are ordered as that reading would predict: Chatfield State Park, at the foot of the Front Range where nocturnal drainage and a strongly stable morning layer are expected, has an essentially zero sampling-window correlation and a strong +3 h window, whereas Platteville on the open plains of the Denver-Julesburg basin, where morning decoupling should be weaker, gains nothing from the later window. Four sites is a thin basis for a mechanism, and the two Californian ones are 178 km apart in a single air basin. Co-located boundary layer measurements, or a lag analysis stratified by a stability index, would be needed to test it properly.",
        "The practical implication is neither \"match the satellite to the sampling window\" nor \"add three hours\", but that the best match has to be determined rather than assumed. For 24 h samples the all-day mean is a reasonable compromise. For programmes designing sub-daily carbonyl sampling, a window centred on the middle of the day is the more robust default, although the optimal window remains site dependent. Whatever the choice, the metadata matter: without the sample start times recorded in AQS we would have had the Colorado sampling window backwards, and would have reported the best-fitting window as the sampling window."
      ]
    },
    {
      "fig": {
        "file": "fig15_state_heterogeneity.png",
        "caption": "Figure 3. Day-to-day agreement (within-month anomaly correlation) at each 24 h monitor, grouped by state, for the eleven states with at least four such monitors. Each point is one monitor, sized by the number of matched samples; the red bar is the state's pooled day-to-day correlation, computed over all its monitors' anomalies together. States are ordered by their median; the bar pools every monitor in the state, including any with fewer than 10 matched samples, which are not plotted. Only 14 % of the variance between monitors lies between states."
      }
    },
    {
      "h2": "Effective Mixing Height at the Colorado Sites",
      "p": [
        "The Colorado sites, whose recorded sampling temperature allows the model meteorology behind H_{eff} to be checked independently, show one further pattern worth recording. There the seasonal amplitude of the column exceeds that of the surface concentration, {{n:seasonal_amp_column}}-fold against {{n:seasonal_amp_surface}}-fold from winter to summer, and the median H_{eff} of {{n:heff_median_co}} km is about half the median TEMPO boundary layer height of {{n:heff_pbl_median_co}} km, whereas nationally the two are close. That ratio should be read with the boundary layer product's own bias in mind: at the hours TEMPO observes, it runs a median {{n:met_pbl_tempo_minus_hrrr}} m deeper than the HRRR analysis at those hours, about 18 % of the HRRR median (medians {{n:met_pbl_tempo_median}} against {{n:met_pbl_hrrr_median}} m, r = {{n:met_pbl_r}}, n = 10,465). Illustrative corrections for the known low bias of TEMPO HCHO against ground-based columns{{ortega2026}}{{rawat2026}} give a Colorado median H_{eff} of {{n:heff_corr_network}} km under the network-wide estimate for columns below 10^{16} molecules cm^{-2}, where Colorado's fall, and {{n:heff_corr_ftir}} km under the roughly 30 % low bias found against FTIR and Pandora at three sites including Boulder. These are sensitivity scenarios rather than uncertainty bounds — the estimates come from different comparisons, a single factor cannot strictly be applied to a median pooling sites and seasons, and both assessments characterise version 3 rather than the version 4 product used here — but they show that a plausible correction closes about half the difference from the modelled boundary layer depth, which is why H_{eff} is treated as a diagnostic here. Further Colorado results are in the Supporting Information (S8, Figure S6 and Table S4)."
      ]
    },
    {
      "h2": "Implications and Limitations",
      "p": [
        "TEMPO provides useful seasonal and episodic context for air toxics monitoring across the United States, and it updates the only previous surface-satellite HCHO comparison over the country: Wang et al. matched seasonal means at 45 AQS sites to OMI columns and found agreement in summer but not winter{{wang2022}}, and our seasonal findings reproduce theirs — but the comparison no longer has to be seasonal, because 70 % of individual 24 h samples now carry a usable observation. The value of the column for tracking day-to-day variation is greatest when observations are averaged spatially, when the monitor's concentrations are not close to the retrieval noise floor, and when the satellite is matched to the periods of the day in which surface-column correspondence is strongest. Which of those conditions hold, and which matching window is best, are now questions that can be answered monitor by monitor rather than assumed from a network average. Pairing satellite observations with time-resolved surface samples, recording sampling start and end times, and preferring midday sampling windows where the science allows would all make better use of hourly retrievals.",
        "Several limitations apply. The record spans two years. The sub-daily arm rests on 40 sites with one 8 h sampling pattern and four sites with 3 h samples, two of them the Colorado pair, so the evidence that morning sampling can work rests on two Californian sites in one air basin. Sample duration and time of day are confounded across the network, because each duration is associated with a different set of sites and programmes; we therefore compare windows only among samples of the same duration. Twenty-three sites report both 24 h and 8 h formaldehyde, so a within-site comparison of duration is possible in principle and would be the natural way to separate the two. Integrated DNPH samples are subject to artefacts and calibration uncertainty; the negative interference from ozone{{arnts1989}} would lower surface concentrations and raise H_{eff}, so it does not explain low values, and calibration differences among HCHO techniques can be substantial{{jeong2026}}. The lags examinable were limited by the solar zenith angle screen and, nationally, by the 3 h of extraction either side of each sampling window; the 20:00 LST block of the 8 h sites is dark. TEMPO V04 HCHO is provisional; scans were assigned to sampling periods by granule midpoint; and the boundary layer height is a GEOS-CF model product supplied with the retrieval, not an observation; at the hours TEMPO observes it runs about 18 % deeper than the HRRR analysis. Hazard Mapping System smoke classification is qualitative and column based{{brey2018}}, so a smoke flag records that a plume was overhead, not how much of it was near the ground. Finally, the permutation test holds the estimated site-month means fixed but does not address other forms of temporal dependence, so the distribution of the correlations should still carry more weight than any count of significant sites."
      ]
    },
    {
      "h1": "Associated Content",
      "p": [
        "Supporting Information. The Supporting Information is available free of charge at [URL]. Colorado site descriptions, quality-control handling and detailed methods; retrieval-noise estimator; smoke classification; Figures S1-S12 and Tables S1-S6 (PDF)."
      ]
    },
    {
      "h1": "Code and Data Availability",
      "p": [
        "The R code used for data retrieval, processing, statistics and figures is available at https://github.com/pdez90/coatts_hcho [archive a release on Zenodo and cite its DOI]. CDPHE formaldehyde data packets are available from the CDPHE Air Toxics and Ozone Precursor Data Repository. National formaldehyde samples, sample times and monitor metadata come from EPA's Air Quality System. TEMPO Level 3 V04 HCHO data are available from the NASA Langley Atmospheric Science Data Center (https://doi.org/10.5067/IS-40e/TEMPO/HCHO_L3.004). NOAA Hazard Mapping System smoke polygons are available from NOAA OSPO. [Decide whether to deposit the matched datasets with a DOI.]"
      ]
    },
    {
      "h1": "Author Information",
      "p": [
        "[Corresponding author, ORCID identifiers, author contributions and competing financial interest statement to be completed.]"
      ]
    },
    {
      "h1": "Acknowledgments",
      "p": [
        "We thank the CDPHE Air Pollution Control Division Air Toxics and Ozone Precursors programme for collecting and publishing the monitoring data and for answering our questions about it [names, with permission], the TEMPO science team and NASA Atmospheric Science Data Center for the TEMPO products, and NOAA Hazard Mapping System analysts for the smoke analyses. [Funding to be completed.]"
      ]
    }
  ],
  "notes": [
    "This is the ES&T version, condensed from the AMT-length draft (v19). Main text held to the ES&T Research Article limits: 7000 words, a 150-200 word abstract, four display items, Introduction / Materials and Methods / Results and Discussion with no separate Conclusions section. Everything else is in the Supporting Information.",
    "Citations are numbered by order of appearance by build_est.js from {{key}} markers; the reference list is emitted in that order. Do not renumber by hand.",
    "Still to settle before submission: author list, affiliations, ORCIDs, corresponding author, author contributions, competing financial interest statement and funding; the TOC/abstract graphic; a Zenodo release and DOI for the code; whether to deposit the matched datasets; and the reference details still highlighted below.",
    "Outstanding with CDPHE: what COOPs stands for, and how to cite their answers to our questions (Supporting text S1).",
    "Time-sensitive: re-run the literature search behind the novelty claim in the Introduction in the week of submission. The watch item is an August 2025 TEMPO science team presentation by Rawat on using remotely sensed HCHO columns to assess surface air quality.",
    "Yellow-highlighted text marks statements to verify or decisions to make."
  ],
  "refs": {
    "zhu2017": "Zhu, L.; Jacob, D. J.; Keutsch, F. N.; Mickley, L. J.; Scheffe, R.; Strum, M.; González Abad, G.; Chance, K.; Yang, K.; Rappenglück, B.; Millet, D. B.; Baasandorj, M.; Jaeglé, L.; Shah, V. Formaldehyde (HCHO) as a hazardous air pollutant: mapping surface air concentrations from satellite and inferring cancer risks in the United States. Environ. Sci. Technol. 2017, 51, 5650-5657. https://doi.org/10.1021/acs.est.7b01356",
    "parrish2012": "Parrish, D. D.; Ryerson, T. B.; Mellqvist, J.; Johansson, J.; Fried, A.; Richter, D.; Walega, J. G.; Washenfelder, R. A.; de Gouw, J. A.; Peischl, J.; Aikin, K. C.; McKeen, S. A.; Frost, G. J.; Fehsenfeld, F. C.; Herndon, S. C. Primary and secondary sources of formaldehyde in urban atmospheres: Houston Texas region. Atmos. Chem. Phys. 2012, 12, 3273-3288. https://doi.org/10.5194/acp-12-3273-2012",
    "liu2026": "Liu, S.; Jaffe, D. A. Surface atmospheric formaldehyde trends in the U.S. driven by temperature-dependent biogenic precursor emissions and influenced by wildfires. ACS ES&T Air 2026, 3, 1167-1175. https://doi.org/10.1021/acsestair.6c00010",
    "liao2021": "Liao, J.; Wolfe, G. M.; Hannun, R. A.; St. Clair, J. M.; Hanisco, T. F.; Gilman, J. B.; Lamplugh, A.; Selimovic, V.; Diskin, G. S.; Nowak, J. B.; Halliday, H. S.; DiGangi, J. P.; Hall, S. R.; Ullmann, K.; Holmes, C. D.; Fite, C. H.; Agastra, A.; Ryerson, T. B.; Peischl, J.; et al. Formaldehyde evolution in US wildfire plumes during the Fire Influence on Regional to Global Environments and Air Quality experiment (FIREX-AQ). Atmos. Chem. Phys. 2021, 21, 18319-18331. https://doi.org/10.5194/acp-21-18319-2021",
    "zoogman2017": "Zoogman, P.; Liu, X.; Suleiman, R. M.; Pennington, W. F.; Flittner, D. E.; Al-Saadi, J. A.; Hilton, B. B.; Nicks, D. K.; Newchurch, M. J.; Carr, J. L.; Janz, S. J.; Andraschko, M. R.; Arola, A.; Baker, B. D.; Canova, B. P.; Chan Miller, C.; Cohen, R. C.; Davis, J. E.; Dussault, M. E.; Edwards, D. P.; Fishman, J.; Ghulam, A.; González Abad, G.; Grutter, M.; Herman, J. R.; Houck, J.; Jacob, D. J.; Joiner, J.; Kerridge, B. J.; Kim, J.; Krotkov, N. A.; Lamsal, L.; Li, C.; Lindfors, A.; Martin, R. V.; McElroy, C. T.; McLinden, C.; Natraj, V.; Neil, D. O.; Nowlan, C. R.; O'Sullivan, E. J.; Palmer, P. I.; Pierce, R. B.; Pippin, M. R.; Saiz-Lopez, A.; Spurr, R. J. D.; Szykman, J. J.; Torres, O.; Veefkind, J. P.; Veihelmann, B.; Wang, H.; Wang, J.; Chance, K. Tropospheric emissions: Monitoring of pollution (TEMPO). J. Quant. Spectrosc. Radiat. Transfer 2017, 186, 17-39. https://doi.org/10.1016/j.jqsrt.2016.05.008",
    "jin2025": "Jin, X.; Yang, Y.; González Abad, G.; Nowlan, C.; Liu, X. Observing the diurnal variations of ozone-NO_{x}-VOC chemistry over the U.S. from the geostationary TEMPO instrument. Geophys. Res. Lett. 2025, 52, e2025GL116394. https://doi.org/10.1029/2025GL116394",
    "zhu2020": "Zhu, L.; González Abad, G.; Nowlan, C. R.; Chan Miller, C.; Chance, K.; Apel, E. C.; DiGangi, J. P.; Fried, A.; Hanisco, T. F.; Hornbrook, R. S.; Hu, L.; Kaiser, J.; Keutsch, F. N.; Permar, W.; St. Clair, J. M.; Wolfe, G. M. Validation of satellite formaldehyde (HCHO) retrievals using observations from 12 aircraft campaigns. Atmos. Chem. Phys. 2020, 20, 12329-12345. https://doi.org/10.5194/acp-20-12329-2020",
    "rawat2026": "Rawat, P.; Travis, K. R.; Henderson, B.; Crawford, J. H.; Judd, L. M.; Demetillo, M. A. G.; Lee, T. C.; Flittner, D. E.; Szykman, J. J.; Valin, L. C.; Whitehill, A.; Baumann, E.; Hanisco, T. F.; Pandey, A.; González Abad, G.; Nowlan, C. R.; Liu, X.; Chance, K. Spatiotemporal assessment of the TEMPO formaldehyde column retrieval using the Pandonia Global Network. J. Geophys. Res. Atmos. 2026, 131, e2025JD044788. https://doi.org/10.1029/2025JD044788",
    "ortega2026": "Ortega, I.; Hannigan, J. W.; Edwards, D.; Stremme, W.; Grutter, M.; Cadena-Caicedo, A.; Strong, K.; Flood, V.; Zhao, X.; González Abad, G.; Nowlan, C. R. Evaluating TEMPO formaldehyde retrievals with co-located ground-based FTIR and Pandora observations. J. Geophys. Res. Atmos. 2026, 131, e2026JD046497. https://doi.org/10.1029/2026JD046497",
    "wang2022": "Wang, P.; Holloway, T.; Bindl, M.; Harkey, M.; De Smedt, I. Ambient formaldehyde over the United States from ground-based (AQS) and satellite (OMI) observations. Remote Sens. 2022, 14, 2191. https://doi.org/10.3390/rs14092191",
    "acker2025": "Acker, S.; Holloway, T.; Harkey, M. Satellite detection of NO_{2} distributions using TROPOMI and TEMPO and comparison with ground-based concentration measurements. Atmos. Chem. Phys. 2025, 25, 8271-8288. https://doi.org/10.5194/acp-25-8271-2025",
    "nawaz2025": "Nawaz, M. O.; Huber, D. E.; Kerr, G. H.; Judd, L. M.; Acker, S. J.; Goldberg, D. L. A comparative analysis of TEMPO NO_{2} remote sensing with surface-level monitoring through diurnal and seasonal trends, meteorology, and monitor characteristics. J. Geophys. Res. Atmos. 2025, 130, e2025JD043923. https://doi.org/10.1029/2025JD043923",
    "dowell2022": "Dowell, D. C.; Alexander, C. R.; James, E. P.; Weygandt, S. S.; Benjamin, S. G.; Manikin, G. S.; Blake, B. T.; Brown, J. M.; Olson, J. B.; Hu, M.; Smirnova, T. G.; Ladwig, T.; Kenyon, J. S.; Ahmadov, R.; Turner, D. D.; Duda, J. D.; Alcott, T. I. The High-Resolution Rapid Refresh (HRRR): An Hourly Updating Convection-Allowing Forecast Model. Part I: Motivation and System Description. Weather Forecast. 2022, 37 (8), 1371-1395. https://doi.org/10.1175/WAF-D-21-0151.1",
    "nasaval2026": "TEMPO Validation Team and TEMPO Ad-hoc Validation Working Group. Validation and Quality Assessment of the TEMPO Level-2 Trace Gas Products, Baseline (Version 03); Smithsonian Astrophysical Observatory, 15 September 2025. https://asdc.larc.nasa.gov/documents/tempo/TEMPO_validation_report_baseline_draft.pdf",
    "epaaqs2026": "U.S. Environmental Protection Agency. Air Quality System (AQS) API and pre-generated data files; U.S. EPA, 2026. https://aqs.epa.gov/aqsweb/documents/data_api.html",
    "epato11a1999": "U.S. Environmental Protection Agency. Compendium Method TO-11A: Determination of formaldehyde in ambient air using adsorbent cartridge followed by high performance liquid chromatography (HPLC). In Compendium of Methods for the Determination of Toxic Organic Compounds in Ambient Air, 2nd ed.; EPA/625/R-96/010b; U.S. EPA: Cincinnati, OH, 1999.",
    "tempol3v4": "NASA/LARC/SD/ASDC. TEMPO gridded formaldehyde total column V04 (PROVISIONAL); NASA Langley Atmospheric Science Data Center DAAC, 2025 (provisional validation 9 December 2024). https://doi.org/10.5067/IS-40e/TEMPO/HCHO_L3.004",
    "nasaguide2025": "NASA Atmospheric Science Data Center. TEMPO Level 2/3 trace gas and cloud products user guide, version 2.1, 6 January 2026; NASA Langley Atmospheric Science Data Center, 2026. https://asdc.larc.nasa.gov/documents/tempo/guide/TEMPO_Level-2-3_trace_gas_clouds_user_guide_V2.1.pdf",
    "steiger1980": "Steiger, J. H. Tests for comparing elements of a correlation matrix. Psychol. Bull. 1980, 87, 245-251. https://doi.org/10.1037/0033-2909.87.2.245",
    "rcore2024": "R Core Team. R: A language and environment for statistical computing; R Foundation for Statistical Computing: Vienna, Austria, 2024. https://www.R-project.org/",
    "goldberg2025": "Goldberg, D. L.; Nawaz, M. O.; Lyu, C.; He, J.; Carlton, A. G.; Kondragunta, S.; Anenberg, S. C. Clear-sky and cloudy-sky differences in NO_{2} concentrations over the United States: implications for satellite measurement applications. Atmos. Chem. Phys. 2025, 25, 16287-16302. https://doi.org/10.5194/acp-25-16287-2025",
    "cdphetac2026": "Colorado Department of Public Health and Environment. Priority toxic air contaminants; CDPHE, 2026. https://cdphe.colorado.gov/air-toxics/priority-toxic-air-contaminants",
    "rolph2009": "Rolph, G. D.; Draxler, R. R.; Stein, A. F.; Taylor, A.; Ruminski, M. G.; Kondragunta, S.; Zeng, J.; Huang, H.-C.; Manikin, G.; McQueen, J. T.; Davidson, P. M. Description and verification of the NOAA Smoke Forecasting System: the 2007 fire season. Weather Forecast. 2009, 24, 361-378. https://doi.org/10.1175/2008WAF2222165.1",
    "brey2018": "Brey, S. J.; Ruminski, M.; Atwood, S. A.; Fischer, E. V. Connecting smoke plumes to sources using Hazard Mapping System (HMS) smoke and fire location data over North America. Atmos. Chem. Phys. 2018, 18, 1745-1761. https://doi.org/10.5194/acp-18-1745-2018",
    "arnts1989": "Arnts, R. R.; Tejada, S. B. 2,4-Dinitrophenylhydrazine-coated silica gel cartridge method for determination of formaldehyde in air: identification of an ozone interference. Environ. Sci. Technol. 1989, 23, 1428-1430. https://doi.org/10.1021/es00069a018",
    "jeong2026": "Jeong, D.; Hornbrook, R. S.; Hills, A. J.; Diskin, G.; Halliday, H. S.; DiGangi, J. P.; Fried, A.; Richter, D.; Walega, J.; Weibring, P.; Hanisco, T. F.; Wolfe, G. M.; St. Clair, J.; Peischl, J.; Wisthaler, A.; et al. Trace Organic Gas Analyzer Time-of-Flight mass spectrometer (TOGA-TOF) system for airborne observations of formaldehyde. Atmos. Meas. Tech. 2026, 19, 2985-3000. https://doi.org/10.5194/amt-19-2985-2026",
    "cdpherepo2026": "Colorado Department of Public Health and Environment. Air Toxics and Ozone Precursor Data Repository; CDPHE, 2026. https://www.colorado.gov/airquality/air_toxics_repo.aspx",
    "bates2015": "Bates, D.; Mächler, M.; Bolker, B.; Walker, S. Fitting linear mixed-effects models using lme4. J. Stat. Softw. 2015, 67, 1-48. https://doi.org/10.18637/jss.v067.i01",
    "pebesma2018": "Pebesma, E. Simple features for R: standardized support for spatial vector data. R J. 2018, 10, 439-446. https://doi.org/10.32614/RJ-2018-009",
    "hollister2023": "Hollister, J. W.; Shah, T.; Nowosad, J.; Robitaille, A. L.; Beck, M. W.; Johnson, M. elevatr: Access Elevation Data from Various APIs, R package version 0.99.0, 2023. https://doi.org/10.5281/zenodo.8335450",
    "census2023": "U.S. Census Bureau. Cartographic boundary files; U.S. Census Bureau, 2023. https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.html",
    "aws": "Amazon Web Services. Terrain Tiles, Registry of Open Data on AWS. https://registry.opendata.aws/terrain-tiles/",
    "noaahms2026": "NOAA Office of Satellite and Product Operations. Hazard Mapping System smoke polygons; NOAA OSPO, 2026. https://satepsanone.nesdis.noaa.gov/pub/FIRE/web/HMS/Smoke_Polygons/Shapefile/",
    "epanatts2025": "U.S. Environmental Protection Agency. Air Toxics Ambient Monitoring; Ambient Monitoring Technology Information Center, U.S. EPA, updated 1 April 2026. https://www.epa.gov/amtic/air-toxics-ambient-monitoring (accessed 20 September 2026)"
  }
};
