// mkcontent19.js - content_v18.js -> content_v19.js
//
// One correction. Sect. 3.2 printed
//     n_s = chi * 10^-9 * p/(k_B T)
// and declared n_s in molecules cm^-3. Evaluated in SI, p/(k_B T) is molecules
// m^-3, so the equation as written is short by the 10^-6 that takes m^-3 to
// cm^-3. The combined factor is 10^-15, not 10^-9.
//
// The CODE was never wrong: ppb_to_molec_cm3() in R/00_config.R computes
//     n_air <- (press_hpa * 100) / (1.380649e-23 * (temp_c + 273.15)) * 1e-6
// with the 1e-6 present and commented. Nothing computed changes; this is the
// printed equation only.
const fs = require("fs");
const path = require("path");
const C = require("./content_v18.js");
const S = C.sections;

const ix = t => {
  const i = S.findIndex(s => (s.h1 || s.h2 || "") === t);
  if (i < 0) throw new Error("no section: " + t);
  return i;
};
function sub(head, from, to) {
  const s = S[ix(head)];
  let hit = 0;
  s.p = s.p.map(t => { if (t.includes(from)) { hit++; return t.replace(from, to); } return t; });
  if (hit !== 1) throw new Error("expected 1 match in " + head + ", got " + hit + ": " + from.slice(0, 70));
}

sub("3.2 Effective mixing height",
"n_{s} = χ × 10^{-9} p/(k_{B}T), using the TEMPO surface pressure at the site",
"n_{s} = 10^{-15} χ p/(k_{B}T), with p in Pa and T in K, the factor 10^{-15} combining the definition of a part per billion (10^{-9}) with the conversion from molecules m^{-3} to molecules cm^{-3} (10^{-6}). We used the TEMPO surface pressure at the site");

C.notes[1] = "Changes from v18: the number-density equation in Sect. 3.2 is corrected as printed. It gave n_s = χ × 10^{-9} p/(k_B T) while declaring n_s in molecules cm^{-3}; evaluated in SI, p/(k_B T) is molecules m^{-3}, so the combined factor is 10^{-15}, not 10^{-9}. The units of p and T are now stated and the factor is decomposed. No computed quantity changes: ppb_to_molec_cm3() in R/00_config.R has always carried the 1e-6 that converts m^{-3} to cm^{-3}, which is why the effective mixing heights are kilometres rather than absurd (median 1.09 km nationally against a 1.04 km TEMPO PBL height), and the 15 % and 3 % sensitivities quoted in the same paragraph are ratios and so unaffected.";

const out = "// content_v19.js - generated by mkcontent19.js; do not edit by hand\n" +
  "module.exports = " + JSON.stringify(C, null, 1) + ";\n";
fs.writeFileSync(path.resolve(__dirname, "content_v19.js"), out);
console.log("wrote content_v19.js:", out.length, "chars");
