// mkcontent11.js - content_v10.js -> content_v11.js
// Final three sentence-level calibrations, plus one sibling of the same
// construction in Sect. 4.6 that the review did not name but which asserts the
// same unobserved mechanism in the Results rather than the Discussion.
const fs = require("fs");
const C = require("./content_v10.js");
const S = C.sections;

const byHead = (t) => {
  const i = S.findIndex(s => (s.h1 || s.h2 || "") === t);
  if (i < 0) throw new Error("no section: " + t);
  return i;
};
function sub(head, from, to) {
  const s = S[byHead(head)];
  let hit = 0;
  s.p = s.p.map(t => { if (t.includes(from)) { hit++; return t.replace(from, to); } return t; });
  if (!hit) throw new Error("not found in " + head + ": " + from.slice(0, 70));
}

// ---- 1. Sect. 2.3: do not assert that every 12:00-20:00 block is well mixed
sub("2.3 National formaldehyde monitors (EPA Air Quality System)",
"so that a single site samples the morning transition, the well-mixed afternoon and the night separately.",
"so that a single site samples the morning, midday–afternoon and night periods separately.");

// ---- 2. Sect. 5.3: mechanism presented as established
sub("5.3 Interpreting the column–surface relationship",
"as expected because vertical mixing redistributes HCHO without altering the column.",
"a pattern consistent with changes in vertical distribution occurring without a corresponding change in the total column.");

// ---- 2b. the same construction in the Results (Sect. 4.6), not named in review
sub("4.6 Three-hour samples: agreement depends on the lag from sampling",
"as expected if vertical mixing redistributes HCHO without changing the column.",
"a pattern consistent with a change in vertical distribution without a corresponding change in the total column.");

// ---- 3. "establish" is too strong for deliberately illustrative scenarios
sub("5.3 Interpreting the column–surface relationship",
"What the scenarios establish is that plausible corrections span most of the distance to the modelled boundary layer depth, so H_{eff} cannot be read as a physical depth — which is why we treat it as a diagnostic.",
"The scenarios show that plausible corrections could span much of the difference from the modelled boundary layer depth, so H_{eff} cannot be read as a physical depth — which is why we treat it as a diagnostic.");

// ---- notes
C.notes[1] = "Changes from v10, closing the claim-calibration pass: Sect. 2.3 no longer describes the 12:00-20:00 block as \"the well-mixed afternoon\" (we have not established that every such period is well mixed); the end of Sect. 5.3 no longer states that vertical mixing redistributes HCHO without altering the column, but describes the pattern the observations show; and \"what the scenarios establish\" becomes \"the scenarios show that plausible corrections could span\", which suits deliberately illustrative scenarios. The same mechanism-as-fact construction appeared once more in Sect. 4.6, in the Results, and is rewritten the same way. No number and no analysis changed. With these, the scientific claim-calibration pass is complete; what remains is production, metadata, the optional stability-stratified analysis flagged in Sect. 5.4, and the Grand Junction hypothesis note in Sect. 5.1.";

const out = "// content_v11.js - generated by mkcontent11.js; do not edit by hand\n" +
  "module.exports = " + JSON.stringify(C, null, 1) + ";\n";
fs.writeFileSync("content_v11.js", out);
console.log("wrote content_v11.js:", out.length, "chars");
