// mkcontent4.js - build content_v4.js from content_v3.js
// v4: national arm (EPA AQS, 123 sites) added with Colorado as the case study;
//     effective mixing heights corrected to local conditions; Sect. 5.4 rewritten
//     around the finding that the lag which matters is site dependent.
const fs = require("fs");
const C = require("./content_v3.js");

const S = C.sections;
const find = (pred) => { const i = S.findIndex(pred); if (i < 0) throw new Error("not found: " + pred); return i; };
const byHead = (t) => find(s => (s.h1 || s.h2 || "") === t);
const setP = (t, ps) => { S[byHead(t)].p = ps; };
const rename = (t, nt) => { const s = S[byHead(t)]; if (s.h2) s.h2 = nt; else s.h1 = nt; };

// ---------------------------------------------------------------- title, abstract
C.title = "TEMPO formaldehyde columns and routine surface air toxics monitoring in " +
  "the United States: day-to-day agreement at 123 sites, the timing of satellite–sample " +
  "matching, and a Colorado case study";

C.abstract = [
"Formaldehyde (HCHO) is a carcinogenic hazardous air pollutant and a leading contributor to estimated cancer risk from outdoor air toxics in the United States. The geostationary Tropospheric Emissions: Monitoring of Pollution (TEMPO) instrument retrieves HCHO columns hourly over North America, but evaluations of these retrievals have relied on column measurements, and comparisons of satellite HCHO with routine surface monitoring have been limited to seasonal means from polar-orbiting instruments. We compare TEMPO Level 3 version 4 HCHO columns with every integrated carbonyl sample reported to the United States Air Quality System (AQS) in 2024–2025 — 16 383 samples at 123 sites in 37 states, of which 102 sites sample for 24 h, 40 for 8 h and 4 for 3 h — and examine Colorado's air toxics network in detail as a case study, using the state's own data packets and a classification of every sample period by wildfire smoke.",
"Nationally, 70 % of 24 h samples had at least one TEMPO scan passing quality screening. The pooled correlation between the daily mean column and 24 h surface HCHO was 0.42 (n = 6106) and 0.40 after removing site and calendar-month means, which isolates day-to-day covariation. Agreement was significant at 122 of 141 site–duration combinations; the median day-to-day correlation at individual 24 h sites was 0.48 (interquartile range 0.27–0.59) and spanned −0.24 to 0.89. In Colorado, where the case study draws on the state packets, the pooled correlation across seven sites was 0.56 and the day-to-day correlation 0.30 — below the national median — and the two independent data pathways, state packets and AQS, gave site correlations agreeing to within 0.02 at the three sites with two-year records.",
"Agreement improved consistently with spatial averaging, from single 0.02° cells to 5 × 5 cell blocks, both nationally and in Colorado. In Colorado we show that this is almost entirely the averaging down of retrieval noise: successive scans imply that noise accounts for about half of the day-to-day variance of a 3 × 3 daily column, capping the attainable correlation near 0.7. The column's seasonal amplitude exceeded the surface amplitude (3.0-fold against 1.7-fold from winter to summer in Colorado), and the effective mixing height implied by the column-to-surface ratio was 0.83 km in Colorado, about half the modelled boundary layer depth, against 1.09 km nationally, close to it.",
"The hour at which a sample is collected mattered more than its length. At the two California sites that sample five 3 h windows a day, day-to-day agreement was as strong in the 05:00–08:00 window (r = 0.44) as at midday (0.41) and absent in the late afternoon (0.17); at Colorado's two 3 h sites, which sample only 06:00–09:00 MST, agreement was absent during the sampling window (0.11) and strongest three hours after it (0.40). Across the 40 sites sampling 8 h blocks, the midday block outperformed the morning block (0.42 against 0.34). The lag that matters is therefore site dependent rather than universal, consistent with the sampled air entering the observed column only once the morning boundary layer has deepened, at an hour that varies with local morning stability. Wildfire smoke, classified in Colorado from NOAA Hazard Mapping System analyses, raised both surface and column HCHO within season, did not reduce TEMPO coverage, and contributed to day-to-day agreement. TEMPO captures the seasonal cycle and regional episodes seen by surface air toxics monitors across the country; its day-to-day skill at an individual monitor is moderate, strongly site dependent, and governed by retrieval noise and by when the satellite looks relative to when the air was sampled."
];

C.shortSummary =
"Satellites now measure formaldehyde, a cancer-causing air pollutant, every daylight hour over North America. We compared these measurements with every routine surface sample collected across the United States in 2024-2025, at 123 sites, and looked at Colorado's network in detail. The satellite tracked day-to-day changes at most sites, but how well depended on where the monitor was and on what time of day the sample was collected: morning samples match the satellite only once the morning air has mixed upward, which happens at a different hour in different places.";

C.notes = [
"Numbers come from the pipeline runs of 11-14 September 2026, analysis code at commit 14a1257 (github.com/pdez90/coatts_hcho). Later commits change manuscript text only and no number. Re-check every number if the pipeline is rerun.",
"Changes from v3: the national arm is complete and now frames the paper (new Sects. 2.3, 3.7, 4.9, 4.10 and 5.6, Table 5 and Figs. 9-11), with Colorado as the case study; the title, abstract, introduction and conclusions were rewritten accordingly. Effective mixing heights are now computed at local temperature and pressure, having confirmed via AQS that CDPHE reports concentrations at standard conditions - every H_{eff} value in Sects. 3.2, 4.5 and 5.3 and in Tables 3 and 4 is about 15 % larger than in v3. Section 5.4 is rewritten around the finding that the lag which matters is site dependent: California's morning samples track TEMPO during the sampling window, Colorado's do not. Figures renumbered only by addition (Figs. 1-8 unchanged).",
"Still to settle with CDPHE: what COOPs stands for; the two samples stamped 23:59 on 12 June 2025 (excluded here; AQS shows no such stamps); and how to cite CDPHE's answers (personal communication?). The reporting-conditions question is now settled from AQS and needs no further reply.",
"Author list, affiliations, author contributions, acknowledgements and funding are placeholders. Consider inviting CDPHE ATOPs staff as co-authors.",
"Add Figure 1: site map of the Colorado sites (seven COATTS sites and the two COOPs sites over terrain and county outlines). Fig. 9 shows the national sites. Current Figs. 1-11 will renumber to 2-12.",
"Before submission: move the text into the Copernicus Word template; archive the code on Zenodo and cite its DOI; decide whether to deposit the matched datasets; complete the Zoogman et al. (2017) author list; confirm the TEMPO dataset citation on the DOI landing page; and re-check the claim of novelty in the Introduction against the literature.",
"Yellow-highlighted text marks statements to verify or decisions to make."
];

// ---------------------------------------------------------------- 1 Introduction
{
  const s = S[byHead("1 Introduction")];
  // replace the final two framing paragraphs
  s.p[3] = "An hourly geostationary instrument changes this arithmetic, because every sample day yields a dozen observations and the satellite can be matched to the hours a sample actually covers. To our knowledge TEMPO HCHO has not yet been evaluated against routine surface air toxics measurements at daily or sub-daily resolution [[re-check before submission]]. Such networks collect integrated samples designed for long-term risk assessment rather than satellite validation, so the practical questions are how often a usable satellite observation is available, how well TEMPO tracks the seasonal cycle and day-to-day variations at individual monitors, how the comparison depends on the choice of spatial and temporal matching, how much the answer varies from monitor to monitor, and what limits the agreement that remains.";
  s.p[4] = "Here we compare TEMPO Level 3 version 4 HCHO columns with surface HCHO measured in 2024–2025 at every United States monitor reporting formaldehyde to EPA's Air Quality System: 123 sites in 37 states, including National Air Toxics Trends Stations, NCore multipollutant sites and Photochemical Assessment Monitoring Stations, with sample durations of 24, 8 and 3 h. Within that network we treat Colorado as a case study. Colorado designated formaldehyde a priority toxic air contaminant, its network spans an urban–industrial corridor north of Denver, oil-and-gas-producing and agricultural areas on the northern Front Range, southern Front Range cities and a valley city on the Western Slope, and its data reach us both through the state's own data packets, which carry information AQS does not hold, and through AQS, which allows the two pathways to be cross-checked. The terrain is also demanding: elevation and boundary layer structure complicate the relationship between column and surface.";
  s.p[5] = "We (i) quantify the availability of screened TEMPO observations on sample days; (ii) separate seasonal from day-to-day agreement, nationally and site by site; (iii) test the sensitivity of the comparison to cloud screening, spatial averaging and time-of-day selection; (iv) use the sub-daily samples, whose sampling windows are recorded in AQS, to examine how agreement depends on the delay between sampling and the satellite view, and on the hour at which sampling takes place; (v) assess the influence of wildfire smoke identified by the NOAA Hazard Mapping System (HMS) in the Colorado case study; and (vi) test candidate explanations for the agreement we find, including retrieval noise, terrain and time of day.";
}

// ---------------------------------------------------------------- 2 Data: new 2.3
rename("2.3 TEMPO formaldehyde columns", "2.4 TEMPO formaldehyde columns");
rename("2.4 NOAA Hazard Mapping System smoke analyses", "2.5 NOAA Hazard Mapping System smoke analyses");
rename("2.1 Colorado Air Toxics Trends network (24 h samples)",
       "2.1 Colorado Air Toxics Trends network (24 h samples; case study)");
rename("2.2 COOPs ozone-precursor sites (3 h samples)",
       "2.2 COOPs ozone-precursor sites (3 h samples; case study)");

const natData = {
  h2: "2.3 National formaldehyde monitors (EPA Air Quality System)",
  p: [
"Formaldehyde is measured routinely across the United States by state, local and tribal agencies and reported to EPA's Air Quality System (AQS) as parameter 43502 (U.S. EPA, 2025). Almost all of these measurements use the same approach as Colorado's: air is drawn through a 2,4-dinitrophenylhydrazine-coated cartridge and the derivative is quantified by high-performance liquid chromatography, following Compendium Method TO-11A (U.S. EPA, 1999). Of the samples analysed here, 76 % were collected with a potassium-iodide ozone scrubber upstream of the cartridge, 16 % on a bare silica cartridge and 8 % behind a heated ozone denuder. Three programmes account for most of the monitors: the National Air Toxics Trends Stations (NATTS), which measure long-term trends in priority air toxics at a small number of urban and rural sites; the NCore multipollutant network; and the Photochemical Assessment Monitoring Stations (PAMS) in ozone non-attainment areas, where carbonyl sampling is sub-daily and often seasonal.",
"We retrieved every formaldehyde sample reported to AQS for 1 January 2024 to 31 December 2025: 16 383 samples at 123 sites in 37 states (Table 5). For each sample AQS records the local standard time at which sampling began, the corresponding GMT date and time, and the sample duration, so the sampling window of every sample is known without a time zone assumption. This is precisely the information the Colorado data packets lack (Sect. 2.2), and it is what makes a national analysis of sampling time possible. Records carrying an AQS null data qualifier were removed (5009 samples carry at least one qualifier of any kind), and where more than one method within a site reported the same window their values were averaged. AQS reports these measurements in parts per billion carbon, which for formaldehyde equals parts per billion by volume; we converted to mass concentration at 25 °C and 1 atm, matching the reporting convention used for the Colorado packets (Sect. 3.2).",
"The network divides into three sampling regimes. One hundred and two sites collect 24 h samples (8730 samples, 30 states), almost all beginning at midnight local standard time, typically every third or sixth day; 23 of these are NATTS sites and 21 are PAMS sites. Forty sites collect 8 h samples (6972 samples, 29 states), every one of them in the same three fixed blocks beginning at 04:00, 12:00 and 20:00 local standard time, so that a single site samples the morning transition, the well-mixed afternoon and the night separately. Four sites collect 3 h samples (681 samples): the two Colorado COOPs sites of Sect. 2.2, which sample only 06:00–09:00 MST, and two sites in California's San Joaquin Valley, Bakersfield-Muni and Clovis-Villa, which sample five windows a day beginning at 05:00, 08:00, 12:00, 16:00 and 23:00 LST between June 2024 and August 2025. The Colorado 24 h sites appear in both arms of this study, once through the state packets and once through AQS, which we use as a check on the two data pathways (Sect. 4.9)."
  ]
};
S.splice(byHead("2.4 TEMPO formaldehyde columns"), 0, natData);

// ---------------------------------------------------------------- 3.2 corrected
setP("3.2 Effective mixing height", [
"To relate the column to the surface concentration we converted the surface mass concentration to a number density n_{s} (molecules cm^{-3}) and defined an effective mixing height H_{eff} = Ω/n_{s}, where Ω is the TEMPO column. H_{eff} is the depth of a uniform layer at the surface concentration that would contain the observed column. It combines the vertical distribution of HCHO (including the free-tropospheric column), biases in the retrieval and in the surface measurement, and the mismatch between the sampling period and daytime satellite sampling, so it is used here as a diagnostic rather than a physical boundary layer depth.",
"The conversion depends on the conditions at which concentrations are reported. Cross-checking the CDPHE packets against the same samples in AQS shows that the two differ by exactly the factor M/24.45, where M = 30.026 g mol^{-1} is the molar mass of HCHO: the packets report mass concentrations at standard conditions (25 °C, 1 atm), and AQS reports the corresponding mixing ratio. We therefore converted the reported concentration to a mixing ratio, χ = C × 24.45/M, and then to a number density at the conditions of the air, n_{s} = χ × 10^{-9} p/(k_{B}T), using the TEMPO surface pressure at the site (median 840 hPa at the Colorado sites) and, for the Colorado arm, the site- and month-mean surface temperature (median 8.8 °C). Ignoring this correction, as an analysis that assumed local-condition reporting would, overestimates n_{s} and understates H_{eff} by about 15 % at the elevations of the Front Range sites. For the national arm, where no surface temperature accompanies the AQS records, a fixed 15 °C was used with the retrieved surface pressure; a 10 K error in this assumption changes H_{eff} by 3 %. H_{eff} was computed only for positive columns and compared with the TEMPO PBL height averaged over the same valid scans."
]);

// ---------------------------------------------------------------- 3.7 national methods
const natMethods = {
  h2: "3.7 The national comparison",
  p: [
"The national arm repeats the Colorado analysis at every AQS site, with three differences forced by its scale. First, extraction: requesting a separate OPeNDAP subset for each of 123 sites would multiply the number of requests by the number of sites, so sites were grouped into 50 clusters of at most 1.25° latitude by 2.5° longitude, one subset was requested per cluster and scan, and the 5 × 5 cell block around each site was cut from it afterwards. Only scans that a cluster's samples actually require were retrieved: the days a site sampled, and for sub-daily samples the sampling window padded by 3 h on each side so that the lagged windows are covered. This produced 88 622 cluster-scans and 3.97 million cell records.",
"Second, matching. A sampling window is expressed as the set of hours it spans, in UTC, and a scan is assigned to a window when the hour containing its midpoint belongs to that set. Because every AQS sampling window begins on the hour, this is exact. Lagged windows are the same set shifted by −3, 0, +3 or +6 h; lags are applied only to sub-daily samples, since a 24 h window shifted by a few hours is almost the same window. Screening, block sizes and cloud thresholds are as in Sect. 3.1, and the primary configuration is again an effective cloud fraction of 0.2 and a 3 × 3 block.",
"Third, statistics. Correlations and within-month anomaly correlations are computed as in Sect. 3.3, pooled by sample duration and lag, by the local standard hour at which the sampling window begins, and site by site (sites with at least 10 matched samples, and window start hours with at least 12). Because the number of sites is large, the pooled regression uses ordinary least squares with the column as a fixed effect and fixed effects for site and calendar month, rather than a mixed model. Wildfire smoke is not classified in the national arm; the HMS analysis remains part of the Colorado case study."
  ]
};
S.splice(byHead("4 Results"), 0, natMethods);

// ---------------------------------------------------------------- 4.5 corrected numbers
setP("4.5 Column–surface relationship", [
"The seasonal amplitude of the column exceeded that of the surface concentration. From winter to summer, median surface HCHO on matched days increased from 2.12 to 3.51 µg m^{-3} (1.7-fold), whereas the median column increased from 2.18 to 6.63 × 10^{15} molecules cm^{-2} (3.0-fold). Correspondingly, the median effective mixing height H_{eff} increased from 0.62 km in winter and 0.65 km in spring to 1.06 km in summer, and was 0.83 km in autumn (Fig. 5). Across all matched days, median H_{eff} was 0.83 km, compared with a median TEMPO PBL height of 1.55 km. H_{eff} was well below the PBL height in spring (0.65 versus 1.77 km), summer (1.06 versus 2.11 km) and autumn (0.83 versus 1.28 km) and close to it in winter (0.62 versus 0.64 km). By site, median H_{eff} ranged from 0.72 km at Grand Junction and 0.76 km at Commerce City to 1.06 km at Colorado Springs and 1.13 km at Cañon City."
]);

// Fig. 5 caption unchanged in wording but note the conditions
{
  const i = find(s => s.fig && s.fig.file === "fig3_effective_height_by_month.png");
  S[i].fig.caption = "Figure 5. Monthly distributions of the effective mixing height H_{eff} (TEMPO column divided by the surface number density at the temperature and pressure of the air, Sect. 3.2) on matched days by site. Orange diamonds show the median TEMPO PBL height on the same days. The vertical axis is truncated at the 98th percentile.";
}

// ---------------------------------------------------------------- Table 3 and 4: H_eff row
{
  const t3 = S[find(s => s.table && /^Table 3\./.test(s.table.caption))].table;
  const r = t3.rows.find(r => r[0].startsWith("Median H_{eff}"));
  r[1] = "0.95 / 0.54"; r[2] = "0.95 / 1.56"; r[3] = "0.90 / 2.25";

  const t4 = S[find(s => s.table && /^Table 4\./.test(s.table.caption))].table;
  const heff = { "DJF|none": "0.62", "MAM|none": "0.65", "MAM|light": "0.72",
    "JJA|none": "1.06", "JJA|light": "1.12", "JJA|medium–heavy": "0.96",
    "SON|none": "0.80", "SON|light": "0.98", "SON|medium–heavy": "1.02" };
  t4.rows.forEach(r => { const k = r[0] + "|" + r[1]; if (heff[k]) r[6] = heff[k]; });
  t4.caption = t4.caption.replace("effective mixing height by season",
    "effective mixing height (at the temperature and pressure of the air, Sect. 3.2) by season");
}

// ---------------------------------------------------------------- 4.9 / 4.10 national results
const natResults = [
{
  h2: "4.9 Agreement across the national network",
  p: [
"TEMPO coverage of the 24 h samples was slightly lower nationally than in Colorado: 70 % of the 8730 samples had at least one scan passing the primary screening, against 75 % in Colorado, with a median of 11 usable scans per sample day. Coverage varied widely between sites, from around 90 % in Arizona, southern California and on the Texas Gulf coast to below 50 % in western Oregon, Vermont and upstate New York, with the lowest values at Tualatin, Oregon (37 %) and Proctor Maple Research Center, Vermont (40 %).",
"Pooled across the 24 h sites, the daily mean column and the 24 h surface concentration correlated at r = 0.42 (ρ = 0.48, n = 6106), and after removing site and calendar-month means the day-to-day correlation was 0.40 (n = 5218 in 1262 site-months). Two comparisons make these numbers interpretable. First, the pooled correlation is well below the median correlation computed within individual sites (0.64; Fig. 9), so pooling across the country dilutes rather than inflates: TEMPO tracks variation at a given monitor considerably better than it tracks the differences between monitors, whose column-to-surface ratios differ with climate, mixing depth and the free-tropospheric background. Second, pooling adds almost nothing over the day-to-day correlation nationally (0.42 against 0.40), whereas in Colorado it adds a great deal (0.56 against 0.30). Colorado's seven sites share one regional seasonal cycle, which the pooled statistic rewards; across the country the seasonal cycles and mean levels are heterogeneous enough to cancel that gain. The day-to-day correlation is therefore the quantity to compare between networks, and by that measure Colorado is below the national norm. The regression of surface concentration on the column, with fixed effects for site and calendar month, gave 0.163 ± 0.006 µg m^{-3} per 10^{15} molecules cm^{-2} (p < 10^{-100}), close to the 3 h Colorado estimate of 0.136 ± 0.037 in the window three hours after sampling. Median H_{eff} across the 24 h sites was 1.09 km against a median TEMPO PBL height of 1.04 km, so nationally the column and the modelled mixed layer are consistent with a well-mixed HCHO profile; Colorado's H_{eff} of about half the PBL height is not the general case.",
"Agreement is significant at most individual sites but far from uniform (Fig. 9). Of 141 site–duration combinations with at least 10 matched samples, 122 had a significant positive correlation. At the 97 sites with enough 24 h samples the median correlation was 0.64 (interquartile range 0.45–0.72) and the median day-to-day correlation 0.48 (0.27–0.59), ranging from 0.89 at Medford, Oregon, 0.85 at Fresno and 0.79 at Stockton, California, to values indistinguishable from zero at a dozen sites and −0.24 at St. Charles Mesa, Colorado. The 40 sites sampling 8 h blocks behaved similarly (median correlation 0.48, median day-to-day correlation 0.47). Colorado's six 24 h AQS sites had a median day-to-day correlation of 0.35, below the national median of 0.48 and below the medians for Iowa (0.59), Michigan (0.59), Pennsylvania (0.54) and California (0.40), and above New York (0.33).",
"The two data pathways agree. At the three Colorado sites with two-year records, the day-to-day correlation computed from the state's data packets and from the same samples retrieved through AQS differ by at most 0.02 (La Salle 0.62 and 0.61, Commerce City 0.48 and 0.48, Grand Junction 0.21 and 0.22), which is reassuring for both the packet parsing and the AQS unit conversion, and means the case study and the national analysis can be read together.",
"Two features of the national distribution bear on what limits agreement. Sensitivity to the processing choices is the same as in Colorado: pooled over 24 h sites, the correlation rises from 0.39 for single cells to 0.42 for 3 × 3 blocks and 0.43 for 5 × 5 blocks, and a stricter cloud threshold of 0.1 helps slightly (0.44 at 3 × 3) at the cost of 9 % of the samples — the signature of averaging down noise rather than of a change in what is being measured. And agreement is weakest where concentrations are lowest: grouping the 24 h sites into thirds by median surface concentration, the median day-to-day correlation is 0.34 in the lowest third (0.6–2.0 µg m^{-3}), 0.58 in the middle third and 0.46 in the highest. A fixed retrieval noise is a larger fraction of the variance where the signal is small, which is what the Colorado noise analysis (Sect. 4.8) implies should happen."
  ]
},
{ fig: { file: "fig13_national_site_map.png", w: 1650, h: 2640,
  caption: "Figure 9. Day-to-day agreement (within-month anomaly correlation) between TEMPO HCHO columns and surface HCHO at each site, by sample duration, for scans inside the sampling window. Colour shows the correlation and symbol size the number of matched samples. Sites with fewer than 10 matched samples are not shown." } },
{
  h2: "4.10 Sampling window and time of day across the network",
  p: [
"The national sub-daily sites allow the Colorado lag result to be tested where sampling windows differ. Two cautions are needed first. Pooling a lag curve across sites that sample different windows mixes together shifts that mean quite different things — a −3 h shift is the middle of the night for a 05:00 sample and mid-morning for a 12:00 sample — so the pooled curves (Fig. 10) are reported for completeness but are not comparable with Colorado's, where every sample covers the same window. The informative cut is by the hour at which sampling begins (Fig. 11). Second, an 8 h window shifted by 3 h still overlaps the original window by five hours, so lag curves for the 8 h sites are expected to be flat, and they are: the day-to-day correlation is 0.31, 0.38, 0.35 and 0.32 at lags of −3, 0, +3 and +6 h.",
"Grouped by the hour at which the window starts, the pattern is clear and it is not the one Colorado alone would suggest. At the two California sites sampling 3 h blocks, the window beginning at 05:00 LST tracks the surface as well as any: the day-to-day correlation is 0.44 (n = 99) for scans inside the sampling window, essentially the same as the 0.41 of the midday window beginning at 12:00 (n = 100), while the late-afternoon window beginning at 16:00 shows no significant agreement (0.17, n = 91, p = 0.11). The Colorado window beginning at 06:00 MST is the outlier: 0.11 (n = 79, p = 0.35), against 0.40 for the same samples matched to scans three hours later (Sect. 4.6). The 8 h sites show the same ordering more coarsely: the block beginning at 12:00 LST gives a day-to-day correlation of 0.42 (n = 1754) and the block beginning at 04:00, which straddles the morning transition, 0.34 (n = 1698); the block beginning at 20:00 is dark and yields no usable scans.",
"In other words, morning sampling is not intrinsically hard to match to a satellite column. At the California sites, samples collected between 05:00 and 08:00 local time agree with the column measured during those same hours. It is at Colorado's two Front Range sites, sampling one hour later in the day, that the sampling window fails and the window three hours later succeeds."
  ]
},
{ fig: { file: "fig11_national_lag_curve.png", w: 2400, h: 1380,
  caption: "Figure 10. Pooled correlation between sub-daily surface HCHO and the mean TEMPO column as a function of the lag of the TEMPO window from the sampling window, for the 3 h and 8 h sites. “Whole” uses the concentrations as measured; “anomalies” uses deviations from site and calendar-month means. Labels give the number of matched samples. Because the sites pooled here sample different windows, a given lag corresponds to different times of day at different sites (Sect. 4.10)." } },
{ fig: { file: "fig12_national_by_start_hour.png", w: 2400, h: 1380,
  caption: "Figure 11. The same correlations grouped by the local standard hour at which the sampling window begins, using only scans inside the sampling window. In the 3 h panel, the windows beginning at 05:00, 12:00 and 16:00 are the two California sites and the window beginning at 06:00 is the two Colorado sites; in the 8 h panel each point pools all 40 sites. Labels give the number of matched samples." } }
];
S.splice(byHead("5 Discussion"), 0, ...natResults);

// new Table 5, placed at the start of Sect. 4.9 (after its heading)
{
  const t5 = { table: {
    caption: "Table 5. The national comparison by sample duration. Sites and samples are those reported to AQS for 2024–2025; matched and usable counts and correlations are for the primary screening (effective cloud fraction ≤ 0.2, 3 × 3 cell block) with TEMPO scans inside the sampling window. Day-to-day correlations use deviations from site and calendar-month means. The Colorado case-study values from the state data packets are shown for comparison.",
    header: ["", "24 h", "8 h", "3 h", "Colorado 24 h (packets)"],
    widths: [2700, 1500, 1400, 1400, 2026],
    rows: [
      ["Sites", "102", "40", "4", "7"],
      ["States", "30", "29", "2", "1"],
      ["NATTS / PAMS sites", "23 / 21", "10 / 35", "0 / 2", "1 / 0 (of the six in AQS)"],
      ["Samples", "8730", "6972", "681", "453"],
      ["Window start hours (LST)", "00", "04, 12, 20", "05, 08, 12, 16, 23 (CA); 06 (CO)", "00"],
      ["Samples with a usable scan", "6106 (70 %)", "3509 (50 %)", "402 (59 %)", "338 (75 %)"],
      ["Median usable scans per sample", "11", "6", "2", "11"],
      ["Pearson r", "0.42", "0.33", "0.46", "0.56"],
      ["Spearman ρ", "0.48", "0.38", "0.42", "0.57"],
      ["Day-to-day r (n)", "0.40 (5218)", "0.38 (3509)", "0.39 (383)", "0.30 (305)"],
      ["Column coefficient (µg m^{-3} per 10^{15} molecules cm^{-2})", "0.163 ± 0.006", "0.193 ± 0.008", "0.229 ± 0.028", "–"],
      ["Median surface HCHO (µg m^{-3})", "2.46", "4.18", "3.93", "2.66"],
      ["Median column (10^{15} molecules cm^{-2})", "5.50", "10.31", "8.78", "3.50"],
      ["Median H_{eff} / median TEMPO PBL height (km)", "1.09 / 1.04", "1.27 / 1.12", "1.05 / 1.05", "0.83 / 1.55"],
      ["Sites with a significant correlation", "85 of 97", "34 of 40", "3 of 4", "5 of 7"],
      ["Median day-to-day r by site (IQR)", "0.48 (0.27–0.59)", "0.47 (0.26–0.57)", "0.31 (0.05–0.42)", "0.21 (−0.24–0.55)"]
    ],
    notes: "Sites with a significant correlation and median day-to-day r by site are computed over sites with at least 10 matched samples. The Colorado column repeats the case-study results of Sects. 4.2–4.3 from the CDPHE data packets; the same Colorado sites also appear in the 24 h and 3 h columns through AQS."
  }};
  S.splice(byHead("4.9 Agreement across the national network") + 1, 0, t5);
}

// ---------------------------------------------------------------- 5.1, 5.2, 5.3 touch-ups
setP("5.1 What TEMPO captures at air toxics monitors", [
"TEMPO HCHO columns reproduced the seasonal cycle and the broad differences among surface air toxics monitors, and a usable observation was available for about seven of every ten 24 h samples nationally and three of every four in Colorado. Day-to-day agreement was weaker and strongly site dependent: significant at most monitors, with a median correlation near 0.5 at 24 h sites, but ranging from 0.9 to zero. This is the central practical result. A satellite column is informative about the day-to-day variation seen by a typical air toxics monitor, and useless at some, and which of the two a given monitor is cannot be assumed from the network average.",
"Within Colorado, the strongest anomaly correlations were at La Salle and Commerce City on the northern Front Range, and the weakest among long records was at Grand Junction. Colorado's monitors sit below the national median, so whatever limits agreement there is not universal. We can only speculate about the reasons for the differences; they may include the magnitude of synoptic and episodic variability relative to retrieval noise, the representativeness of a monitor for a several-kilometre area, and, at Grand Junction, a valley setting where persistent winter inversions could decouple surface concentrations from the column [[hypothesis — consider meteorological analysis]]. The national distribution gives one clue: agreement is weakest at the lowest-concentration sites (Sect. 4.9), which is what a fixed retrieval noise predicts. The records at Colorado Springs, Pueblo, Cañon City and Wheat Ridge (July or October to December 2025) are too short to characterise day-to-day skill."
]);

setP("5.3 Interpreting the column–surface relationship", [
"In Colorado the effective mixing height was about half the TEMPO PBL height on matched days (0.83 against 1.55 km); nationally the two were close (1.09 against 1.04 km). Three factors bear on the difference between column and surface. First, TEMPO HCHO columns have been reported to be biased low by about 30 % relative to FTIR and Pandora observations (Ortega et al., 2026) [[add site-specific Boulder values and Rawat et al. (2026) high-column bias after checking the papers]]; correcting a 30 % low bias would raise the Colorado median H_{eff} from 0.83 km to about 1.2 km, comparable with the median PBL height. Second, HCHO produced or emitted within the boundary layer and concentrated near the surface yields H_{eff} below the PBL depth. Third, the 24 h surface samples include night-time concentrations that the daytime satellite does not see. Known artefacts of DNPH sampling, such as the negative interference from ozone (Arnts and Tejada, 1989), would lower surface concentrations and raise H_{eff}, so they do not explain low values; most national samples are collected with an ozone scrubber or denuder (Sect. 2.3). Calibration differences among HCHO measurement techniques can also be substantial (Jeong et al., 2026).",
"That Colorado's H_{eff} is low relative to the national value is consistent with its monitors sitting at high elevation in semi-arid terrain, where the modelled boundary layer is deep in summer while HCHO remains concentrated near its sources. The larger seasonal amplitude of the column than of the surface concentration — 3.0-fold against 1.7-fold from winter to summer — is consistent with deeper summer mixing and a larger free-tropospheric HCHO column in summer. The 3 h comparison adds a direct constraint: between 06:00–09:00 and 09:00–12:00 the median TEMPO boundary layer height rises from 0.5 to 1.6 km while the median column and the inferred H_{eff} barely change (0.95 km in both windows), as expected because vertical mixing redistributes HCHO without altering the column."
]);

// 5.2: replace the last sentence about the national extension
{
  const s = S[byHead("5.2 Noise and spatial averaging")];
  s.p = [s.p[0].replace(
    "Where agreement stays far below the noise ceiling, as at Grand Junction, the explanation must lie with the monitor's representativeness or with the vertical structure above it rather than with retrieval noise; neither terrain inside the block nor a winter effect accounts for it, and identifying what does would need meteorological analysis beyond this study [[consider for the national extension]].",
    "Where agreement stays far below the noise ceiling, as at Grand Junction, the explanation must lie with the monitor's representativeness or with the vertical structure above it rather than with retrieval noise; neither terrain inside the block nor a winter effect accounts for it, and identifying what does would need meteorological analysis beyond this study. The national results support the same reading from the other direction: the block-size gradient is reproduced across the country, and the sites where agreement is weakest are those with the lowest concentrations, where a fixed noise consumes the largest share of the variance (Sect. 4.9).")];
}

// ---------------------------------------------------------------- 5.4 rewritten
rename("5.4 Sampling time, mixing, and the lag that matters",
       "5.4 Sampling time, mixing, and why the lag that matters is site dependent");
setP("5.4 Sampling time, mixing, and why the lag that matters is site dependent", [
"The Colorado 3 h samples show that the comparison depends on when TEMPO looks relative to when the air was sampled, and that the best match is not the sampling window itself. Samples collected between 06:00 and 09:00 MST correlated poorly with the column measured at the same time, well with the column three hours later, and not at all with the column six hours later. The national sub-daily sites show that this is not a general property of morning samples. At the two California sites, samples collected between 05:00 and 08:00 local time correlate with the column measured during those same hours as well as midday samples do with the midday column. The lag that matters is a property of the site, not of the clock.",
"Three lines of evidence argue against the simplest alternative, that early-morning retrievals are too poor to be useful. At the 24 h sites, where the sample spans the whole day, early scans track the surface as well as later scans (Sect. 4.8). Scan-to-scan noise and reported per-cell uncertainties are similar in the two windows. And the California result settles it directly: an early-morning window that carries no day-to-day information at two Colorado sites carries as much as a midday window at two Californian ones, even though the Californian window begins an hour earlier in the day.",
"A boundary layer explanation fits all of these observations. Between 06:00 and 09:00 on the Front Range the surface layer is shallow and stable, so a surface sample reflects overnight accumulation in a thin layer that is decoupled from most of the column above it; the column at that hour is dominated by the residual layer and the free troposphere. By 09:00–12:00 the mixed layer has deepened — the median TEMPO boundary layer height triples — and has entrained the air that was near the surface during sampling, so the column and the sample describe much the same air mass. By 12:00–15:00, with the mixed layer deeper still, photochemical production, entrainment of free-tropospheric air and horizontal transport have replaced or diluted that air, and the correspondence is lost. On this reading, the lag that maximises agreement is the delay between sampling and the time at which the sampled air becomes part of the mixed layer, which depends on how stable the local morning boundary layer is and how quickly it breaks up.",
"The contrasts within our data are consistent with that. Chatfield State Park lies at the foot of the Front Range, where nocturnal drainage flow and a strongly stable morning layer decouple the surface from the air aloft; its sampling-window correlation is essentially zero and the +3 h window is strong. Platteville sits on the open plains of the Denver–Julesburg basin, where morning decoupling is weaker and the surrounding region is more uniform, and there the sampling window and the +3 h window perform about equally (0.55 and 0.46 for the whole record). Bakersfield and Clovis lie on the floor of the San Joaquin Valley, where the summer morning boundary layer grows early and the samples begin an hour earlier still, and there the sampling window works. This ordering is what a morning-stability explanation predicts, but our data cannot test it directly; co-located boundary layer measurements, or a lag analysis stratified by a stability index, would [[hypothesis — could be tested with boundary layer soundings or modelled stability]].",
"The 8 h sites make the same point on a coarser time grid and with 40 sites rather than four. The block beginning at 12:00 local time, which lies wholly within the well-mixed afternoon, agrees better than the block beginning at 04:00, which spends its first hours in the stable morning layer and its remaining hours after mixing. The difference is real but modest (day-to-day correlations of 0.42 and 0.34), as expected when a window is long enough to average across the transition.",
"The practical implication is therefore not “match the satellite to the sampling window”, nor “add three hours”, but “match it to the hours when the sampled air is part of the mixed layer”, and to determine when those hours are at each site rather than assuming. For 24 h samples the all-day mean is a reasonable compromise, as our results show; for programmes designing sub-daily carbonyl sampling, a window centred on the middle of the day should correspond most closely to what a geostationary instrument sees, at every site. Whatever the choice, the metadata matter: without the sample start times recorded in AQS we would have had the Colorado sampling window backwards, and would have reported the best-fitting window as the sampling window."
]);

// ---------------------------------------------------------------- 5.6 new, 5.6 -> 5.7
rename("5.6 Implications for air toxics monitoring and limitations",
       "5.7 Implications for air toxics monitoring and limitations");
S.splice(byHead("5.7 Implications for air toxics monitoring and limitations"), 0, {
  h2: "5.6 Colorado in national context, and what a national comparison adds",
  p: [
"Taking the national network as the reference changes how the Colorado results should be read. The pooled correlation across Colorado's seven sites, 0.56, is higher than the national 0.42, but the two are not measuring the same thing. A correlation pooled over sites is a mixture of agreement within sites and agreement about the differences between them, and the mixture depends on how alike the sites are. Colorado's pooled value is close to the median correlation at its individual sites (0.53), because its seven monitors share one regional seasonal cycle; the national pooled value falls well below the median at individual sites (0.42 against 0.64), because monitors in different climates have different column-to-surface ratios. The day-to-day correlation, which removes both the seasonal cycle and the between-site differences, is the quantity that means the same thing in both, and there Colorado sits below the national norm (0.30 pooled and 0.35 as a median over its AQS sites, against 0.40 and 0.48 nationally). A study of a single state would not have known which of these it was seeing.",
"The national comparison also tests the two explanatory claims the case study makes. The first, that averaging blocks help because they average down noise, predicts a block-size gradient everywhere and weaker agreement where concentrations are low; both hold across the country. The second, that the timing of the match is governed by boundary layer development rather than by the quality of morning retrievals, predicts that morning sampling should work at sites where the morning layer grows early; that is what the California sites show. Neither test was available from Colorado alone.",
"Finally, the comparison places these results beside the only previous study of surface and satellite HCHO over the United States. Wang et al. (2022) compared seasonal means of surface HCHO at 45 AQS sites with OMI columns for 2006–2015 and found regional correlations of 0.56–0.87 in summer, weak or negative correlations in winter, and a seasonal amplitude 20–100 % larger in the column than at the surface. Our seasonal findings reproduce theirs — the column amplitude is roughly twice the surface amplitude in Colorado — but the comparison no longer has to be seasonal. With a geostationary instrument, 70 % of individual 24 h samples across the country carry a usable observation, and the same networks can be used to ask when, and at which monitors, a satellite tracks day-to-day variation."
  ]
});

setP("5.7 Implications for air toxics monitoring and limitations", [
"For air toxics programmes, these results suggest that TEMPO can provide spatial and seasonal context between and around 1-in-6 day samples and can flag regional episodes such as smoke, but it cannot substitute for monitor measurements at daily time scales at an individual site — and how close it comes varies enormously between monitors. A programme considering satellite data as a supplement can estimate what to expect at its own sites from the site-level results reported here (Fig. 9) rather than from a network average. Pairing satellite observations with time-resolved surface samples, recording sampling start and end times, and preferring midday sampling windows where the science allows would all make better use of hourly retrievals.",
"Several limitations apply. The record spans two years. In the Colorado case study, four 24 h sites have six months or less of data and the 3 h record at Platteville ends in July 2025; nationally, the sub-daily arm rests on 40 sites with one 8 h sampling pattern and four sites with 3 h samples, two of them the Colorado pair, so the evidence that morning sampling can work rests on two Californian sites in one air basin. Integrated DNPH samples are subject to artefacts and calibration uncertainty. The lags that could be examined were limited by the solar zenith angle screen, which removes the earliest and latest windows entirely, and the 20:00 LST block of the 8 h sites is dark. The national effective mixing heights assume a fixed air temperature of 15 °C (Sect. 3.2). TEMPO V04 HCHO is provisional; scans were assigned to sampling periods by granule midpoint, which can differ from the time TEMPO viewed a given site by tens of minutes; and the PBL height is a model product. Wildfire smoke is classified only in the Colorado case study, and HMS smoke classification is qualitative and column based. Finally, many correlations were computed across sites, seasons and screening variants without correction for multiple comparisons, and anomaly p-values are optimistic; the site-level significance counts in Sect. 4.9 should be read with that in mind."
]);

// ---------------------------------------------------------------- 6 Conclusions
setP("6 Conclusions", [
"We evaluated TEMPO Level 3 V04 HCHO columns against every integrated formaldehyde sample reported to EPA's Air Quality System in 2024–2025 — 16 383 samples at 123 sites in 37 states — with Colorado's air toxics and ozone-precursor network examined in detail as a case study. Nationally, a screened TEMPO observation was available for 70 % of 24 h samples; the daily column and the 24 h surface concentration correlated at 0.42, and at 0.40 once the shared seasonal cycle and the differences between sites were removed. Agreement was significant at 122 of 141 site–duration combinations but varied from 0.9 to zero between monitors, with a median day-to-day correlation of 0.48 at 24 h sites. It was weakest where concentrations were lowest, and it improved with spatial averaging everywhere; in Colorado, where the noise could be quantified from successive scans, about half the day-to-day variance of a 3 × 3 daily column is retrieval noise, which caps the attainable correlation near 0.7 and accounts for the whole benefit of averaging.",
"The hour at which a sample is collected matters more than its length or the precision of the match. Colorado's 3 h samples, whose 06:00–09:00 MST window is recorded in AQS, agree with TEMPO not during sampling (r = 0.12) but three hours later (0.40), and not at all after six hours (0.03). The national sites show that this lag is a property of the site rather than of the clock: at two California sites the 05:00–08:00 window agrees with the column measured in that same window as well as midday sampling does, and across 40 sites sampling 8 h blocks the midday block outperforms the morning block. The unifying explanation is that a surface sample and the column describe the same air only once the morning boundary layer has entrained the sampled air, at an hour that depends on local morning stability. In the Colorado case study, wildfire smoke raised both surface and column HCHO within season and contributed to day-to-day agreement, most clearly in that same post-sampling window.",
"TEMPO provides useful seasonal and episodic context for air toxics monitoring across the United States, and its value for tracking day-to-day variation is greatest when observations are averaged spatially, when the monitor's concentrations are not close to the retrieval noise floor, and when the satellite is matched to the hours in which the sampled air is mixed through the boundary layer. Which of those conditions hold is a question that can now be answered monitor by monitor."
]);

// ---------------------------------------------------------------- availability
setP("Code availability", [
"The R code used for data retrieval, processing, statistics and figures is available at https://github.com/pdez90/coatts_hcho (commit 14a1257, the state of the analysis code that produced the results reported here) [[archive a release on Zenodo and cite its DOI]]. A single script reproduces both arms of the analysis, from downloading the CDPHE data packets, the AQS records, the TEMPO granules and the HMS shapefiles through to every table and figure."
]);
setP("Data availability", [
"CDPHE formaldehyde data packets are available from the CDPHE Air Toxics and Ozone Precursor Data Repository (https://www.colorado.gov/airquality/air_toxics_repo.aspx). National formaldehyde samples, sample times and monitor metadata come from EPA's Air Quality System (https://aqs.epa.gov/aqsweb/documents/data_api.html and https://aqs.epa.gov/aqsweb/airdata/download_files.html). TEMPO Level 3 V04 HCHO data are available from the NASA Langley Atmospheric Science Data Center (https://doi.org/10.5067/IS-40e/TEMPO/HCHO_L3.004). NOAA HMS smoke polygons are available from https://satepsanone.nesdis.noaa.gov/pub/FIRE/web/HMS/Smoke_Polygons/Shapefile/. [[Decide whether to deposit the matched datasets with a DOI.]]"
]);

// ---------------------------------------------------------------- references
C.references.push(
"U.S. EPA: National Air Toxics Trends Stations (NATTS) and the ambient air monitoring networks, U.S. Environmental Protection Agency, https://www.epa.gov/amtic/national-air-toxics-trends-stations-natts (last access: [[date]]), 2025. [[check title and citation form]]"
);
C.references.sort((a, b) => a.localeCompare(b, "en"));

// ---------------------------------------------------------------- 4.6 / 4.7 stale H_eff
{
  const s46 = S[byHead("4.6 Three-hour samples: agreement depends on the lag from sampling")];
  s46.p = s46.p.map(t => t.replace(
    "while the median effective mixing height stayed near 0.8 km at every lag",
    "while the median effective mixing height stayed near 0.95 km at every lag"));
  const s47 = S[byHead("4.7 Wildfire smoke")];
  s47.p = s47.p.map(t => t.replace(
    "The effective mixing height did not change consistently with smoke in summer (0.88, 0.94 and 0.80 km) but was higher on the 13 autumn smoke days (0.70, 0.85 and 0.90 km).",
    "The effective mixing height did not change consistently with smoke in summer (1.06, 1.12 and 0.96 km) but was higher on the 13 autumn smoke days (0.80, 0.98 and 1.02 km)."));
}

// ---------------------------------------------------------------- write
const out = "// content_v4.js - generated by mkcontent4.js; do not edit by hand\n" +
  "module.exports = " + JSON.stringify(C, null, 1) + ";\n";
fs.writeFileSync("content_v4.js", out);
console.log("wrote content_v4.js:", out.length, "bytes;", C.sections.length, "blocks");
