// mkcontent8.js - content_v7.js -> content_v8.js
// Resolves the novelty claim after the literature search of 14 September 2026.
// The search found no evaluation of TEMPO HCHO against surface concentration
// measurements from routine networks; NASA's own validation report lists the HCHO
// comparisons as TROPOMI, PGN, NDACC FTIR, aircraft profiles and WRF-Chem only.
// The claim is therefore kept, but narrowed to exactly what was checked and
// supported by citations rather than left as an unverified assertion.
const fs = require("fs");
const C = require("./content_v7.js");
const S = C.sections;

const byHead = (t) => {
  const i = S.findIndex(s => (s.h1 || s.h2 || "") === t);
  if (i < 0) throw new Error("no section: " + t);
  return i;
};
function sub(head, from, to) {
  const s = S[byHead(head)];
  let hit = 0;
  s.p = s.p.map(t => { if (t.includes(from)) { hit++; return t.replace(from, to); } return t; });
  if (!hit) throw new Error("not found in " + head + ": " + from.slice(0, 70));
}

// ---- the NO2 precedent: add the second, more directly comparable study ----
sub("1 Introduction",
"For nitrogen dioxide, where the surface network is hourly and dense, TEMPO and TROPOMI columns have been compared with regulatory monitors directly (Acker et al., 2025).",
"For nitrogen dioxide, where the surface network is hourly and dense, TEMPO and TROPOMI columns have been compared with regulatory monitors directly, both against ground-based concentrations generally (Acker et al., 2025) and monitor by monitor across diurnal and seasonal cycles (Nawaz et al., 2025). No equivalent comparison exists for formaldehyde, whose surface network is neither hourly nor dense.");

// ---- the novelty claim, narrowed to what the search actually establishes ----
sub("1 Introduction",
"To our knowledge TEMPO HCHO has not yet been evaluated against routine surface air toxics measurements at daily or sub-daily resolution [[re-check before submission]].",
"Evaluations of TEMPO HCHO published to date compare it with other measurements of the column: with TROPOMI, with the Pandonia Global Network (Rawat et al., 2026), with NDACC Fourier transform infrared spectrometers and Pandora (Ortega et al., 2026), and with vertically integrated aircraft profiles; these are the comparisons listed in the mission's own validation report (NASA ASDC, 2026). To our knowledge TEMPO HCHO has not been evaluated against surface concentration measurements from routine monitoring networks at daily or sub-daily resolution.");

// ---- references ----
C.references.push(
"Nawaz, M. O., Huber, D. E., Kerr, G. H., Judd, L. M., Acker, S. J., and Goldberg, D. L.: A comparative analysis of TEMPO NO_{2} remote sensing with surface-level monitoring through diurnal and seasonal trends, meteorology, and monitor characteristics, J. Geophys. Res.-Atmos., 130, e2025JD043923, https://doi.org/10.1029/2025JD043923, 2025.",
"NASA ASDC: Validation and quality assessment of the TEMPO Level-2 trace gas products, NASA Langley Atmospheric Science Data Center, https://asdc.larc.nasa.gov/documents/tempo/TEMPO_validation_report_baseline_draft.pdf, last access: 14 September 2026, 2026. [[confirm the current version and its formal citation before submission]]"
);
C.references.sort((a, b) => a.localeCompare(b, "en"));

// ---- drafting notes ----
C.notes[1] = "Changes from v7: the novelty claim in the Introduction is resolved and its verification flag removed. A literature search on 14 September 2026 (Rawat et al. 2026 JGR; Ortega et al. 2026; Zhao et al. 2025 GRL; the NASA TEMPO Level-2 validation report; EPA's TEMPO validation collaboration page; the TEMPO science team presentation archive; and searches for TEMPO HCHO against AQS, NATTS, NCore and PAMS) found no evaluation of TEMPO HCHO against surface concentration measurements from routine monitoring networks. The mission's own validation report lists the HCHO comparisons as TROPOMI, the Pandonia Global Network, NDACC FTIR, vertically integrated aircraft profiles and WRF-Chem - no surface networks. The claim is therefore kept but narrowed to exactly that, and is now supported by citations rather than asserted. Nawaz et al. (2025), a monitor-by-monitor TEMPO NO_{2} comparison against surface monitors, is added as the closest methodological precedent alongside Acker et al. (2025).";
C.notes.splice(2, 0,
"WATCH BEFORE SUBMISSION: the closest work in progress is an August 2025 TEMPO science team presentation by Rawat, \"Leveraging observations of remotely sensed HCHO column to assess surface air quality\" - the same EPA-affiliated group as the Rawat et al. (2026) Pandonia assessment. No paper had appeared as of 14 September 2026. Re-run the search immediately before submitting and cite it if it has been published; it is the most likely source of overlap.");

const out = "// content_v8.js - generated by mkcontent8.js; do not edit by hand\n" +
  "module.exports = " + JSON.stringify(C, null, 1) + ";\n";
fs.writeFileSync("content_v8.js", out);
console.log("wrote content_v8.js:", out.length, "chars; refs:", C.references.length);
