// mkcontent15.js - content_v14.js -> content_v15.js
// The bootstrap intervals are now seeded per stratum, so they no longer depend
// on how many strata ran before them. Three limits move at the two decimals the
// text quotes; the point estimates and all other limits are unchanged.
const fs = require("fs");
const C = require("./content_v14.js");
const S = C.sections;
const byHead = (t) => {
  const i = S.findIndex(s => (s.h1 || s.h2 || "") === t);
  if (i < 0) throw new Error("no section: " + t);
  return i;
};
function sub(head, from, to) {
  const s = S[byHead(head)];
  let hit = 0;
  s.p = s.p.map(t => { if (t.includes(from)) { hit++; return t.replace(from, to); } return t; });
  if (!hit) throw new Error("not found in " + head + ": " + from.slice(0, 70));
}
const H = "4.11 Are the days TEMPO can observe representative?";

sub(H, "gives 0.51 µg m^{-3} nationally (0.42 to 0.61; 955 site-months at 100 monitors)",
       "gives 0.51 µg m^{-3} nationally (0.42 to 0.60; 955 site-months at 100 monitors)");
sub(H, "0.16 µg m^{-3} in winter (10 % of the seasonal median; 0.01 to 0.30)",
       "0.16 µg m^{-3} in winter (10 % of the seasonal median; 0.01 to 0.31)");
sub(H, "1.00 in summer (34 %; 0.82 to 1.18)",
       "1.00 in summer (34 %; 0.83 to 1.19)");

C.notes[1] = "Changes from v14: the site-cluster bootstrap is now seeded per stratum, so each interval depends only on its own data. Previously all strata drew from one RNG stream seeded once, which meant adding or suppressing a stratum shifted the confidence limits of every stratum computed after it - a reproducibility defect rather than a rounding one. Three limits move at the two decimals the text quotes (the national paired upper limit 0.61 to 0.60, winter upper 0.30 to 0.31, summer 0.82-1.18 to 0.83-1.19); every point estimate, the fixed-effects results and all other limits are unchanged.";

const out = "// content_v15.js - generated by mkcontent15.js; do not edit by hand\n" +
  "module.exports = " + JSON.stringify(C, null, 1) + ";\n";
fs.writeFileSync("content_v15.js", out);
console.log("wrote content_v15.js");
