// mkcontent7.js - content_v6.js -> content_v7.js, third review pass
// 1. Sect. 2.1 still assumed local-condition reporting, contradicting Sect. 3.2 (stale text)
// 2. "this is exact" in Sect. 3.7 overstated: window bounds are exact, granule-midpoint
//    assignment is not
// 3. abstract: "carbonyl" -> "formaldehyde" (parameter 43502 is what was retrieved)
// 4. abstract: 102 + 40 + 4 > 123 reads as an error unless the categories are non-exclusive
//    (23 sites sample both 24 h and 8 h)
const fs = require("fs");
const C = require("./content_v6.js");
const S = C.sections;

const byHead = (t) => {
  const i = S.findIndex(s => (s.h1 || s.h2 || "") === t);
  if (i < 0) throw new Error("no section: " + t);
  return i;
};
function sub(head, from, to) {
  const s = S[byHead(head)];
  let hit = 0;
  s.p = s.p.map(t => { if (t.includes(from)) { hit++; return t.replace(from, to); } return t; });
  if (!hit) throw new Error("not found in " + head + ": " + from.slice(0, 70));
}

// ---------------------------------------------------------------- 1. stale assumption
sub("2.1 Colorado Air Toxics Trends network (24 h samples; case study)",
"We assume that concentrations are reported at local temperature and pressure [[confirm with CDPHE]].",
"Concentrations are reported at standard conditions (25 °C, 1 atm), as established by comparison with the corresponding AQS mixing ratios for the same samples (Sect. 3.2).");

// ---------------------------------------------------------------- 2. "exact" overstated
sub("3.7 The national comparison",
"Because every AQS sampling window begins on the hour, this is exact.",
"Because every AQS sampling window begins on the hour, the window boundaries are known exactly and the assignment is unambiguous at hourly resolution; the granule midpoint can still differ from the time TEMPO viewed an individual site by tens of minutes, which the hourly assignment does not resolve.");

// ---------------------------------------------------------------- 3 + 4. abstract
const absBefore = C.abstract[0];
C.abstract[0] = C.abstract[0].replace(
"We compare TEMPO Level 3 version 4 HCHO columns with all valid integrated carbonyl samples reported to the United States Air Quality System (AQS) in 2024–2025 — 16 383 samples at 123 sites in 37 states, of which 102 sites sample for 24 h, 40 for 8 h and 4 for 3 h — and",
"We compare TEMPO Level 3 version 4 HCHO columns with all valid integrated formaldehyde samples reported to the United States Air Quality System (AQS) in 2024–2025 — 16 383 samples at 123 sites in 37 states, including 24 h samples from 102 sites, 8 h samples from 40 sites and 3 h samples from four sites — and"
);
if (C.abstract[0] === absBefore) throw new Error("abstract replacement did not match");

// ---------------------------------------------------------------- the duration confound, and where its fix lies
sub("5.7 Implications for air toxics monitoring and limitations",
"nationally, the sub-daily arm rests on 40 sites with one 8 h sampling pattern and four sites with 3 h samples, two of them the Colorado pair, so the evidence that morning sampling can work rests on two Californian sites in one air basin.",
"nationally, the sub-daily arm rests on 40 sites with one 8 h sampling pattern and four sites with 3 h samples, two of them the Colorado pair, so the evidence that morning sampling can work rests on two Californian sites in one air basin. Sample duration and time of day are also confounded across the network as a whole, because each duration is associated with a different set of sites and sampling programmes; we therefore compare windows only among samples of the same duration. Twenty-three sites do report both 24 h and 8 h formaldehyde, so a within-site comparison of duration is possible in principle and would be the natural way to separate the two.");

// ---------------------------------------------------------------- notes
C.notes[1] = "Changes from v6, all in response to the third review pass: Sect. 2.1 no longer assumes local-condition reporting - it was stale text contradicting the AQS cross-check in Sect. 3.2, and is the one thing in v6 that could have confused a reviewer; \"this is exact\" in Sect. 3.7 now distinguishes the exactly known sampling-window bounds from the granule-midpoint assignment, which the limitations already said can be off by tens of minutes; the abstract says \"formaldehyde samples\" rather than \"carbonyl samples\" (parameter 43502 is what was retrieved) and states the per-duration site counts non-exclusively, since 102 + 40 + 4 exceeds 123 - 23 sites report both 24 h and 8 h; and Sect. 5.7 now states the duration/time-of-day confound explicitly and notes that those 23 sites would be the way to break it.";

const out = "// content_v7.js - generated by mkcontent7.js; do not edit by hand\n" +
  "module.exports = " + JSON.stringify(C, null, 1) + ";\n";
fs.writeFileSync("content_v7.js", out);
console.log("wrote content_v7.js:", out.length, "chars");
