// mkcontent12.js - content_v11.js -> content_v12.js
// Adds the site map as Figure 1 and renumbers every figure and cross-reference.
// Supplementary figures (S1-S4) and Table S1 are untouched.
const fs = require("fs");
const C = require("./content_v11.js");
const S = C.sections;

const byHead = (t) => {
  const i = S.findIndex(s => (s.h1 || s.h2 || "") === t);
  if (i < 0) throw new Error("no section: " + t);
  return i;
};
function sub(head, from, to) {
  const s = S[byHead(head)];
  let hit = 0;
  s.p = s.p.map(t => { if (t.includes(from)) { hit++; return t.replace(from, to); } return t; });
  if (!hit) throw new Error("not found in " + head + ": " + from.slice(0, 70));
}

// ---------------------------------------------------------------- 1. renumber
// "Fig. N", "Figs. N and M", "Figure N" -> N+1. An "S" before the digit
// (Fig. S2, Figure S1) never matches \d, so supplementary references are left
// alone. String.replace scans its input once and never re-examines what it has
// written, so one ascending pass cannot bump the same number twice.
const RE = /\b(Figs?\.|Figure)(\s+)(\d+)((\s+and\s+)(\d+))?/g;
let renumbered = 0;
function bump(t) {
  if (typeof t !== "string") return t;
  return t.replace(RE, (m, word, sp, n1, tail, andWord, n2) => {
    renumbered++;
    if (n2 === undefined) return word + sp + (Number(n1) + 1);
    return word + sp + (Number(n1) + 1) + andWord + (Number(n2) + 1);
  });
}

function walkAll(fn) {
  C.abstract = C.abstract.map(fn);
  C.shortSummary = fn(C.shortSummary);
  S.forEach(s => {
    if (s.p) s.p = s.p.map(fn);
    if (s.fig) s.fig.caption = fn(s.fig.caption);
    if (s.table) {
      s.table.caption = fn(s.table.caption);
      if (s.table.notes) s.table.notes = fn(s.table.notes);
      s.table.header = s.table.header.map(fn);
      s.table.rows = s.table.rows.map(r => r.map(fn));
    }
  });
  C.supplement.forEach(f => {
    if (f.caption) f.caption = fn(f.caption);
    if (f.tableS) {
      f.tableS.caption = fn(f.tableS.caption);
      if (f.tableS.notes) f.tableS.notes = fn(f.tableS.notes);
    }
  });
}
walkAll(bump);
console.log("renumbered", renumbered, "figure references");

// ---------------------------------------------------------------- 2. insert Figure 1
const siteMap = { fig: {
  file: "fig0_site_map.png", w: 2280, h: 1620,
  caption: "Figure 1. The Colorado case-study sites: seven COATTS sites sampling 24 h integrated carbonyls (circles) and two COOPs sites sampling 3 h (triangles), over terrain and county boundaries. Inset: the 123 sites across the contiguous United States that reported formaldehyde to AQS in 2024–2025, coloured by sample duration, with Colorado outlined. Elevation is from AWS terrain tiles; boundaries are US Census cartographic files."
}};
// between the Sect. 2.1 text and Table 1, where the sites are first named
S.splice(byHead("2.1 Colorado Air Toxics Trends network (24 h samples; case study)") + 1, 0, siteMap);

// ---------------------------------------------------------------- 3. point the text at it
sub("2.1 Colorado Air Toxics Trends network (24 h samples; case study)",
"We used formaldehyde from the 2024 and 2025 annual data packets for seven sites (Table 1).",
"We used formaldehyde from the 2024 and 2025 annual data packets for seven sites (Table 1, Fig. 1).");

sub("2.2 COOPs ozone-precursor sites (3 h samples; case study)",
"Two ozone-precursor sites, Chatfield State Park in Douglas County (CHCO) and Platteville in Weld County (PVCO), belong to CDPHE's COOPs network",
"Two ozone-precursor sites, Chatfield State Park in Douglas County (CHCO) and Platteville in Weld County (PVCO) (Fig. 1), belong to CDPHE's COOPs network");

sub("2.3 National formaldehyde monitors (EPA Air Quality System)",
"sites in 37 states (Table 5).",
"sites in 37 states (Table 5; their distribution is shown in the inset of Fig. 1).");

// ---------------------------------------------------------------- 4. notes
C.notes = C.notes.filter(n => !/^Add Figure 1: site map/.test(n));
C.notes[1] = "Changes from v11: the Colorado site map is added as Figure 1 and every figure and cross-reference is renumbered, so the former Figs. 1-11 are now Figs. 2-12; supplementary figures S1-S4 and Table S1 are unchanged. The map is produced by R/14_site_map.R from a cached AWS terrain DEM and US Census cartographic boundary files, and it checks its nine site coordinates against the processed data before drawing. Sects. 2.1, 2.2 and 2.3 now point at it.";

const out = "// content_v12.js - generated by mkcontent12.js; do not edit by hand\n" +
  "module.exports = " + JSON.stringify(C, null, 1) + ";\n";
fs.writeFileSync("content_v12.js", out);
console.log("wrote content_v12.js:", out.length, "chars");
