// mkcontent5.js - content_v4.js -> content_v5.js, applying the review
// (1) boundary-layer mechanism softened from conclusion to hypothesis
// (2) noise attribution stated as the upper bound it is; Colorado leads, national corroborates
// (3) Benjamini-Hochberg FDR counts for the 141 site-level tests
// (4) universal language ("at every site") removed
// (5) H_eff interpretation tightened
// (6) Discussion repetition trimmed, abstract slimmed
const fs = require("fs");
const C = require("./content_v4.js");
const S = C.sections;

const byHead = (t) => {
  const i = S.findIndex(s => (s.h1 || s.h2 || "") === t);
  if (i < 0) throw new Error("no section: " + t);
  return i;
};
// replace an exact substring inside a section's paragraphs, asserting it was found
function sub(head, from, to) {
  const s = S[byHead(head)];
  let hit = 0;
  s.p = s.p.map(t => { if (t.includes(from)) { hit++; return t.replace(from, to); } return t; });
  if (!hit) throw new Error("not found in " + head + ": " + from.slice(0, 70));
}
const setP = (head, ps) => { S[byHead(head)].p = ps; };

// ============================================================ 1. abstract
C.abstract = [
"Formaldehyde (HCHO) is a carcinogenic hazardous air pollutant and a leading contributor to estimated cancer risk from outdoor air toxics in the United States. The geostationary Tropospheric Emissions: Monitoring of Pollution (TEMPO) instrument retrieves HCHO columns hourly over North America, but evaluations of these retrievals have relied on column measurements, and comparisons of satellite HCHO with routine surface monitoring have been limited to seasonal means from polar-orbiting instruments. We compare TEMPO Level 3 version 4 HCHO columns with all valid integrated carbonyl samples reported to the United States Air Quality System (AQS) in 2024–2025 — 16 383 samples at 123 sites in 37 states, of which 102 sites sample for 24 h, 40 for 8 h and 4 for 3 h — and examine Colorado's air toxics network in detail as a case study, using the state's own data packets and a classification of every sample period by wildfire smoke.",
"Nationally, 70 % of 24 h samples had at least one TEMPO scan passing quality screening. The pooled correlation between the daily mean column and 24 h surface HCHO was 0.42 (n = 6106) and 0.40 after removing site and calendar-month means, which isolates day-to-day covariation. The central result is how unevenly that skill is distributed: at individual 24 h monitors the day-to-day correlation had a median of 0.48, an interquartile range of 0.27–0.59 and a range from −0.24 to 0.89. There is useful day-to-day information at most routine monitors and none at some, and no single satellite-to-surface relationship that can safely be assumed at a site that has not been checked.",
"Agreement improved consistently with spatial averaging, from single 0.02° cells to 5 × 5 cell blocks, both nationally and in Colorado. In Colorado, differences between successive scans bound the random retrieval noise at about half of the day-to-day variance of a 3 × 3 daily column, implying a ceiling near 0.7 on the attainable correlation; correcting for it leaves the correlation unchanged across block sizes, so averaging appears to help mainly by reducing noise rather than by improving spatial representativeness. The column's seasonal amplitude exceeded the surface amplitude (3.0-fold against 1.7-fold from winter to summer in Colorado), and the effective mixing height implied by the column-to-surface ratio was 0.83 km in Colorado, about half the modelled boundary layer depth, against 1.09 km nationally, close to it.",
"The hour at which a sample is collected mattered more than its length. At the two California sites that sample five 3 h windows a day, day-to-day agreement was as strong in the 05:00–08:00 window (r = 0.44) as at midday (0.41) and absent in the late afternoon (0.17); at Colorado's two 3 h sites, which sample only 06:00–09:00 MST, agreement was absent during the sampling window (0.11) and strongest three hours after it (0.40). Across the 40 sites sampling 8 h blocks, the midday block outperformed the morning block (0.42 against 0.34). There is therefore no universal lag between sampling and the best-matching satellite window; the window that matches best differs between sampling regimes and, in our data, between regions. The pattern is consistent with the deepening of the morning mixed layer making surface concentrations representative of a larger fraction of the column, at an hour that differs from place to place, though our observations constrain the timing rather than the mechanism. Wildfire smoke, classified in Colorado from NOAA Hazard Mapping System analyses, raised both surface and column HCHO within season, did not reduce TEMPO coverage, and contributed to day-to-day agreement. TEMPO captures the seasonal cycle and regional episodes seen by surface air toxics monitors across the country; its day-to-day skill at an individual monitor is moderate, strongly site dependent, and governed by retrieval noise and by when the satellite looks relative to when the air was sampled."
];

C.shortSummary =
"Satellites now measure formaldehyde, a cancer-causing air pollutant, every daylight hour over North America. We compared these measurements with every routine surface sample collected across the United States in 2024-2025, at 123 sites, and looked at Colorado's network in detail. The satellite tracked day-to-day changes at most monitors but at some not at all, and how well it did depended on where the monitor was and on what time of day the sample was collected.";

// ============================================================ 2. FDR in the methods
sub("3.3 Statistical analysis",
"Their p-values do not account for the degrees of freedom used by the monthly means and are therefore optimistic.",
"Their p-values do not account for the degrees of freedom used by the monthly means and are therefore optimistic. Where correlations are reported for many sites at once, we give both the number significant at a nominal p < 0.05 and the number surviving a Benjamini-Hochberg false-discovery-rate correction applied across that family of tests; the distribution of the correlations themselves is more informative than either count.");

// ============================================================ 3. noise as an upper bound (4.8)
sub("4.8 What limits day-to-day agreement",
"That is 48 % of the variance of the within-month column anomalies pooled over sites, so noise alone would cap the day-to-day correlation at about 0.72. The observed 0.30 is well below that cap.",
"That is 48 % of the variance of the within-month column anomalies pooled over sites, so noise alone would cap the day-to-day correlation at about 0.72. Because the column genuinely changes between successive scans, this estimate is an upper bound on the random scan-to-scan noise, and correspondingly a lower bound on the ceiling; it is also blind to errors that persist through a day, which would lower the ceiling further. The observed 0.30 is well below the cap either way.");

// ============================================================ 4. Results 4.9: FDR, H_eff, noise wording
sub("4.9 Agreement across the national network",
"Median H_{eff} across the 24 h sites was 1.09 km against a median TEMPO PBL height of 1.04 km, so nationally the column and the modelled mixed layer are consistent with a well-mixed HCHO profile; Colorado's H_{eff} of about half the PBL height is not the general case.",
"Median H_{eff} across the 24 h sites was 1.09 km against a median TEMPO PBL height of 1.04 km, so nationally the two medians are close, whereas in Colorado H_{eff} is about half the modelled boundary layer depth. Colorado is therefore unusual in this respect. The agreement of the two medians nationally is not by itself evidence of a well-mixed HCHO profile: H_{eff} also absorbs retrieval bias, the free-tropospheric column, error in the surface measurement and the mismatch between a 24 h sample and daytime satellite sampling (Sect. 3.2).");

sub("4.9 Agreement across the national network",
"Of 141 site–duration combinations with at least 10 matched samples, 122 had a significant positive correlation.",
"Of 141 site–duration combinations with at least 10 matched samples, 122 had a positive correlation significant at a nominal p < 0.05, and 121 survive a Benjamini-Hochberg correction across the 141 tests; for the day-to-day correlations the counts are 103 and 102. The counts are robust to the correction, but the distribution is the more informative quantity.");

sub("4.9 Agreement across the national network",
"and a stricter cloud threshold of 0.1 helps slightly (0.44 at 3 × 3) at the cost of 9 % of the samples — the signature of averaging down noise rather than of a change in what is being measured.",
"and a stricter cloud threshold of 0.1 helps slightly (0.44 at 3 × 3) at the cost of 9 % of the samples. On its own this gradient is equally consistent with averaging down noise and with larger blocks being more representative; what distinguishes the two is the Colorado noise analysis (Sect. 4.8), in which the noise-corrected correlation is the same at every block size. The national gradient corroborates that reading rather than establishing it.");

// ============================================================ 5. Results 4.10: no universal rule
sub("4.10 Sampling window and time of day across the network",
"In other words, morning sampling is not intrinsically hard to match to a satellite column. At the California sites, samples collected between 05:00 and 08:00 local time agree with the column measured during those same hours. It is at Colorado's two Front Range sites, sampling one hour later in the day, that the sampling window fails and the window three hours later succeeds.",
"In other words, morning sampling is not intrinsically hard to match to a satellite column. At the California sites, samples collected between 05:00 and 08:00 local time agree with the column measured during those same hours. It is at Colorado's two Front Range sites, sampling one hour later in the day, that the sampling window fails and the window three hours later succeeds. What these observations establish is a negative: there is no single lag, and no single clock hour, that gives the best match everywhere. Which window is best at a given monitor is not predictable from the sampling schedule alone.");

// ============================================================ 6. Discussion 5.2: Colorado leads, national corroborates
setP("5.2 Noise and spatial averaging", [
"The consistent gain in agreement from single cells to 5 × 5 blocks, together with the better performance of all-day means than midday means, suggests that random noise in individual retrievals limits single-cell comparisons more than spatial mismatch does. The Colorado noise analysis (Sect. 4.8) is what allows the two to be separated: successive-scan differences bound the random noise at about half the day-to-day variance of the 3 × 3 daily column, implying a ceiling near 0.7, and the noise-corrected correlation is then the same at every block size. That invariance is the direct evidence that averaging helps by reducing noise rather than by capturing a more representative area. The national block-size gradient, and the weaker agreement at the lowest-concentration sites where a fixed noise consumes the largest share of the variance (Sect. 4.9), corroborate it across a much wider range of conditions but could not establish it alone.",
"Two caveats belong with that conclusion. The noise estimate is an upper bound on random scan-to-scan error and says nothing about errors that persist through a day, so the ceiling is correspondingly uncertain; and the reported per-cell uncertainties, taken at face value, are larger still and would leave no room for the correlations we observe, which suggests they overstate the random error of the scans they flag as most uncertain. The cloud fraction threshold mattered much less than block size, particularly for all-day means, suggesting that residual cloud contamination is not the dominant error source for daily means, although stricter screening helped when fewer (midday) scans were averaged.",
"For comparisons with 24 h integrated samples, averaging over roughly 10 km and over all daylight scans is a reasonable default. Near strong local sources, however, larger blocks dilute local enhancements, so the appropriate averaging scale depends on whether the application targets regional or near-source concentrations. Where agreement stays far below the noise ceiling, as at Grand Junction, the explanation must lie with the monitor's representativeness or with the vertical structure above it rather than with retrieval noise; neither terrain inside the block nor a winter effect accounts for it, and identifying what does would need meteorological analysis beyond this study."
]);

// ============================================================ 7. Discussion 5.3: H_eff hedging
sub("5.3 Interpreting the column–surface relationship",
"That Colorado's H_{eff} is low relative to the national value is consistent with its monitors sitting at high elevation in semi-arid terrain, where the modelled boundary layer is deep in summer while HCHO remains concentrated near its sources.",
"Why Colorado's H_{eff} is low relative to the national value we can only suggest: its monitors sit at high elevation in semi-arid terrain, where the modelled boundary layer is deep in summer while HCHO may remain concentrated near its sources [[hypothesis — not tested here]].");

// ============================================================ 8. Discussion 5.4: mechanism as hypothesis
setP("5.4 Sampling time, mixing, and why the lag that matters is site dependent", [
"The Colorado 3 h samples show that the comparison depends on when TEMPO looks relative to when the air was sampled, and that the best match is not the sampling window itself. Samples collected between 06:00 and 09:00 MST correlated poorly with the column measured at the same time, well with the column three hours later, and not at all with the column six hours later. The national sub-daily sites show that this is not a general property of morning samples. At the two California sites, samples collected between 05:00 and 08:00 local time correlate with the column measured during those same hours as well as midday samples do with the midday column. The firm conclusion is a negative one: there is no universal lag, and the window that matches best differs between sampling regimes and, in our data, between regions.",
"Three lines of evidence argue against the simplest alternative, that early-morning retrievals are too poor to be useful. At the 24 h sites, where the sample spans the whole day, early scans track the surface as well as later scans (Sect. 4.8). Scan-to-scan noise and reported per-cell uncertainties are similar in the two windows. And the California result settles it directly: an early-morning window that carries no day-to-day information at two Colorado sites carries as much as a midday window at two Californian ones, even though the Californian window begins an hour earlier in the day.",
"A boundary layer explanation is consistent with these observations, and we offer it as a hypothesis rather than a demonstrated mechanism. As the morning mixed layer deepens, a surface concentration becomes representative of a larger fraction of the column, so the two measurements should agree more closely once mixing has developed and less closely while the surface layer is shallow and stable. On the Front Range between 06:00 and 09:00 the surface layer is shallow, so a surface sample reflects overnight accumulation in a thin layer while the column at that hour is dominated by the residual layer and the free troposphere; by 09:00–12:00 the median TEMPO boundary layer height has tripled and agreement is at its strongest; by 12:00–15:00, with the mixed layer deeper still, agreement is lost again, which photochemical production, entrainment and horizontal transport could each explain. We have not followed an air parcel, measured a vertical profile, or observed the mixing itself, so these are interpretations of a timing result, not measurements of a process. On this reading the window that matches best is set by how quickly the local morning boundary layer develops.",
"The contrasts within our data are ordered as that reading would predict. Chatfield State Park lies at the foot of the Front Range, where nocturnal drainage flow and a strongly stable morning layer are expected; its sampling-window correlation is essentially zero and the +3 h window is strong. Platteville sits on the open plains of the Denver–Julesburg basin, where morning decoupling should be weaker and the surrounding region is more uniform, and there the sampling window and the +3 h window perform about equally (0.55 and 0.46 for the whole record). Bakersfield and Clovis lie on the floor of the San Joaquin Valley and sample an hour earlier still, and there the sampling window works. Four sites is a thin basis for a mechanism, and the two Californian ones are 80 km apart in a single air basin, so they are closer to one independent test than two. Co-located boundary layer measurements, or a lag analysis stratified by a stability index, would be needed to test the explanation properly [[consider a stability-stratified reanalysis of the 8 h sites]].",
"The 8 h sites make a related point on a coarser time grid and with 40 sites rather than four. The block beginning at 12:00 local time, which lies wholly within the well-mixed afternoon, agrees better than the block beginning at 04:00, which spends its first hours in the stable morning layer and its remaining hours after mixing. The difference is real but modest (day-to-day correlations of 0.42 and 0.34), as expected when a window is long enough to average across the transition. Because every one of these sites samples the same three blocks, this comparison holds the schedule fixed and varies only the time of day, which the 3 h comparison cannot do.",
"The practical implication is therefore not “match the satellite to the sampling window”, nor “add three hours”, but that the best match has to be determined rather than assumed. For 24 h samples the all-day mean is a reasonable compromise, as our results show. For programmes designing sub-daily carbonyl sampling, a window centred on the middle of the day is likely to be the more robust default for comparison with a geostationary column, although the optimal window remains site dependent and our evidence for midday comes from aggregate behaviour at the 8 h sites and from two Californian monitors. Whatever the choice, the metadata matter: without the sample start times recorded in AQS we would have had the Colorado sampling window backwards, and would have reported the best-fitting window as the sampling window."
]);

// ============================================================ 9. Discussion 5.6 trimmed (~40 %)
setP("5.6 Colorado in national context, and what a national comparison adds", [
"Taking the national network as the reference changes how the Colorado results should be read. Colorado's pooled correlation of 0.56 is higher than the national 0.42, but the two are not measuring the same thing: a correlation pooled over sites mixes agreement within sites with agreement about the differences between them, in proportions that depend on how alike the sites are. Colorado's pooled value is close to the median correlation at its individual sites (0.53) because its seven monitors share one regional seasonal cycle, whereas the national pooled value falls well below the median at individual sites (0.42 against 0.64) because monitors in different climates have different column-to-surface ratios. The day-to-day correlation means the same thing in both, and by that measure Colorado sits below the national norm (0.30 pooled and 0.35 as a median over its AQS sites, against 0.40 and 0.48 nationally). A single-state study could not have known which of these it was seeing — and the same caution applies to any evaluation carried out at one site or in one region.",
"The national arm also supplies the test each of the case study's two explanations needs and Colorado alone cannot provide: a block-size gradient that holds across the country, with the weakest agreement where concentrations are lowest (Sect. 5.2), and a set of monitors whose morning samples do track the column, which is what rules out morning retrievals being the problem (Sect. 5.4). Beyond that, the comparison places these results beside the only previous study of surface and satellite HCHO over the United States. Wang et al. (2022) compared seasonal means at 45 AQS sites with OMI columns for 2006–2015 and found regional correlations of 0.56–0.87 in summer, weak or negative correlations in winter, and a seasonal amplitude 20–100 % larger in the column than at the surface. Our seasonal findings reproduce theirs, but the comparison no longer has to be seasonal: 70 % of individual 24 h samples across the country now carry a usable observation, so the same networks can be used to ask when, and at which monitors, a satellite tracks day-to-day variation."
]);

// ============================================================ 10. limitations: multiplicity
sub("5.7 Implications for air toxics monitoring and limitations",
"Finally, many correlations were computed across sites, seasons and screening variants without correction for multiple comparisons, and anomaly p-values are optimistic; the site-level significance counts in Sect. 4.9 should be read with that in mind.",
"Finally, anomaly p-values are optimistic because they do not account for the degrees of freedom spent on the site-month means, and correlations were computed across many sites, seasons and screening variants. The site-level counts in Sect. 4.9 are corrected for multiplicity within that family of tests and change by one, but no correction addresses the optimism of the individual p-values, and the distribution of the correlations should carry more weight than any count of them.");

// ============================================================ 11. Conclusions
setP("6 Conclusions", [
"We evaluated TEMPO Level 3 V04 HCHO columns against all valid integrated formaldehyde samples reported to EPA's Air Quality System in 2024–2025 — 16 383 samples at 123 sites in 37 states — with Colorado's air toxics and ozone-precursor network examined in detail as a case study. Nationally, a screened TEMPO observation was available for 70 % of 24 h samples; the daily column and the 24 h surface concentration correlated at 0.42, and at 0.40 once the shared seasonal cycle and the differences between sites were removed. The distribution behind those pooled numbers is the main result: at individual 24 h monitors the day-to-day correlation had a median of 0.48, an interquartile range of 0.27–0.59 and a range from −0.24 to 0.89. TEMPO carries usable day-to-day information at most routine air toxics monitors and none at some, and there is no network-wide satellite-to-surface relationship that can safely be assumed at a monitor that has not been checked.",
"Agreement was weakest where concentrations were lowest, and it improved with spatial averaging everywhere. In Colorado, where the retrieval noise could be estimated from successive scans, that noise accounts for at most about half the day-to-day variance of a 3 × 3 daily column, implying a ceiling near 0.7; correcting for it leaves the correlation unchanged across block sizes, which indicates that averaging helps mainly by reducing noise rather than by improving spatial representativeness.",
"The hour at which a sample is collected matters more than its length or the precision of the match. Colorado's 3 h samples, whose 06:00–09:00 MST window is recorded in AQS, agree with TEMPO not during sampling (r = 0.12) but three hours later (0.40), and not at all after six hours (0.03). The national sites show that this lag is not a universal one: at two California sites the 05:00–08:00 window agrees with the column measured in that same window as well as midday sampling does, and across 40 sites sampling 8 h blocks the midday block outperforms the morning block. These observations are consistent with the deepening of the morning mixed layer making a surface sample representative of a larger fraction of the column, at an hour that differs between sites, but they constrain the timing of the best match rather than demonstrating the mechanism behind it. In the Colorado case study, wildfire smoke raised both surface and column HCHO within season and contributed to day-to-day agreement, most clearly in that same post-sampling window.",
"TEMPO provides useful seasonal and episodic context for air toxics monitoring across the United States, and its value for tracking day-to-day variation is greatest when observations are averaged spatially, when the monitor's concentrations are not close to the retrieval noise floor, and when the satellite is matched to the hours in which the sampled air is well mixed. Which of those conditions hold, and which matching window is best, are now questions that can be answered monitor by monitor rather than assumed from a network average."
]);

// ============================================================ 12. 2.3: "all valid"
sub("2.3 National formaldehyde monitors (EPA Air Quality System)",
"We retrieved every formaldehyde sample reported to AQS for 1 January 2024 to 31 December 2025: 16 383 samples at 123 sites in 37 states (Table 5).",
"We retrieved every formaldehyde sample reported to AQS for 1 January 2024 to 31 December 2025 and retained all valid records: 16 383 samples at 123 sites in 37 states (Table 5).");

// ============================================================ 13. drafting notes
C.notes = [
"Numbers come from the pipeline runs of 11-14 September 2026, analysis code at commit 14a1257 (github.com/pdez90/coatts_hcho), plus the Benjamini-Hochberg counts added to step 13 afterwards. Later commits change manuscript text only and no number. Re-check every number if the pipeline is rerun.",
"Changes from v4, all in response to review: the boundary-layer explanation is now offered as a hypothesis rather than a mechanism throughout (abstract, Sects. 4.10, 5.4, Conclusions) - we constrain the timing of the best match, not the process behind it; the retrieval-noise estimate is stated as the upper bound the method makes it, with the Colorado noise-corrected invariance leading and the national block-size gradient corroborating rather than establishing (Sects. 4.8, 4.9, 5.2, Conclusions); site-level significance counts now carry a Benjamini-Hochberg correction (121 of 141 whole-period, 102 of 141 day-to-day; Sects. 3.3, 4.9, 5.7) and the distribution is given precedence over the counts; \"at every site\" and similar universal claims removed (Sect. 5.4); the H_{eff} interpretation is tightened so that equal medians are not read as a well-mixed profile (Sects. 4.9, 5.3); Sect. 5.6 cut by about 40 % and Sect. 5.2 restructured; the abstract drops the significance count and the packets-vs-AQS cross-check in favour of the distribution of site-level correlations; \"every sample\" is now \"all valid samples\".",
"Still to settle with CDPHE: what COOPs stands for; the two samples stamped 23:59 on 12 June 2025 (excluded here; AQS shows no such stamps); and how to cite CDPHE's answers (personal communication?). The reporting-conditions question is settled from AQS and needs no further reply.",
"Author list, affiliations, author contributions, acknowledgements and funding are placeholders. Consider inviting CDPHE ATOPs staff as co-authors.",
"Add Figure 1: site map of the Colorado sites (seven COATTS sites and the two COOPs sites over terrain and county outlines). Fig. 9 shows the national sites. Current Figs. 1-11 will renumber to 2-12.",
"BEFORE SUBMISSION, in order: (1) run the literature search behind the novelty claim in the Introduction - it is the one highlighted statement that could sink the framing; (2) move the text into the Copernicus Word template; (3) archive the code on Zenodo and cite its DOI; (4) decide whether to deposit the matched datasets; (5) complete the Zoogman et al. (2017) author list; (6) confirm the TEMPO dataset citation on the DOI landing page; (7) add the Ortega et al. site-specific Boulder values and the Rawat et al. high-column bias.",
"Yellow-highlighted text marks statements to verify or decisions to make."
];

const out = "// content_v5.js - generated by mkcontent5.js; do not edit by hand\n" +
  "module.exports = " + JSON.stringify(C, null, 1) + ";\n";
fs.writeFileSync("content_v5.js", out);
console.log("wrote content_v5.js:", out.length, "chars;", C.sections.length, "blocks");

// ============================================================ 14. trim pass
// Hedging (items 1-2 above) adds words; the review also asked for less repetition.
// Cut where sections restate Results rather than where they qualify claims.

// 5.4: compress the "not bad morning retrievals" argument (it restates 4.8/4.10)
// and the 8 h paragraph (restates 4.10), keeping every hedge.
sub("5.4 Sampling time, mixing, and why the lag that matters is site dependent",
"Three lines of evidence argue against the simplest alternative, that early-morning retrievals are too poor to be useful. At the 24 h sites, where the sample spans the whole day, early scans track the surface as well as later scans (Sect. 4.8). Scan-to-scan noise and reported per-cell uncertainties are similar in the two windows. And the California result settles it directly: an early-morning window that carries no day-to-day information at two Colorado sites carries as much as a midday window at two Californian ones, even though the Californian window begins an hour earlier in the day.",
"The simplest alternative, that early-morning retrievals are too poor to be useful, does not survive the California result: an early-morning window that carries no day-to-day information at two Colorado sites carries as much as a midday window at two Californian ones, which begin sampling an hour earlier still. The 24 h control and the scan-noise comparison (Sect. 4.8) point the same way.");

sub("5.4 Sampling time, mixing, and why the lag that matters is site dependent",
"The 8 h sites make a related point on a coarser time grid and with 40 sites rather than four. The block beginning at 12:00 local time, which lies wholly within the well-mixed afternoon, agrees better than the block beginning at 04:00, which spends its first hours in the stable morning layer and its remaining hours after mixing. The difference is real but modest (day-to-day correlations of 0.42 and 0.34), as expected when a window is long enough to average across the transition. Because every one of these sites samples the same three blocks, this comparison holds the schedule fixed and varies only the time of day, which the 3 h comparison cannot do.",
"The 8 h sites make a related point with 40 monitors rather than four, and every one of them samples the same three blocks, so the comparison holds the schedule fixed and varies only the time of day — which the 3 h comparison cannot do. The midday block, wholly within the well-mixed afternoon, agrees better than the 04:00 block, which spends its first hours in the stable morning layer; the difference is real but modest (0.42 against 0.34), as expected when a window is long enough to average across the transition.");

// 5.6: the review asked for ~40 %; cut the restatement of 4.9 and of Wang's numbers
setP("5.6 Colorado in national context, and what a national comparison adds", [
"Taking the national network as the reference changes how the Colorado results should be read. Colorado's pooled correlation of 0.56 exceeds the national 0.42, but the two do not measure the same thing: a correlation pooled over sites mixes agreement within sites with agreement about the differences between them, in proportions that depend on how alike the sites are. Colorado's pooled value is close to the median at its own sites (0.53) because its seven monitors share one regional seasonal cycle; the national value falls well below it (0.42 against 0.64) because monitors in different climates have different column-to-surface ratios. The day-to-day correlation means the same thing in both, and by that measure Colorado sits below the national norm. A single-state study could not have known which of these it was seeing, and the same caution applies to any evaluation carried out in one region.",
"The national arm also supplies the two tests Colorado alone cannot: a block-size gradient that holds across the country, weakest where concentrations are lowest (Sect. 5.2), and a set of monitors whose morning samples do track the column, which is what rules out morning retrievals being the problem (Sect. 5.4). It also updates the only previous comparison of surface and satellite HCHO over the United States: Wang et al. (2022) matched seasonal means at 45 AQS sites to OMI columns and found agreement in summer but not winter, with a larger seasonal amplitude in the column than at the surface. Our seasonal findings reproduce theirs, but the comparison no longer has to be seasonal — 70 % of individual 24 h samples now carry a usable observation, so the same networks can be asked when, and at which monitors, a satellite tracks day-to-day variation."
]);

// Conclusions: three findings plus a closing sentence, not four paragraphs
setP("6 Conclusions", [
"We evaluated TEMPO Level 3 V04 HCHO columns against all valid integrated formaldehyde samples reported to EPA's Air Quality System in 2024–2025 — 16 383 samples at 123 sites in 37 states — with Colorado's air toxics and ozone-precursor network examined in detail as a case study. Nationally, a screened TEMPO observation was available for 70 % of 24 h samples; the daily column and the 24 h surface concentration correlated at 0.42, and at 0.40 once the shared seasonal cycle and the differences between sites were removed. The distribution behind those pooled numbers is the main result: at individual 24 h monitors the day-to-day correlation had a median of 0.48, an interquartile range of 0.27–0.59 and a range from −0.24 to 0.89. TEMPO carries usable day-to-day information at most routine air toxics monitors and none at some, and there is no network-wide satellite-to-surface relationship that can safely be assumed at a monitor that has not been checked.",
"Agreement was weakest where concentrations were lowest and improved with spatial averaging everywhere. In Colorado, where the retrieval noise could be estimated from successive scans, that noise accounts for at most about half the day-to-day variance of a 3 × 3 daily column, implying a ceiling near 0.7; correcting for it leaves the correlation unchanged across block sizes, which indicates that averaging helps mainly by reducing noise rather than by improving spatial representativeness.",
"The hour at which a sample is collected matters more than its length or the precision of the match. Colorado's 3 h samples, whose 06:00–09:00 MST window is recorded in AQS, agree with TEMPO not during sampling (r = 0.12) but three hours later (0.40), and not at all after six hours (0.03). The national sites show that this lag is not universal: at two California sites the 05:00–08:00 window agrees with the column measured in that same window as well as midday sampling does, and across 40 sites sampling 8 h blocks the midday block outperforms the morning block. These observations are consistent with the deepening of the morning mixed layer making a surface sample representative of a larger fraction of the column, at an hour that differs between sites, but they constrain the timing of the best match rather than demonstrating the mechanism behind it. In the Colorado case study, wildfire smoke raised both surface and column HCHO within season and contributed to day-to-day agreement, most clearly in that same post-sampling window.",
"TEMPO therefore provides useful seasonal and episodic context for air toxics monitoring across the United States, and its value for tracking day-to-day variation is greatest when observations are averaged spatially, when the monitor's concentrations are not close to the retrieval noise floor, and when the satellite is matched to the hours in which the sampled air is well mixed. Which of those conditions hold, and which matching window is best, are now questions that can be answered monitor by monitor rather than assumed from a network average."
]);

const out2 = "// content_v5.js - generated by mkcontent5.js; do not edit by hand\n" +
  "module.exports = " + JSON.stringify(C, null, 1) + ";\n";
fs.writeFileSync("content_v5.js", out2);
console.log("after trim pass:", out2.length, "chars");
